/*
    Diablo II Character Editor
    Copyright (C) 2021-2022 Walter Couto

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/
//---------------------------------------------------------------------------

#include "pch.h"
#include <sstream>

namespace d2ce
{
    namespace JsonReaderHelper
    {
        const std::string& GetItemGems()
        {
            static std::string defaultTxt;
            if (defaultTxt.empty())
            {
                std::stringstream ss;
                ss << u8"[\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 3632,\n";
                ss << u8"    \"Key\": \"gemeffect1\",\n";
                ss << u8"    \"enUS\": \"Helm: adds to strength\\nShield: adds to shield's defense\\nWeapon: adds to attack rating\\n\",\n";
                ss << u8"    \"zhTW\": \"頭盔：提高力量\\n盾牌：提高盾牌的防禦\\n武器：提高準確率\\n\",\n";
                ss << u8"    \"deDE\": \"Helm: erhöht Stärke\\nSchild: erhöht Verteidigung des Schildes\\nWaffe: erhöht Angriffswert\\n\",\n";
                ss << u8"    \"esES\": \"Yelmo: aumenta la fuerza\\nEscudo: aumenta la defensa del escudo\\nArma: aumenta el índice de ataque\\n\",\n";
                ss << u8"    \"frFR\": \"Heaume : augmente la Force\\nBouclier : ajoute de la défense au bouclier\\nArme : augmente le score d’attaque\\n\",\n";
                ss << u8"    \"itIT\": \"Elmo: aggiunge Forza\\nScudo: aggiunge difesa allo scudo\\nArma: aggiunge indice d'attacco\\n\",\n";
                ss << u8"    \"koKR\": \"투구: 힘 증가\\n방패: 방패의 방어력 증가\\n무기: 명중률 증가\\n\",\n";
                ss << u8"    \"plPL\": \"Hełm: zwiększa siłę\\nTarcza: zwiększa obronę tarczy\\nBroń: zwiększa skuteczność ataku\\n\",\n";
                ss << u8"    \"esMX\": \"Yelmo: agrega fuerza\\nEscudo: agrega defensa del escudo\\nArma: agrega índice de ataque\\n\",\n";
                ss << u8"    \"jaJP\": \"兜: 筋力が上昇\\n盾: 盾防御力が上昇\\n武器: 命中率が上昇\\n\",\n";
                ss << u8"    \"ptBR\": \"Elmo: aumenta a força\\nEscudo: aumenta a defesa do escudo\\nArma: aumenta a taxa de ataque\\n\",\n";
                ss << u8"    \"ruRU\": \"Шлем: повышает силу\\nЩит: повышает защиту\\nОружие: повышает рейтинг атаки\\n\",\n";
                ss << u8"    \"zhCN\": \"头盔: 增加力量\\n盾牌: 增加盾牌的防御值\\n武器: 增加命中值\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 3633,\n";
                ss << u8"    \"Key\": \"gemeffect2\",\n";
                ss << u8"    \"enUS\": \"Helm: adds to maximum mana\\nShield: adds resistance to cold\\nWeapon: adds cold damage to attack\\n\",\n";
                ss << u8"    \"zhTW\": \"頭盔：提高法力上限\\n護盾：提高冰寒抗性\\n武器：攻擊附加冰寒傷害\",\n";
                ss << u8"    \"deDE\": \"Helm: Erhöht maximales Mana\\nSchild: Erhöht Kältewiderstand\\nWaffe: Fügt Angriffen Kälteschaden hinzu\\n\",\n";
                ss << u8"    \"esES\": \"Yelmo: aumenta el maná máximo\\nEscudo: aumenta la resistencia al frío\\nArma: añade daño de frío al ataque\\n\",\n";
                ss << u8"    \"frFR\": \"Heaume : augmente le mana max.\\nBouclier : augmente la résistance au Froid\\nArme : ajoute des dégâts de Froid à l’attaque\\n\",\n";
                ss << u8"    \"itIT\": \"Elmo: aggiunge mana massimo\\nScudo: aggiunge resistenza al freddo\\nArma: aggiunge danni da freddo\\n\",\n";
                ss << u8"    \"koKR\": \"투구: 최대 마나 증가\\n방패: 냉기 저항 증가\\n무기: 공격에 냉기 피해 추가\\n\",\n";
                ss << u8"    \"plPL\": \"Hełm: zwiększa maksymalną ilość many\\nTarcza: zwiększa odporność na zimno\\nBroń: dodaje obrażenia od zimna\\n\",\n";
                ss << u8"    \"esMX\": \"Yelmo: agrega maná máximo\\nEscudo: agrega resistencia al frío\\nArma: agrega daño de frío al ataque\\n\",\n";
                ss << u8"    \"jaJP\": \"兜: マナ最大値が上昇\\n盾: 冷気耐性が上昇\\n武器: 攻撃に冷気ダメージを追加\\n\",\n";
                ss << u8"    \"ptBR\": \"Elmo: aumenta o máximo de mana\\nEscudo: adiciona resistência a gelo\\nArma: adiciona dano gélido ao ataque\\n\",\n";
                ss << u8"    \"ruRU\": \"Шлем: увеличивает максимальный запас маны\\nЩит: повышает сопротивление льду\\nОружие: добавляет урон от льда при атаках\\n\",\n";
                ss << u8"    \"zhCN\": \"头盔: 增加最大法力\\n盾牌: 增加冰霜抗性\\n武器: 增加攻击时的冰霜伤害\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 3634,\n";
                ss << u8"    \"Key\": \"gemeffect3\",\n";
                ss << u8"    \"enUS\": \"Helm: adds to dexterity\\nShield: adds resistance to poison\\nWeapon: adds poison damage to attack\\n\",\n";
                ss << u8"    \"zhTW\": \"頭盔：提高敏捷\\n護盾：提高毒素抗性\\n武器：攻擊附加毒素傷害\\n\",\n";
                ss << u8"    \"deDE\": \"Helm: Erhöht Geschicklichkeit\\nSchild: Erhöht Giftwiderstand\\nWaffe: Fügt Angriffen Giftschaden hinzu\\n\",\n";
                ss << u8"    \"esES\": \"Yelmo: aumenta la destreza\\nEscudo: aumenta la resistencia al veneno\\nArma: añade daño de veneno al ataque\\n\",\n";
                ss << u8"    \"frFR\": \"Heaume : augmente la dextérité\\nBouclier : augmente la résistance au Poison\\nArme : ajoute des dégâts de Poison à l’attaque\",\n";
                ss << u8"    \"itIT\": \"Elmo: aggiunge Destrezza\\nScudo: aggiunge resistenza al veleno\\nArma: aggiunge danni da veleno\\n\",\n";
                ss << u8"    \"koKR\": \"투구: 민첩 증가\\n방패: 독 저항 증가\\n무기: 공격에 독 피해 추가\\n\",\n";
                ss << u8"    \"plPL\": \"Hełm: zwiększa zręczność\\nTarcza: zwiększa odporność na trucizny\\nBroń: dodaje obrażenia od trucizny\\n\",\n";
                ss << u8"    \"esMX\": \"Yelmo: agrega destreza\\nEscudo: agrega resistencia al veneno\\nArma: agrega daño de veneno al ataque\\n\",\n";
                ss << u8"    \"jaJP\": \"兜: 敏捷性が上昇\\n盾: 毒物耐性が上昇\\n武器: 攻撃に毒ダメージを追加\\n\",\n";
                ss << u8"    \"ptBR\": \"Elmo: aumenta a destreza\\nEscudo: adiciona resistência a veneno\\nArma: adiciona dano venenoso ao ataque\\n\",\n";
                ss << u8"    \"ruRU\": \"Шлем: повышает ловкость\\nЩит: повышает сопротивление яду\\nОружие: добавляет урон от яда при атаках\\n\",\n";
                ss << u8"    \"zhCN\": \"头盔: 增加敏捷\\n盾牌: 增加毒素抗性\\n武器: 增加攻击时的毒素伤害\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 3635,\n";
                ss << u8"    \"Key\": \"gemeffect4\",\n";
                ss << u8"    \"enUS\": \"Helm: adds to maximum life\\nShield: adds resistance to fire\\nWeapon: adds fire damage to attack\\n\",\n";
                ss << u8"    \"zhTW\": \"頭盔：提高生命上限\\n護盾：提高火焰抗性\\n武器：攻擊附加火焰傷害\\n\",\n";
                ss << u8"    \"deDE\": \"Helm: Erhöht maximales Leben\\nSchild: Erhöht Feuerwiderstand\\nWaffe: Fügt Angriffen Feuerschaden hinzu\\n\",\n";
                ss << u8"    \"esES\": \"Yelmo: aumenta la vida máxima\\nEscudo: aumenta la resistencia al fuego\\nArma: añade daño de fuego al ataque\\n\",\n";
                ss << u8"    \"frFR\": \"Heaume : augmente la vie max.\\nBouclier : augmente la résistance au Feu\\nArme : ajoute des dégâts de Feu à l’attaque\",\n";
                ss << u8"    \"itIT\": \"Elmo: aggiunge vita massima\\nScudo: aggiunge resistenza al fuoco\\nArma: aggiunge danni da fuoco\\n\",\n";
                ss << u8"    \"koKR\": \"투구: 최대 생명력 증가\\n방패: 화염 저항 증가\\n무기: 공격에 화염 피해 추가\\n\",\n";
                ss << u8"    \"plPL\": \"Hełm: zwiększa maksymalną ilość zdrowia\\nTarcza: zwiększa odporność na ogień\\nBroń: dodaje obrażenia od ognia\\n\",\n";
                ss << u8"    \"esMX\": \"Yelmo: agrega vida máxima\\nEscudo: agrega resistencia al fuego\\nArma: agrega daño de fuego al ataque\\n\",\n";
                ss << u8"    \"jaJP\": \"兜: ライフ最大値が上昇\\n盾: 火炎耐性が上昇\\n武器: 攻撃に火炎ダメージを追加\\n\",\n";
                ss << u8"    \"ptBR\": \"Elmo: aumenta o máximo de pontos de vida\\nEscudo: adiciona resistência a fogo\\nArma: adiciona dano ígneo ao ataque\\n\",\n";
                ss << u8"    \"ruRU\": \"Шлем: увеличивает максимальный запас здоровья\\nЩит: повышает сопротивление огню\\nОружие: добавляет урон от огня при атаках\\n\",\n";
                ss << u8"    \"zhCN\": \"头盔: 增加最大生命\\n盾牌: 增加火焰抗性\\n武器: 增加攻击时的火焰伤害\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 3636,\n";
                ss << u8"    \"Key\": \"gemeffect5\",\n";
                ss << u8"    \"enUS\": \"Helm: adds to attack rating\\nShield: adds to all resistances\\nWeapon: adds to damage vs. undead\\n\",\n";
                ss << u8"    \"zhTW\": \"頭盔：提高準確率\\n護盾：提高所有抗性\\n武器：提高對不死怪物的傷害\",\n";
                ss << u8"    \"deDE\": \"Helm: Erhöht Angriffswert\\nSchild: Erhöht alle Widerstände\\nWaffe: Erhöht Schaden gegen Untote\",\n";
                ss << u8"    \"esES\": \"Yelmo: aumenta el índice de ataque\\nEscudo: aumenta todas las resistencias\\nArmas: aumenta el daño contra muertos vivientes\\n\",\n";
                ss << u8"    \"frFR\": \"Heaume : augmente le score d’attaque\\nBouclier : augmente toutes les résistances\\nArme : augmente les dégâts infligés aux Morts-vivants\\n\",\n";
                ss << u8"    \"itIT\": \"Elmo: aggiunge indice d'attacco\\nScudo: aggiunge tutte le resistenze\\nArma: aggiunge danni contro i non morti\\n\",\n";
                ss << u8"    \"koKR\": \"투구: 명중률 증가\\n방패: 모든 저항 증가\\n무기: 언데드에게 주는 피해 추가\\n\",\n";
                ss << u8"    \"plPL\": \"Hełm: zwiększa skuteczność ataku\\nTarcza: zwiększa wszystkie odporności\\nBroń: zwiększa obrażenia zadane nieumarłym\\n\",\n";
                ss << u8"    \"esMX\": \"Yelmo: agrega índice de ataque\\nEscudo: agrega todas las resistencias\\nArma: agrega daño contra los no muertos\\n\",\n";
                ss << u8"    \"jaJP\": \"兜: 命中率が上昇\\n盾: 全属性耐性が上昇\\n武器: アンデッドへのダメージが増加\\n\",\n";
                ss << u8"    \"ptBR\": \"Elmo: aumenta a taxa de ataque\\nEscudo: aumenta todas as resistências\\nArma: aumenta o dano contra mortos-vivos\\n\",\n";
                ss << u8"    \"ruRU\": \"Шлем: повышает рейтинг атаки\\nЩит: повышает сопротивление всем видам урона\\nОружие: повышает урон против нежити\\n\",\n";
                ss << u8"    \"zhCN\": \"头盔: 增加命中值\\n盾牌: 增加所有抗性\\n武器: 增加对亡灵的伤害\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 3637,\n";
                ss << u8"    \"Key\": \"gemeffect6\",\n";
                ss << u8"    \"enUS\": \"Helm: adds to chance to find magic items\\nShield: adds resistance to lightning\\nWeapon: adds lightning damage to attack\\n\",\n";
                ss << u8"    \"zhTW\": \"頭盔：提高魔法物品尋獲機率\\n護盾：提高電擊抗性\\n武器：攻擊附加電擊傷害\\n\",\n";
                ss << u8"    \"deDE\": \"Helm: Erhöht Chance, magische Gegenstände zu finden\\nSchild: Erhöht Blitzwiderstand\\nWaffe: Fügt Angriffen Blitzschaden hinzu\\n\",\n";
                ss << u8"    \"esES\": \"Yelmo: aumenta la probabilidad de encontrar objetos mágicos\\nEscudo: aumenta la resistencia a los rayos\\nArma: añade daño de rayos al ataque\\n\",\n";
                ss << u8"    \"frFR\": \"Heaume : augmente les chances de trouver des objets magiques\\nBouclier : augmente la résistance à la Foudre\\nArme : ajoute des dégâts de Foudre à l’attaque\\n\",\n";
                ss << u8"    \"itIT\": \"Elmo: aggiunge alla probabilità di trovare oggetti magici\\nScudo: aggiunge resistenza al fulmine\\nArma: aggiunge danni da fulmine\\n\",\n";
                ss << u8"    \"koKR\": \"투구: 마법 아이템 획득 확률 증가\\n방패: 번개 저항 증가\\n무기: 공격에 번개 피해 추가\\n\",\n";
                ss << u8"    \"plPL\": \"Hełm: zwiększa szansę na znalezienie magicznych przedmiotów\\nTarcza: zwiększa odporność na błyskawice\\nBroń: dodaje obrażenia od błyskawic\\n\",\n";
                ss << u8"    \"esMX\": \"Yelmo: agrega probabilidad de encontrar objetos mágicos\\nEscudo: agrega resistencia al rayo\\nArma: agrega daño de rayo al ataque\\n\",\n";
                ss << u8"    \"jaJP\": \"兜: マジックアイテムのドロップ率が上昇\\n盾: 電撃耐性が上昇\\n武器: 攻撃に電撃ダメージを追加\\n\",\n";
                ss << u8"    \"ptBR\": \"Elmo: aumenta a chance de encontrar itens mágicos\\nEscudo: adiciona resistência elétrica\\nArma: adiciona dano elétrico ao ataque\\n\",\n";
                ss << u8"    \"ruRU\": \"Шлем: повышает вероятность найти магические предметы\\nЩит: повышает сопротивление молнии\\nОружие: добавляет урон от молнии при атаках\\n\",\n";
                ss << u8"    \"zhCN\": \"头盔: 增加找到魔法物品几率\\n盾牌: 增加闪电抗性\\n武器: 增加攻击时的闪电伤害\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 3638,\n";
                ss << u8"    \"Key\": \"gemeffect7\",\n";
                ss << u8"    \"enUS\": \"Helm: adds mana and life regeneration\\nShield: adds attacker takes damage\\nWeapon: adds mana and life steal to attack\\n\",\n";
                ss << u8"    \"zhTW\": \"頭盔：提高法力和生命恢復率\\n護盾：提高攻擊者反傷\\n武器：攻擊附加法力和生命竊取\\n\",\n";
                ss << u8"    \"deDE\": \"Helm: Erhöht Mana- und Lebensregeneration\\nSchild: Angreifer erleidet Schaden\\nWaffe: Fügt Angriffen Mana- und Lebensraub hinzu\\n\",\n";
                ss << u8"    \"esES\": \"Yelmo: aumenta la regeneración de vida y maná\\nEscudo: añade daño a los atacantes\\nArma: añade robo de vida y maná al ataque\\n\",\n";
                ss << u8"    \"frFR\": \"Heaume : accroît la régénération de mana et de vie\\nBouclier : augmente les dégâts subis par l’adversaire\\nArme : ajoute vol de mana et de vie à l’attaque\",\n";
                ss << u8"    \"itIT\": \"Elmo: aggiunge rigenerazione di mana e vita\\nScudo: aggiunge danni subiti dagli attaccanti\\nArma: aggiunge furto di mana e vita\\n\",\n";
                ss << u8"    \"koKR\": \"투구: 마나 및 생명력 재생 속도 증가\\n방패: 공격자에게 주는 피해 추가\\n무기: 공격에 마나 및 생명력 훔치기 추가\\n\",\n";
                ss << u8"    \"plPL\": \"Hełm: zwiększa szybkość regeneracji many i zdrowia\\nTarcza: sprawia, że atakujący otrzymuje obrażenia\\nBroń: zapewnia kradzież many i zdrowia\\n\",\n";
                ss << u8"    \"esMX\": \"Yelmo: agrega regeneración de vida y maná\\nEscudo: agrega que el atacante recibe daño\\nArma: agrega robo de vida y maná al ataque\\n\",\n";
                ss << u8"    \"jaJP\": \"兜: ライフとマナの回復速度が上昇\\n盾: 反撃ダメージを追加\\n武器: 攻撃時にライフとマナを奪う効果を追加\\n\",\n";
                ss << u8"    \"ptBR\": \"Elmo: adiciona regeneração de pontos de vida e mana\\nEscudo: adiciona recebimento de dano pelo agressor\\nArma: adiciona roubo de pontos de vida e mana ao ataque\\n\",\n";
                ss << u8"    \"ruRU\": \"Шлем: повышает скорость восполнения маны и здоровья\\nЩит: наносит урон атакующим противникам\\nОружие: позволяет похищать ману и здоровье при атаках\\n\",\n";
                ss << u8"    \"zhCN\": \"头盔: 增加法力和生命回复\\n盾牌: 增加攻击者受到的伤害\\n武器: 增加攻击时偷取的法力和生命\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 4019,\n";
                ss << u8"    \"Key\": \"Use\",\n";
                ss << u8"    \"enUS\": \"Use Gem\",\n";
                ss << u8"    \"zhTW\": \"使用寶石\",\n";
                ss << u8"    \"deDE\": \"Edelstein benutzen\",\n";
                ss << u8"    \"esES\": \"Usar gema\",\n";
                ss << u8"    \"frFR\": \"Utiliser une gemme\",\n";
                ss << u8"    \"itIT\": \"Usa Gemma\",\n";
                ss << u8"    \"koKR\": \"보석 사용\",\n";
                ss << u8"    \"plPL\": \"Użyj klejnotu\",\n";
                ss << u8"    \"esMX\": \"Usar gema\",\n";
                ss << u8"    \"jaJP\": \"宝石を使う\",\n";
                ss << u8"    \"ptBR\": \"Usar gema\",\n";
                ss << u8"    \"ruRU\": \"Использовать самоцвет\",\n";
                ss << u8"    \"zhCN\": \"使用宝石\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 11073,\n";
                ss << u8"    \"Key\": \"GemXp1\",\n";
                ss << u8"    \"enUS\": \"Helms:\",\n";
                ss << u8"    \"zhTW\": \"頭盔：\",\n";
                ss << u8"    \"deDE\": \"Helme:\",\n";
                ss << u8"    \"esES\": \"Yelmos:\",\n";
                ss << u8"    \"frFR\": \"Heaumes :\",\n";
                ss << u8"    \"itIT\": \"Elmi:\",\n";
                ss << u8"    \"koKR\": \"투구:\",\n";
                ss << u8"    \"plPL\": \"Hełm:\",\n";
                ss << u8"    \"esMX\": \"Yelmos:\",\n";
                ss << u8"    \"jaJP\": \"兜:\",\n";
                ss << u8"    \"ptBR\": \"Elmos:\",\n";
                ss << u8"    \"ruRU\": \"Шлемы:\",\n";
                ss << u8"    \"zhCN\": \"头盔:\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 11074,\n";
                ss << u8"    \"Key\": \"GemXp2\",\n";
                ss << u8"    \"enUS\": \"Shields:\",\n";
                ss << u8"    \"zhTW\": \"盾牌：\",\n";
                ss << u8"    \"deDE\": \"Schilde:\",\n";
                ss << u8"    \"esES\": \"Escudos:\",\n";
                ss << u8"    \"frFR\": \"Boucliers :\",\n";
                ss << u8"    \"itIT\": \"Scudi:\",\n";
                ss << u8"    \"koKR\": \"방패:\",\n";
                ss << u8"    \"plPL\": \"Tarcza:\",\n";
                ss << u8"    \"esMX\": \"Escudos:\",\n";
                ss << u8"    \"jaJP\": \"盾:\",\n";
                ss << u8"    \"ptBR\": \"Escudos:\",\n";
                ss << u8"    \"ruRU\": \"Щиты:\",\n";
                ss << u8"    \"zhCN\": \"盾牌:\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 11075,\n";
                ss << u8"    \"Key\": \"GemXp3\",\n";
                ss << u8"    \"enUS\": \"Weapons:\",\n";
                ss << u8"    \"zhTW\": \"武器：\",\n";
                ss << u8"    \"deDE\": \"Waffen:\",\n";
                ss << u8"    \"esES\": \"Armas:\",\n";
                ss << u8"    \"frFR\": \"Armes :\",\n";
                ss << u8"    \"itIT\": \"Armi:\",\n";
                ss << u8"    \"koKR\": \"무기:\",\n";
                ss << u8"    \"plPL\": \"Broń:\",\n";
                ss << u8"    \"esMX\": \"Armas:\",\n";
                ss << u8"    \"jaJP\": \"武器:\",\n";
                ss << u8"    \"ptBR\": \"Armas:\",\n";
                ss << u8"    \"ruRU\": \"Оружие:\",\n";
                ss << u8"    \"zhCN\": \"武器:\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 11076,\n";
                ss << u8"    \"Key\": \"GemXp4\",\n";
                ss << u8"    \"enUS\": \"Armor:\",\n";
                ss << u8"    \"zhTW\": \"護甲：\",\n";
                ss << u8"    \"deDE\": \"Rüstung:\",\n";
                ss << u8"    \"esES\": \"Armadura:\",\n";
                ss << u8"    \"frFR\": \"Armures :\",\n";
                ss << u8"    \"itIT\": \"Armature:\",\n";
                ss << u8"    \"koKR\": \"방어구:\",\n";
                ss << u8"    \"plPL\": \"Zbroja:\",\n";
                ss << u8"    \"esMX\": \"Armadura:\",\n";
                ss << u8"    \"jaJP\": \"鎧:\",\n";
                ss << u8"    \"ptBR\": \"Armaduras:\",\n";
                ss << u8"    \"ruRU\": \"Броня:\",\n";
                ss << u8"    \"zhCN\": \"护甲:\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 21265,\n";
                ss << u8"    \"Key\": \"GemeffectX11\",\n";
                ss << u8"    \"enUS\": \"Adds to Strength\",\n";
                ss << u8"    \"zhTW\": \"提高力量\",\n";
                ss << u8"    \"deDE\": \"Erhöht Stärke\",\n";
                ss << u8"    \"esES\": \"Aumenta la fuerza\",\n";
                ss << u8"    \"frFR\": \"Augmente la force\",\n";
                ss << u8"    \"itIT\": \"Aggiunge Forza\",\n";
                ss << u8"    \"koKR\": \"힘 증가\",\n";
                ss << u8"    \"plPL\": \"Zwiększa siłę\",\n";
                ss << u8"    \"esMX\": \"Agrega fuerza\",\n";
                ss << u8"    \"jaJP\": \"筋力が上昇\",\n";
                ss << u8"    \"ptBR\": \"Aumenta a força\",\n";
                ss << u8"    \"ruRU\": \"Повышает силу\",\n";
                ss << u8"    \"zhCN\": \"增加力量\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 21266,\n";
                ss << u8"    \"Key\": \"GemeffectX12\",\n";
                ss << u8"    \"enUS\": \"Adds to Defense\",\n";
                ss << u8"    \"zhTW\": \"提高防禦\",\n";
                ss << u8"    \"deDE\": \"Erhöht Verteidigung\",\n";
                ss << u8"    \"esES\": \"Aumenta la defensa\",\n";
                ss << u8"    \"frFR\": \"Augmente la défense\",\n";
                ss << u8"    \"itIT\": \"Aggiunge difesa\",\n";
                ss << u8"    \"koKR\": \"방어력 증가\",\n";
                ss << u8"    \"plPL\": \"Zwiększa obronę\",\n";
                ss << u8"    \"esMX\": \"Agrega defensa\",\n";
                ss << u8"    \"jaJP\": \"防御力が上昇\",\n";
                ss << u8"    \"ptBR\": \"Aumenta a defesa\",\n";
                ss << u8"    \"ruRU\": \"Повышает защиту\",\n";
                ss << u8"    \"zhCN\": \"增加防御\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 21267,\n";
                ss << u8"    \"Key\": \"GemeffectX13\",\n";
                ss << u8"    \"enUS\": \"Adds to Attack Rating\",\n";
                ss << u8"    \"zhTW\": \"提高準確率\",\n";
                ss << u8"    \"deDE\": \"Erhöht Angriffswert\",\n";
                ss << u8"    \"esES\": \"Aumenta el índice de ataque\",\n";
                ss << u8"    \"frFR\": \"Augmente le score d’attaque\",\n";
                ss << u8"    \"itIT\": \"Aggiunge indice d'attacco\",\n";
                ss << u8"    \"koKR\": \"명중률 증가\",\n";
                ss << u8"    \"plPL\": \"Zwiększa skuteczność ataku\",\n";
                ss << u8"    \"esMX\": \"Agrega índice de ataque\",\n";
                ss << u8"    \"jaJP\": \"命中率が上昇\",\n";
                ss << u8"    \"ptBR\": \"Aumenta a taxa de ataque\",\n";
                ss << u8"    \"ruRU\": \"Повышает рейтинг атаки\",\n";
                ss << u8"    \"zhCN\": \"增加命中值\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 21268,\n";
                ss << u8"    \"Key\": \"GemeffectX21\",\n";
                ss << u8"    \"enUS\": \"Adds to Maximum Mana\",\n";
                ss << u8"    \"zhTW\": \"提高法力上限\",\n";
                ss << u8"    \"deDE\": \"Erhöht maximales Mana\",\n";
                ss << u8"    \"esES\": \"Aumenta el maná máximo\",\n";
                ss << u8"    \"frFR\": \"Augmente le mana max.\",\n";
                ss << u8"    \"itIT\": \"Aggiunge mana massimo\",\n";
                ss << u8"    \"koKR\": \"최대 마나 증가\",\n";
                ss << u8"    \"plPL\": \"Zwiększa maksymalną ilość many\",\n";
                ss << u8"    \"esMX\": \"Agrega maná máximo\",\n";
                ss << u8"    \"jaJP\": \"マナ最大値が上昇\",\n";
                ss << u8"    \"ptBR\": \"Aumenta o máximo de mana\",\n";
                ss << u8"    \"ruRU\": \"Увеличивает максимальный запас маны\",\n";
                ss << u8"    \"zhCN\": \"增加最大法力\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 21269,\n";
                ss << u8"    \"Key\": \"GemeffectX22\",\n";
                ss << u8"    \"enUS\": \"Adds Resistance to Cold\",\n";
                ss << u8"    \"zhTW\": \"提高冰寒抗性\",\n";
                ss << u8"    \"deDE\": \"Erhöht Kältewiderstand\",\n";
                ss << u8"    \"esES\": \"Aumenta la resistencia al frío\",\n";
                ss << u8"    \"frFR\": \"Augmente la résistance au Foid\",\n";
                ss << u8"    \"itIT\": \"Aggiunge resistenza al freddo\",\n";
                ss << u8"    \"koKR\": \"냉기 저항 증가\",\n";
                ss << u8"    \"plPL\": \"Zwiększa odporność na zimno\",\n";
                ss << u8"    \"esMX\": \"Agrega resistencia al frío\",\n";
                ss << u8"    \"jaJP\": \"冷気耐性が上昇\",\n";
                ss << u8"    \"ptBR\": \"Adiciona resistência a gelo\",\n";
                ss << u8"    \"ruRU\": \"Повышает сопротивление льду\",\n";
                ss << u8"    \"zhCN\": \"增加冰霜抗性\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 21270,\n";
                ss << u8"    \"Key\": \"GemeffectX23\",\n";
                ss << u8"    \"enUS\": \"Adds Cold Damage to Attack\",\n";
                ss << u8"    \"zhTW\": \"攻擊附加冰寒傷害\",\n";
                ss << u8"    \"deDE\": \"Fügt Angriffen Kälteschaden hinzu\",\n";
                ss << u8"    \"esES\": \"Añade daño de frío al ataque\",\n";
                ss << u8"    \"frFR\": \"Ajoute des dégâts de Froid\",\n";
                ss << u8"    \"itIT\": \"Aggiunge danni da freddo\",\n";
                ss << u8"    \"koKR\": \"공격에 냉기 피해 추가\",\n";
                ss << u8"    \"plPL\": \"Dodaje obrażenia od zimna\",\n";
                ss << u8"    \"esMX\": \"Agrega daño de frío al ataque\",\n";
                ss << u8"    \"jaJP\": \"攻撃に冷気ダメージを追加\",\n";
                ss << u8"    \"ptBR\": \"Adiciona dano gélido ao ataque\",\n";
                ss << u8"    \"ruRU\": \"Добавляет урон от льда при атаках\",\n";
                ss << u8"    \"zhCN\": \"增加攻击时的冰霜伤害\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 21271,\n";
                ss << u8"    \"Key\": \"GemeffectX31\",\n";
                ss << u8"    \"enUS\": \"Adds to Dexterity\",\n";
                ss << u8"    \"zhTW\": \"提高敏捷\",\n";
                ss << u8"    \"deDE\": \"Erhöht Geschicklichkeit\",\n";
                ss << u8"    \"esES\": \"Aumenta la destreza\",\n";
                ss << u8"    \"frFR\": \"Augmente la dextérité\",\n";
                ss << u8"    \"itIT\": \"Aggiunge Destrezza\",\n";
                ss << u8"    \"koKR\": \"민첩 증가\",\n";
                ss << u8"    \"plPL\": \"Zwiększa zręczność\",\n";
                ss << u8"    \"esMX\": \"Agrega destreza\",\n";
                ss << u8"    \"jaJP\": \"敏捷性が上昇\",\n";
                ss << u8"    \"ptBR\": \"Aumenta a destreza\",\n";
                ss << u8"    \"ruRU\": \"Повышает ловкость\",\n";
                ss << u8"    \"zhCN\": \"增加敏捷\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 21272,\n";
                ss << u8"    \"Key\": \"GemeffectX32\",\n";
                ss << u8"    \"enUS\": \"Adds Resistance to Poison\",\n";
                ss << u8"    \"zhTW\": \"提高毒素抗性\",\n";
                ss << u8"    \"deDE\": \"Erhöht Giftwiderstand\",\n";
                ss << u8"    \"esES\": \"Aumenta la resistencia al veneno\",\n";
                ss << u8"    \"frFR\": \"Augmente la résistance au Poison\",\n";
                ss << u8"    \"itIT\": \"Aggiunge resistenza al veleno\",\n";
                ss << u8"    \"koKR\": \"독 저항 증가\",\n";
                ss << u8"    \"plPL\": \"Zwiększa odporność na trucizny\",\n";
                ss << u8"    \"esMX\": \"Agrega resistencia al veneno\",\n";
                ss << u8"    \"jaJP\": \"毒物耐性が上昇\",\n";
                ss << u8"    \"ptBR\": \"Adiciona resistência a veneno\",\n";
                ss << u8"    \"ruRU\": \"Повышает сопротивление яду\",\n";
                ss << u8"    \"zhCN\": \"增加毒素抗性\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 21273,\n";
                ss << u8"    \"Key\": \"GemeffectX33\",\n";
                ss << u8"    \"enUS\": \"Adds Poison Damage to Attack\",\n";
                ss << u8"    \"zhTW\": \"攻擊附加毒素傷害\",\n";
                ss << u8"    \"deDE\": \"Fügt Angriffen Giftschaden hinzu\",\n";
                ss << u8"    \"esES\": \"Añade daño de veneno al ataque\",\n";
                ss << u8"    \"frFR\": \"Ajoute des dégâts de Poison\",\n";
                ss << u8"    \"itIT\": \"Aggiunge danni da veleno\",\n";
                ss << u8"    \"koKR\": \"공격에 독 피해 추가\",\n";
                ss << u8"    \"plPL\": \"Dodaje obrażenia od trucizny\",\n";
                ss << u8"    \"esMX\": \"Agrega daño de veneno al ataque\",\n";
                ss << u8"    \"jaJP\": \"攻撃に毒ダメージを追加\",\n";
                ss << u8"    \"ptBR\": \"Adiciona dano venenoso ao ataque\",\n";
                ss << u8"    \"ruRU\": \"Добавляет урон от яда при атаках\",\n";
                ss << u8"    \"zhCN\": \"增加攻击时的毒素伤害\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 21274,\n";
                ss << u8"    \"Key\": \"GemeffectX41\",\n";
                ss << u8"    \"enUS\": \"Adds to Maximum Life\",\n";
                ss << u8"    \"zhTW\": \"提高生命上限\",\n";
                ss << u8"    \"deDE\": \"Erhöht maximales Leben\",\n";
                ss << u8"    \"esES\": \"Aumenta la vida máxima\",\n";
                ss << u8"    \"frFR\": \"Augmente la vie max.\",\n";
                ss << u8"    \"itIT\": \"Aggiunge vita massima\",\n";
                ss << u8"    \"koKR\": \"최대 생명력 증가\",\n";
                ss << u8"    \"plPL\": \"Zwiększa maksymalną ilość zdrowia\",\n";
                ss << u8"    \"esMX\": \"Agrega vida máxima\",\n";
                ss << u8"    \"jaJP\": \"ライフ最大値が上昇\",\n";
                ss << u8"    \"ptBR\": \"Aumenta o máximo de pontos de vida\",\n";
                ss << u8"    \"ruRU\": \"Увеличивает максимальный запас здоровья\",\n";
                ss << u8"    \"zhCN\": \"增加最大生命\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 21275,\n";
                ss << u8"    \"Key\": \"GemeffectX42\",\n";
                ss << u8"    \"enUS\": \"Adds Resistance to Fire\",\n";
                ss << u8"    \"zhTW\": \"提高火焰抗性\",\n";
                ss << u8"    \"deDE\": \"Erhöht Feuerwiderstand\",\n";
                ss << u8"    \"esES\": \"Aumenta la resistencia al fuego\",\n";
                ss << u8"    \"frFR\": \"Augmente la résistance au Feu\",\n";
                ss << u8"    \"itIT\": \"Aggiunge resistenza al fuoco\",\n";
                ss << u8"    \"koKR\": \"화염 저항 증가\",\n";
                ss << u8"    \"plPL\": \"Zwiększa odporność na ogień\",\n";
                ss << u8"    \"esMX\": \"Agrega resistencia al fuego\",\n";
                ss << u8"    \"jaJP\": \"火炎耐性が上昇\",\n";
                ss << u8"    \"ptBR\": \"Adiciona resistência a fogo\",\n";
                ss << u8"    \"ruRU\": \"Повышает сопротивление огню\",\n";
                ss << u8"    \"zhCN\": \"增加火焰抗性\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 21276,\n";
                ss << u8"    \"Key\": \"GemeffectX43\",\n";
                ss << u8"    \"enUS\": \"Adds Fire Damage to Attack\",\n";
                ss << u8"    \"zhTW\": \"攻擊附加火焰傷害\",\n";
                ss << u8"    \"deDE\": \"Fügt Angriffen Feuerschaden hinzu\",\n";
                ss << u8"    \"esES\": \"Añade daño de fuego al ataque\",\n";
                ss << u8"    \"frFR\": \"Ajoute des dégâts de Feu\",\n";
                ss << u8"    \"itIT\": \"Aggiunge danni da fuoco\",\n";
                ss << u8"    \"koKR\": \"공격에 화염 피해 추가\",\n";
                ss << u8"    \"plPL\": \"Dodaje obrażenia od ognia\",\n";
                ss << u8"    \"esMX\": \"Agrega daño de fuego al ataque\",\n";
                ss << u8"    \"jaJP\": \"攻撃に火炎ダメージを追加\",\n";
                ss << u8"    \"ptBR\": \"Adiciona dano ígneo ao ataque\",\n";
                ss << u8"    \"ruRU\": \"Добавляет урон от огня при атаках\",\n";
                ss << u8"    \"zhCN\": \"增加攻击时的火焰伤害\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 21277,\n";
                ss << u8"    \"Key\": \"GemeffectX51\",\n";
                ss << u8"    \"enUS\": \"Adds to Attack Rating\",\n";
                ss << u8"    \"zhTW\": \"提高準確率\",\n";
                ss << u8"    \"deDE\": \"Erhöht Angriffswert\",\n";
                ss << u8"    \"esES\": \"Aumenta el índice de ataque\",\n";
                ss << u8"    \"frFR\": \"Augmente le score d’attaque\",\n";
                ss << u8"    \"itIT\": \"Aggiunge indice d'attacco\",\n";
                ss << u8"    \"koKR\": \"명중률 증가\",\n";
                ss << u8"    \"plPL\": \"Zwiększa skuteczność ataku\",\n";
                ss << u8"    \"esMX\": \"Agrega índice de ataque\",\n";
                ss << u8"    \"jaJP\": \"命中率が上昇\",\n";
                ss << u8"    \"ptBR\": \"Aumenta a taxa de ataque\",\n";
                ss << u8"    \"ruRU\": \"Повышает рейтинг атаки\",\n";
                ss << u8"    \"zhCN\": \"增加命中值\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 21278,\n";
                ss << u8"    \"Key\": \"GemeffectX52\",\n";
                ss << u8"    \"enUS\": \"Adds to All Resistances\",\n";
                ss << u8"    \"zhTW\": \"提高所有抗性\",\n";
                ss << u8"    \"deDE\": \"Erhöht alle Widerstände\",\n";
                ss << u8"    \"esES\": \"Aumenta todas las resistencias\",\n";
                ss << u8"    \"frFR\": \"Augmente toutes les résistances\",\n";
                ss << u8"    \"itIT\": \"Aggiunge tutte le resistenze\",\n";
                ss << u8"    \"koKR\": \"모든 저항 증가\",\n";
                ss << u8"    \"plPL\": \"Zwiększa wszystkie odporności\",\n";
                ss << u8"    \"esMX\": \"Agrega todas las resistencias\",\n";
                ss << u8"    \"jaJP\": \"全属性耐性が上昇\",\n";
                ss << u8"    \"ptBR\": \"Aumenta todas as resistências\",\n";
                ss << u8"    \"ruRU\": \"Повышает все виды сопротивления\",\n";
                ss << u8"    \"zhCN\": \"增加所有抗性\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 21279,\n";
                ss << u8"    \"Key\": \"GemeffectX53\",\n";
                ss << u8"    \"enUS\": \"Adds to Damage vs. Undead\",\n";
                ss << u8"    \"zhTW\": \"提高對不死怪物的傷害\",\n";
                ss << u8"    \"deDE\": \"Erhöht Schaden gegen Untote\",\n";
                ss << u8"    \"esES\": \"Aumenta el daño contra muertos vivientes\",\n";
                ss << u8"    \"frFR\": \"Augmente les dégâts infligés aux Morts-vivants\",\n";
                ss << u8"    \"itIT\": \"Aggiunge danni contro i non morti\",\n";
                ss << u8"    \"koKR\": \"언데드에게 주는 피해 추가\",\n";
                ss << u8"    \"plPL\": \"Zwiększa obrażenia zadane nieumarłym\",\n";
                ss << u8"    \"esMX\": \"Agrega daño contra los no muertos\",\n";
                ss << u8"    \"jaJP\": \"アンデッドへのダメージが増加\",\n";
                ss << u8"    \"ptBR\": \"Aumenta o dano contra mortos-vivos\",\n";
                ss << u8"    \"ruRU\": \"Повышает урон против нежити\",\n";
                ss << u8"    \"zhCN\": \"增加对亡灵的伤害\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 21280,\n";
                ss << u8"    \"Key\": \"GemeffectX61\",\n";
                ss << u8"    \"enUS\": \"Adds to Chance to Find Magic Items\",\n";
                ss << u8"    \"zhTW\": \"提高魔法物品尋獲機率\",\n";
                ss << u8"    \"deDE\": \"Erhöht Chance, magische Gegenstände zu finden\",\n";
                ss << u8"    \"esES\": \"Aumenta la probabilidad de encontrar objetos mágicos\",\n";
                ss << u8"    \"frFR\": \"Augmente les chances de trouver des objets magiques\",\n";
                ss << u8"    \"itIT\": \"Aggiunge probabilità di trovare oggetti magici\",\n";
                ss << u8"    \"koKR\": \"마법 아이템 획득 확률 증가\",\n";
                ss << u8"    \"plPL\": \"Zwiększa szansę znalezienia magicznych przedmiotów\",\n";
                ss << u8"    \"esMX\": \"Agrega probabilidad de encontrar objetos mágicos\",\n";
                ss << u8"    \"jaJP\": \"マジックアイテムのドロップ率が上昇\",\n";
                ss << u8"    \"ptBR\": \"Aumenta a chance de encontrar itens mágicos\",\n";
                ss << u8"    \"ruRU\": \"Повышает вероятность найти магические предметы\",\n";
                ss << u8"    \"zhCN\": \"增加找到魔法物品几率\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 21281,\n";
                ss << u8"    \"Key\": \"GemeffectX62\",\n";
                ss << u8"    \"enUS\": \"Adds Resistance to Lightning\",\n";
                ss << u8"    \"zhTW\": \"提高電擊抗性\",\n";
                ss << u8"    \"deDE\": \"Erhöht Blitzwiderstand\",\n";
                ss << u8"    \"esES\": \"Aumenta la resistencia a los rayos\",\n";
                ss << u8"    \"frFR\": \"Augmente la résistance à la Foudre\",\n";
                ss << u8"    \"itIT\": \"Aggiunge resistenza al fulmine\",\n";
                ss << u8"    \"koKR\": \"번개 저항 증가\",\n";
                ss << u8"    \"plPL\": \"Zwiększa odporność na błyskawice\",\n";
                ss << u8"    \"esMX\": \"Agrega resistencia al rayo\",\n";
                ss << u8"    \"jaJP\": \"電撃耐性が上昇\",\n";
                ss << u8"    \"ptBR\": \"Adiciona resistência elétrica\",\n";
                ss << u8"    \"ruRU\": \"Повышает сопротивление молнии\",\n";
                ss << u8"    \"zhCN\": \"增加闪电抗性\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 21282,\n";
                ss << u8"    \"Key\": \"GemeffectX63\",\n";
                ss << u8"    \"enUS\": \"Adds Lightning Damage to Attack\",\n";
                ss << u8"    \"zhTW\": \"攻擊附加電擊傷害\",\n";
                ss << u8"    \"deDE\": \"Fügt Angriffen Blitzschaden hinzu\",\n";
                ss << u8"    \"esES\": \"Añade daño de rayos al ataque\",\n";
                ss << u8"    \"frFR\": \"Ajoute des dégâts de Foudre\",\n";
                ss << u8"    \"itIT\": \"Aggiunge danni da fulmine\",\n";
                ss << u8"    \"koKR\": \"공격에 번개 피해 추가\",\n";
                ss << u8"    \"plPL\": \"Dodaje obrażenia od błyskawic\",\n";
                ss << u8"    \"esMX\": \"Agrega daño de rayo al ataque\",\n";
                ss << u8"    \"jaJP\": \"攻撃に電撃ダメージを追加\",\n";
                ss << u8"    \"ptBR\": \"Adiciona dano elétrico ao ataque\",\n";
                ss << u8"    \"ruRU\": \"Добавляет урон от молнии при атаках\",\n";
                ss << u8"    \"zhCN\": \"增加攻击时的闪电伤害\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 21283,\n";
                ss << u8"    \"Key\": \"GemeffectX71\",\n";
                ss << u8"    \"enUS\": \"Adds Mana and Life Regeneration\",\n";
                ss << u8"    \"zhTW\": \"提高法力和生命恢復率\",\n";
                ss << u8"    \"deDE\": \"Erhöht Mana- und Lebensregeneration\",\n";
                ss << u8"    \"esES\": \"Añade regeneración de vida y maná\",\n";
                ss << u8"    \"frFR\": \"Accroit la régénération de mana et de vie\",\n";
                ss << u8"    \"itIT\": \"Aggiunge rigenerazione di mana e vita\",\n";
                ss << u8"    \"koKR\": \"마나 및 생명력 재생 속도 증가\",\n";
                ss << u8"    \"plPL\": \"Zwiększa regenerację zdrowia i many\",\n";
                ss << u8"    \"esMX\": \"Agrega regeneración de vida y maná\",\n";
                ss << u8"    \"jaJP\": \"ライフとマナの回復速度が上昇\",\n";
                ss << u8"    \"ptBR\": \"Adiciona regeneração de pontos de vida e mana\",\n";
                ss << u8"    \"ruRU\": \"Повышает скорость восполнения маны и здоровья\",\n";
                ss << u8"    \"zhCN\": \"增加法力和生命回复\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 21284,\n";
                ss << u8"    \"Key\": \"GemeffectX72\",\n";
                ss << u8"    \"enUS\": \"Adds Attacker Takes Damage\",\n";
                ss << u8"    \"zhTW\": \"提高攻擊者反傷\",\n";
                ss << u8"    \"deDE\": \"Angreifer erleiden Schaden\",\n";
                ss << u8"    \"esES\": \"Añade daño a los atacantes\",\n";
                ss << u8"    \"frFR\": \"Ajoute des dégâts subis par l’attaquant\",\n";
                ss << u8"    \"itIT\": \"Aggiunge danni subiti dagli attaccanti\",\n";
                ss << u8"    \"koKR\": \"공격자에게 주는 피해 추가\",\n";
                ss << u8"    \"plPL\": \"Sprawia, że atakujący otrzymuje obrażenia\",\n";
                ss << u8"    \"esMX\": \"Agrega que el atacante recibe daño\",\n";
                ss << u8"    \"jaJP\": \"反撃ダメージを追加\",\n";
                ss << u8"    \"ptBR\": \"Adiciona recebimento de dano pelo agressor\",\n";
                ss << u8"    \"ruRU\": \"Наносит урон атакующим противникам\",\n";
                ss << u8"    \"zhCN\": \"增加攻击者受到的伤害\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 21285,\n";
                ss << u8"    \"Key\": \"GemeffectX73\",\n";
                ss << u8"    \"enUS\": \"Adds Mana and Life Steal to Attack\",\n";
                ss << u8"    \"zhTW\": \"攻擊附加法力和生命竊取\",\n";
                ss << u8"    \"deDE\": \"Fügt Angriff Mana- und Lebensraub hinzu\",\n";
                ss << u8"    \"esES\": \"Añade robo de vida y maná al ataque\",\n";
                ss << u8"    \"frFR\": \"Ajoute vol de mana et de vie aux dégâts\",\n";
                ss << u8"    \"itIT\": \"Aggiunge furto di mana e vita\",\n";
                ss << u8"    \"koKR\": \"공격에 마나 및 생명력 훔치기 추가\",\n";
                ss << u8"    \"plPL\": \"Zapewnia kradzież many i zdrowia\",\n";
                ss << u8"    \"esMX\": \"Agrega robo de vida y maná al ataque\",\n";
                ss << u8"    \"jaJP\": \"攻撃時にライフとマナを奪う効果を追加\",\n";
                ss << u8"    \"ptBR\": \"Adiciona roubo de pontos de vida e mana ao ataque\",\n";
                ss << u8"    \"ruRU\": \"Позволяет похищать ману и здоровье при атаках\",\n";
                ss << u8"    \"zhCN\": \"增加攻击时偷取的法力和生命\"\n";
                ss << u8"  }\n";
                ss << u8"]\n";
                defaultTxt = ss.str();
            }
            return defaultTxt;
        }
    }
}