/*
    Diablo II Character Editor
    Copyright (C) 2021-2023 Walter Couto

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/
//---------------------------------------------------------------------------

#include "pch.h"
#include <sstream>

namespace d2ce
{
    namespace JsonReaderHelper
    {
        const std::string& GetBankExpansionLayout()
        {
            static std::string defaultTxt;
            if (defaultTxt.empty())
            {
                std::stringstream ss;
                ss << u8"{\n";
                ss << u8"    \"basedOn\": \"BankOriginalLayout.json\",\n";
                ss << u8"    \"type\": \"BankPanel\", \"name\": \"BankExpansionLayout\",\n";
                ss << u8"    \"children\": [\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"ClickCatcherWidget\", \"name\": \"click_catcher\",\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"GridImageWidget\", \"name\": \"background\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"filename\": \"PANEL\\expandedstash\",\n";
                ss << u8"            },\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"TextBoxWidget\", \"name\": \"gold_max\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 78, \"y\": 35 },\n";
                ss << u8"            },\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"TextBoxWidget\", \"name\": \"gold_amount\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 40, \"y\": 358 },\n";
                ss << u8"            },\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"ButtonWidget\", \"name\": \"gold_withdraw\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 15, \"y\": 357 },\n";
                ss << u8"            },\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"ButtonWidget\", \"name\": \"close\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 272, \"y\": 384 },\n";
                ss << u8"            },\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"InventoryGridWidget\", \"name\": \"grid\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 15, \"y\": 63 },\n";
                ss << u8"                \"cellCount\": { \"x\": 10, \"y\": 10 },\n";
                ss << u8"                \"cellSize\": \"$ItemCellSize\",\n";
                ss << u8"            },\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"TabBarWidget\", \"name\": \"BankTabs\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"tabCount\": 4,\n";
                ss << u8"                \"filename\": \"PANEL\\buyselltabs\",\n";
                ss << u8"                \"inactiveFrames\": [ 4, 5, 6, 7],\n";
                ss << u8"                \"activeFrames\": [ 0, 1, 2, 3],\n";
                ss << u8"                \"disabledFrames\": [-1, 5, ],\n";
                ss << u8"                \"textStrings\": [ \"@personal\", \"@shared\", \"@shared\", \"@shared\"],\n";
                ss << u8"                \"tabSize\": { \"x\": 79, \"y\": 24 },\n";
                ss << u8"                \"tabPadding\": { \"x\": 1, \"y\": 0 },\n";
                ss << u8"                \"onSwitchTabMessage\": \"BankPanelMessage:SelectTab\",\n";
                ss << u8"            }\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"Widget\", \"name\": \"PreviousSeasonToggleDisplay\",\n";
                ss << u8"            \"children\": [\n";
                ss << u8"                {\n";
                ss << u8"                    \"type\": \"TextBoxWidget\", \"name\": \"ShowPreviousLadderText\",\n";
                ss << u8"                    \"fields\": {\n";
                ss << u8"                        \"text\": \"@oldStash\",\n";
                ss << u8"                        \"rect\": { \"x\": 45, \"y\": 404 },\n";
                ss << u8"                        \"style\": {\n";
                ss << u8"                            \"fontColor\": \"$PanelTitleColor\",\n";
                ss << u8"                            \"pointSize\": \"$MediumFontSize\",\n";
                ss << u8"                            \"alignment\": { \"v\": \"center\", \"h\": \"left\" },\n";
                ss << u8"                            \"spacing\" : \"$MinimumSpacing\",\n";
                ss << u8"                            \"dropShadow\": \"$DefaultDropShadow\"\n";
                ss << u8"                        }\n";
                ss << u8"                    }\n";
                ss << u8"                },\n";
                ss << u8"                {\n";
                ss << u8"                    \"type\": \"ToggleButtonWidget\", \"name\": \"ShowPreviousLadderSeasonToggle\",\n";
                ss << u8"                    \"fields\": {\n";
                ss << u8"                        \"rect\": { \"x\": 10, \"y\": 388 },\n";
                ss << u8"                        \"filename\": \"PANEL\\buysellbtn\",\n";
                ss << u8"                        \"untoggledFrame\": 0,\n";
                ss << u8"                        \"untoggledPressedFrame\": 1,\n";
                ss << u8"                        \"toggledFrame\": 16,\n";
                ss << u8"                        \"toggledPressedFrame\": 17,\n";
                ss << u8"                        \"onClickMessage\": \"BankPanelMessage:TogglePreviousSeasonTabs\",\n";
                ss << u8"                        \"tooltipString\": \"@SharedStashPreviousSeasonToggleTooltip\",\n";
                ss << u8"                    }\n";
                ss << u8"                }\n";
                ss << u8"            ]\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"TabBarWidget\", \"name\": \"PreviousLadderSeasonBankTabs\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"tabCount\": 3,\n";
                ss << u8"                \"filename\": \"PANEL\\buyselltabs\",\n";
                ss << u8"                \"inactiveFrames\": [ 12, 13, 14 ],\n";
                ss << u8"                \"activeFrames\": [ 8, 9, 10 ],\n";
                ss << u8"                \"textStrings\": [ \"@shared\", \"@shared\", \"@shared\"],\n";
                ss << u8"                \"tabSize\": { \"x\": 79, \"y\": 24 },\n";
                ss << u8"                \"tabPadding\": { \"x\": 1, \"y\": 0 },\n";
                ss << u8"                \"onSwitchTabMessage\": \"BankPanelMessage:SelectTab\",\n";
                ss << u8"            }\n";
                ss << u8"        },\n";
                ss << u8"    ]\n";
                ss << u8"}\n";
                defaultTxt = ss.str();
            }
            return defaultTxt;
        }

        const std::string& GetHirelingInventoryPanel()
        {
            static std::string defaultTxt;
            if (defaultTxt.empty())
            {
                std::stringstream ss;
                ss << u8"{\n";
                ss << u8"    \"type\": \"HirelingInventoryPanel\", \"name\": \"HirelingInventoryPanel\",\n";
                ss << u8"    \"fields\": {\n";
                ss << u8"        \"rect\": \"$LeftPanelRect\",\n";
                ss << u8"        \"anchor\": \"$LeftPanelAnchor\",\n";
                ss << u8"        \"slotBackgroundFilename\": \"PANEL\\\\Hireling\\\\HireablePanel\\\\Hireables_Paperdoll\",\n";
                ss << u8"        // limited to 20 overrides\n";
                ss << u8"        \"slotBackgroundOverrides\": [\n";
                ss << u8"            {\n";
                ss << u8"                \"monsterClass\": 271,\n";
                ss << u8"                \"rightBackgroundFrame\": 0,\n";
                ss << u8"                \"leftBackgroundFrame\": 0,\n";
                ss << u8"            },\n";
                ss << u8"            {\n";
                ss << u8"                \"monsterClass\": 338,\n";
                ss << u8"                \"rightBackgroundFrame\": 1,\n";
                ss << u8"                \"leftBackgroundFrame\": 1,\n";
                ss << u8"            },\n";
                ss << u8"            {\n";
                ss << u8"                \"monsterClass\": 359,\n";
                ss << u8"                \"rightBackgroundFrame\": 2,\n";
                ss << u8"                \"leftBackgroundFrame\": 3,\n";
                ss << u8"            },\n";
                ss << u8"            {\n";
                ss << u8"                \"monsterClass\": 560,\n";
                ss << u8"                \"rightBackgroundFrame\": 4,\n";
                ss << u8"                \"leftBackgroundFrame\": 4,\n";
                ss << u8"            },\n";
                ss << u8"            {\n";
                ss << u8"                \"monsterClass\": 561,\n";
                ss << u8"                \"rightBackgroundFrame\": 2,\n";
                ss << u8"                \"leftBackgroundFrame\": 2,\n";
                ss << u8"            },\n";
                ss << u8"        ]\n";
                ss << u8"    },\n";
                ss << u8"    \"children\": [\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"ImageWidget\", \"name\": \"Background\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 0, \"y\": 0 },\n";
                ss << u8"                \"filename\": \"\\\\PANEL\\\\Hireling\\\\HirelingPanel\"\n";
                ss << u8"            },\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"ClickCatcherWidget\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": \"$PanelClickCatcherRect\"\n";
                ss << u8"            }\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"ImageWidget\", \"name\": \"LeftHinge\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": \"$LeftHingeRect\",\n";
                ss << u8"                \"filename\": \"$LeftHingeSprite\"\n";
                ss << u8"            },\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"TextBoxWidget\", \"name\": \"Title\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": \"$InGamePanelTitleRect\",\n";
                ss << u8"                \"style\": \"$StyleTitleBlock\",\n";
                ss << u8"                \"text\": \"@MiniPanelHireinv\",\n";
                ss << u8"            },\n";
                ss << u8"        },\n";
                ss << u8"        // Background images for inventory slots\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"InventorySlotWidget\", \"name\": \"slot_head\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 481, \"y\": 193, \"width\": 196, \"height\": 196 },\n";
                ss << u8"                \"cellSize\": \"$ItemCellSize\",\n";
                ss << u8"                \"location\": \"head\",\n";
                ss << u8"                \"gemSocketFilename\": \"PANEL\\\\gemsocket\",\n";
                ss << u8"                \"backgroundFilename\": \"PANEL\\\\Inventory\\\\Inventory_Paperdoll_HeadArmor\",\n";
                ss << u8"                \"isHireable\": true,\n";
                ss << u8"            }\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"InventorySlotWidget\", \"name\": \"slot_torso\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 481, \"y\": 433, \"width\": 196, \"height\": 294 },\n";
                ss << u8"                \"cellSize\": \"$ItemCellSize\",\n";
                ss << u8"                \"location\": \"torso\",\n";
                ss << u8"                \"gemSocketFilename\": \"PANEL\\\\gemsocket\",\n";
                ss << u8"                \"backgroundFilename\": \"PANEL\\\\Inventory\\\\Inventory_Paperdoll_ChestArmor\",\n";
                ss << u8"                \"isHireable\": true,\n";
                ss << u8"            }\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"InventorySlotWidget\", \"name\": \"slot_right_arm\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 108, \"y\": 336, \"width\": 196, \"height\": 392 },\n";
                ss << u8"                \"cellSize\": \"$ItemCellSize\",\n";
                ss << u8"                \"location\": \"right_arm\",\n";
                ss << u8"                \"gemSocketFilename\": \"PANEL\\\\gemsocket\",\n";
                ss << u8"                \"backgroundFilename\": \"PANEL\\\\Inventory\\\\Inventory_Paperdoll_Weapon\",\n";
                ss << u8"                \"isHireable\": true,\n";
                ss << u8"            }\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"InventorySlotWidget\", \"name\": \"slot_left_arm\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 861, \"y\": 336, \"width\": 196, \"height\": 392 },\n";
                ss << u8"                \"cellSize\": \"$ItemCellSize\",\n";
                ss << u8"                \"location\": \"left_arm\",\n";
                ss << u8"                \"gemSocketFilename\": \"PANEL\\\\gemsocket\",\n";
                ss << u8"                \"backgroundFilename\": \"PANEL\\\\Inventory\\\\Inventory_Paperdoll_Weapon\",\n";
                ss << u8"                \"isHireable\": true,\n";
                ss << u8"            }\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"TextBoxWidget\", \"name\": \"CharacterName\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 123, \"y\": 782, \"width\": 500, \"height\": 50 },\n";
                ss << u8"                \"style\": {\n";
                ss << u8"                    \"fontColor\":\"$FontColorWhite\",\n";
                ss << u8"                    \"pointSize\": \"$LargeFontSize\",\n";
                ss << u8"                    \"dropShadow\": \"$DefaultDropShadow\",\n";
                ss << u8"                    \"alignment\": { \"h\": \"left\", \"v\": \"center\" }\n";
                ss << u8"                },\n";
                ss << u8"            }\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"TextBoxWidget\", \"name\": \"HPTitle\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 93, \"y\": 955, \"width\": 230, \"height\": 59 },\n";
                ss << u8"                \"text\": \"@strchrlif\",\n";
                ss << u8"                \"style\": {\n";
                ss << u8"                    \"fontColor\":\"$FontColorWhite\",\n";
                ss << u8"                    \"fontFace\": \"Formal\",\n";
                ss << u8"                    \"pointSize\": \"$SmallPanelFontSize\",\n";
                ss << u8"                    \"alignment\": { \"h\": \"center\", \"v\": \"center\" }\n";
                ss << u8"                },\n";
                ss << u8"            }\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"TextBoxWidget\", \"name\": \"HPStat\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 328, \"y\": 955, \"width\": 237, \"height\": 59 },\n";
                ss << u8"                \"style\": {\n";
                ss << u8"                    \"fontColor\": { \"r\": 255, \"g\": 255, \"b\": 255, \"a\": 255 },\n";
                ss << u8"                    \"pointSize\": \"$SmallPanelFontSize\",\n";
                ss << u8"                    \"alignment\": { \"h\": \"center\", \"v\": \"center\" }\n";
                ss << u8"                },\n";
                ss << u8"            }\n";
                ss << u8"        },\n";
                ss << u8"        // Level\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"TextBoxWidget\", \"name\": \"HireTypeText\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 128, \"y\": 870, \"width\": 320, \"height\": 54 },\n";
                ss << u8"                \"text\": \"@strchrlvl\",\n";
                ss << u8"                \"style\": {\n";
                ss << u8"                    \"fontColor\": \"$FontColorWhite\",\n";
                ss << u8"                    \"pointSize\": \"$XMediumPanelFontSize\",\n";
                ss << u8"                    \"dropShadow\": \"$DefaultDropShadow\",\n";
                ss << u8"                    \"alignment\": { \"h\": \"left\", \"v\": \"center\" }\n";
                ss << u8"                },\n";
                ss << u8"            }\n";
                ss << u8"        },\n";
                ss << u8"        // Experience\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"ExpBarWidget\", \"name\": \"XpProgress\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 139, \"y\": 845, \"width\": 888, \"height\": 10 } ,\n";
                ss << u8"                \"filename\": \"PANEL\\\\Hireling\\\\Hireling_ExpBar\",\n";
                ss << u8"                \"frame\": 0,\n";
                ss << u8"                \"isHireling\": true,\n";
                ss << u8"                \"hitMargin\": { \"top\": 15, \"bottom\": 15 }\n";
                ss << u8"            }\n";
                ss << u8"        },\n";
                ss << u8"       /* {\n";
                ss << u8"            \"type\": \"TextBoxWidget\", \"name\": \"NextLevelXP\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 789, \"y\": 912, \"width\": 250, \"height\": 50 },\n";
                ss << u8"                \"style\": {\n";
                ss << u8"                    \"fontColor\": { \"r\": 255, \"g\": 255, \"b\": 255, \"a\": 255 },\n";
                ss << u8"                    \"pointSize\": \"$MediumPanelFontSize\",\n";
                ss << u8"                    \"alignment\": { \"h\": \"left\", \"v\": \"center\" }\n";
                ss << u8"                },\n";
                ss << u8"            }\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"TextBoxWidget\", \"name\": \"ConnectorWord\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 748, \"y\": 912, \"height\": 50 },\n";
                ss << u8"                \"text\": \"@ItemStats1j\",\n";
                ss << u8"                \"style\": {\n";
                ss << u8"                    \"fontColor\": { \"r\": 255, \"g\": 255, \"b\": 255, \"a\": 255 },\n";
                ss << u8"                    \"pointSize\": \"$MediumPanelFontSize\",\n";
                ss << u8"                    \"alignment\": { \"h\": \"center\", \"v\": \"center\" }\n";
                ss << u8"                },\n";
                ss << u8"            }\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"TextBoxWidget\", \"name\": \"CurrentXP\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 467, \"y\": 912, \"width\": 250, \"height\": 50 },\n";
                ss << u8"                \"style\": {\n";
                ss << u8"                    \"fontColor\": { \"r\": 255, \"g\": 255, \"b\": 255, \"a\": 255 },\n";
                ss << u8"                    \"pointSize\": \"$MediumPanelFontSize\",\n";
                ss << u8"                    \"alignment\": { \"h\": \"right\", \"v\": \"center\" }\n";
                ss << u8"                },\n";
                ss << u8"            }\n";
                ss << u8"        },*/\n";
                ss << u8"        // Base stats\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"TextBoxWidget\", \"name\": \"StrengthTitle\",\n";
                ss << u8"            \"fields\":\n";
                ss << u8"            {\n";
                ss << u8"                \"rect\": { \"x\": 93, \"y\": 1037, \"width\": 230, \"height\": 59 },\n";
                ss << u8"                \"text\": \"@strchrstr\",\n";
                ss << u8"                \"style\": {\n";
                ss << u8"                    \"fontColor\":\"$FontColorWhite\",\n";
                ss << u8"                    \"fontFace\": \"Formal\",\n";
                ss << u8"                    \"pointSize\": \"$SmallPanelFontSize\",\n";
                ss << u8"                    \"alignment\": { \"h\": \"center\", \"v\": \"center\" }\n";
                ss << u8"                },\n";
                ss << u8"            }\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"TextBoxWidget\", \"name\": \"StrengthStat\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 328, \"y\": 1037, \"width\": 237, \"height\": 59 },\n";
                ss << u8"                \"style\": {\n";
                ss << u8"                    \"fontColor\": { \"r\": 255, \"g\": 255, \"b\": 255, \"a\": 255 },\n";
                ss << u8"                    \"pointSize\": \"$SmallPanelFontSize\",\n";
                ss << u8"                    \"alignment\": { \"h\": \"center\", \"v\": \"center\" }\n";
                ss << u8"                },\n";
                ss << u8"            }\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"TextBoxWidget\", \"name\": \"DexTitle\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 93, \"y\": 1121, \"width\": 230, \"height\": 59 },\n";
                ss << u8"                \"text\": \"@strchrdex\",\n";
                ss << u8"                \"style\": {\n";
                ss << u8"                    \"fontColor\":\"$FontColorWhite\",\n";
                ss << u8"                    \"fontFace\": \"Formal\",\n";
                ss << u8"                    \"pointSize\": \"$SmallPanelFontSize\",\n";
                ss << u8"                    \"alignment\": { \"h\": \"center\", \"v\": \"center\" }\n";
                ss << u8"                },\n";
                ss << u8"            }\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"TextBoxWidget\", \"name\": \"DexStat\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 328, \"y\": 1121, \"width\": 237, \"height\": 59 },\n";
                ss << u8"                \"style\": {\n";
                ss << u8"                    \"fontColor\": { \"r\": 255, \"g\": 255, \"b\": 255, \"a\": 255 },\n";
                ss << u8"                    \"pointSize\": \"$SmallPanelFontSize\",\n";
                ss << u8"                    \"alignment\": { \"h\": \"center\", \"v\": \"center\" }\n";
                ss << u8"                },\n";
                ss << u8"            }\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"TextBoxWidget\", \"name\": \"DamageTitle\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 93, \"y\": 1204, \"width\": 230, \"height\": 59 },\n";
                ss << u8"                \"text\": \"@strchrskm\",\n";
                ss << u8"                \"style\": {\n";
                ss << u8"                    \"fontColor\":\"$FontColorWhite\",\n";
                ss << u8"                    \"fontFace\": \"Formal\",\n";
                ss << u8"                    \"pointSize\": \"$SmallPanelFontSize\",\n";
                ss << u8"                    \"alignment\": { \"h\": \"center\", \"v\": \"center\" }\n";
                ss << u8"                },\n";
                ss << u8"            }\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"Widget\", \"name\": \"Damage\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 328, \"y\": 1204, \"width\": 237, \"height\": 59 },\n";
                ss << u8"            },\n";
                ss << u8"            \"children\": [\n";
                ss << u8"                {\n";
                ss << u8"                    \"type\": \"TextBoxWidget\", \"name\": \"DamageStat\",\n";
                ss << u8"                    \"fields\": {\n";
                ss << u8"                        \"rect\": { \"x\": 0, \"y\": 0, \"width\": 237, \"height\": 59 },\n";
                ss << u8"                        \"style\": {\n";
                ss << u8"                            \"fontColor\": { \"r\": 255, \"g\": 255, \"b\": 255, \"a\": 255 },\n";
                ss << u8"                            \"pointSize\": \"$SmallPanelFontSize\",\n";
                ss << u8"                            \"alignment\": { \"h\": \"center\", \"v\": \"center\" }\n";
                ss << u8"                        }\n";
                ss << u8"                    }\n";
                ss << u8"                },\n";
                ss << u8"                {\n";
                ss << u8"                    \"type\": \"TextBoxWidget\", \"name\": \"DamageStatTop\",\n";
                ss << u8"                    \"fields\": {\n";
                ss << u8"                        \"rect\": { \"x\": 0, \"y\": 0, \"width\": 237, \"height\": 59 },\n";
                ss << u8"                        \"style\": {\n";
                ss << u8"                            \"fontColor\": { \"r\": 255, \"g\": 255, \"b\": 255, \"a\": 255 },\n";
                ss << u8"                            \"pointSize\": \"$SmallPanelFontSize\",\n";
                ss << u8"                            \"alignment\": { \"h\": \"center\", \"v\": \"top\" }\n";
                ss << u8"                        }\n";
                ss << u8"                    }\n";
                ss << u8"                },\n";
                ss << u8"                {\n";
                ss << u8"                    \"type\": \"TextBoxWidget\", \"name\": \"DamageStatBottom\",\n";
                ss << u8"                    \"fields\": {\n";
                ss << u8"                        \"rect\": { \"x\": 0, \"y\": -1, \"width\": 237, \"height\": 59 },\n";
                ss << u8"                        \"style\": {\n";
                ss << u8"                            \"fontColor\": { \"r\": 255, \"g\": 255, \"b\": 255, \"a\": 255 },\n";
                ss << u8"                            \"pointSize\": \"$SmallPanelFontSize\",\n";
                ss << u8"                            \"alignment\": { \"h\": \"center\", \"v\": \"bottom\" }\n";
                ss << u8"                        }\n";
                ss << u8"                    }\n";
                ss << u8"                },\n";
                ss << u8"            ]\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"TextBoxWidget\", \"name\": \"ArmorClassTitle\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 93, \"y\": 1288, \"width\": 230, \"height\": 59 },\n";
                ss << u8"                \"text\": \"@strchrdef\",\n";
                ss << u8"                \"style\": {\n";
                ss << u8"                    \"fontColor\":\"$FontColorWhite\",\n";
                ss << u8"                    \"fontFace\": \"Formal\",\n";
                ss << u8"                    \"pointSize\": \"$SmallPanelFontSize\",\n";
                ss << u8"                    \"alignment\": { \"h\": \"center\", \"v\": \"center\" }\n";
                ss << u8"                },\n";
                ss << u8"            }\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"TextBoxWidget\", \"name\": \"ArmorClass\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 328, \"y\": 1288, \"width\": 237, \"height\": 59 },\n";
                ss << u8"                \"style\": {\n";
                ss << u8"                    \"fontColor\": { \"r\": 255, \"g\": 255, \"b\": 255, \"a\": 255 },\n";
                ss << u8"                    \"pointSize\": \"$SmallPanelFontSize\",\n";
                ss << u8"                    \"alignment\": { \"h\": \"center\", \"v\": \"center\" }\n";
                ss << u8"                },\n";
                ss << u8"            }\n";
                ss << u8"        },\n";
                ss << u8"        // Elemental Resistances\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"TextBoxWidget\", \"name\": \"FireResistanceTitle\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 596, \"y\": 1038, \"width\": 364, \"height\": 59 },\n";
                ss << u8"                \"text\": \"@strchrfir\",\n";
                ss << u8"                \"style\": {\n";
                ss << u8"                    \"fontColor\":\"$FontColorWhite\",\n";
                ss << u8"                    \"fontFace\": \"Formal\",\n";
                ss << u8"                    \"pointSize\": \"$SmallPanelFontSize\",\n";
                ss << u8"                    \"alignment\": { \"h\": \"center\", \"v\": \"center\" },\n";
                ss << u8"                },\n";
                ss << u8"            }\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"TextBoxWidget\", \"name\": \"FireText\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 953, \"y\": 1038, \"width\": 115, \"height\": 59 },\n";
                ss << u8"                \"style\": {\n";
                ss << u8"                    \"fontColor\": { \"r\": 255, \"g\": 255, \"b\": 255, \"a\": 255 },\n";
                ss << u8"                    \"pointSize\": \"$SmallPanelFontSize\",\n";
                ss << u8"                    \"alignment\": { \"h\": \"center\", \"v\": \"center\" },\n";
                ss << u8"                },\n";
                ss << u8"            }\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"TextBoxWidget\", \"name\": \"ColdResistanceTitle\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 596, \"y\": 1119, \"width\": 364, \"height\": 59 },\n";
                ss << u8"                \"text\": \"@strchrcol\",\n";
                ss << u8"                \"style\": {\n";
                ss << u8"                    \"fontColor\":\"$FontColorWhite\",\n";
                ss << u8"                    \"fontFace\": \"Formal\",\n";
                ss << u8"                    \"pointSize\": \"$SmallPanelFontSize\",\n";
                ss << u8"                    \"alignment\": { \"h\": \"center\", \"v\": \"center\" },\n";
                ss << u8"                },\n";
                ss << u8"            }\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"TextBoxWidget\", \"name\": \"ColdText\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 953, \"y\": 1119, \"width\": 115, \"height\": 59 },\n";
                ss << u8"                \"style\": {\n";
                ss << u8"                    \"fontColor\": { \"r\": 255, \"g\": 255, \"b\": 255, \"a\": 255 },\n";
                ss << u8"                    \"pointSize\": \"$SmallPanelFontSize\",\n";
                ss << u8"                    \"alignment\": { \"h\": \"center\", \"v\": \"center\" },\n";
                ss << u8"                },\n";
                ss << u8"            }\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"TextBoxWidget\", \"name\": \"LightningResistanceTitle\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 596, \"y\": 1204, \"width\": 364, \"height\": 59 },\n";
                ss << u8"                \"text\": \"@strchrlit\",\n";
                ss << u8"                \"style\": {\n";
                ss << u8"                    \"fontColor\":\"$FontColorWhite\",\n";
                ss << u8"                    \"fontFace\": \"Formal\",\n";
                ss << u8"                    \"pointSize\": \"$SmallPanelFontSize\",\n";
                ss << u8"                    \"alignment\": { \"h\": \"center\", \"v\": \"center\" },\n";
                ss << u8"                },\n";
                ss << u8"            }\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"TextBoxWidget\", \"name\": \"LightningText\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 953, \"y\": 1204, \"width\": 115, \"height\": 59 },\n";
                ss << u8"                \"style\": {\n";
                ss << u8"                    \"fontColor\": { \"r\": 255, \"g\": 255, \"b\": 255, \"a\": 255 },\n";
                ss << u8"                    \"pointSize\": \"$SmallPanelFontSize\",\n";
                ss << u8"                    \"alignment\": { \"h\": \"center\", \"v\": \"center\" },\n";
                ss << u8"                },\n";
                ss << u8"            }\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"TextBoxWidget\", \"name\": \"PoisonResistanceTitle\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 596, \"y\": 1286, \"width\": 364, \"height\": 59 },\n";
                ss << u8"                \"text\": \"@strchrpos\",\n";
                ss << u8"                \"style\": {\n";
                ss << u8"                    \"fontColor\":\"$FontColorWhite\",\n";
                ss << u8"                    \"fontFace\": \"Formal\",\n";
                ss << u8"                    \"pointSize\": \"$SmallPanelFontSize\",\n";
                ss << u8"                    \"alignment\": { \"h\": \"center\", \"v\": \"center\" },\n";
                ss << u8"                },\n";
                ss << u8"            }\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"TextBoxWidget\", \"name\": \"PoisonText\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 953, \"y\": 1286, \"width\": 115, \"height\": 59 },\n";
                ss << u8"                \"style\": {\n";
                ss << u8"                    \"fontColor\": { \"r\": 255, \"g\": 255, \"b\": 255, \"a\": 255 },\n";
                ss << u8"                    \"pointSize\": \"$SmallPanelFontSize\",\n";
                ss << u8"                    \"alignment\": { \"h\": \"center\", \"v\": \"center\" },\n";
                ss << u8"                },\n";
                ss << u8"            },\n";
                ss << u8"        },\n";
                ss << u8"        // To Advanced Stats panel\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"ButtonWidget\", \"name\": \"AdvancedStats\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 1108, \"y\": 711 },\n";
                ss << u8"                \"filename\": \"PANEL\\\\Character_Sheet\\\\AdvancedStatsButton\",\n";
                ss << u8"                \"hoveredFrame\": 3,\n";
                ss << u8"                \"onClickMessage\": \"HirelingInventoryPanelMessage:ToggleAdvancedStats\",\n";
                ss << u8"                \"pressLabelOffset\": { \"x\": 0, \"y\": 2 },\n";
                ss << u8"                \"tooltipString\": \"@AdvancedStats\"\n";
                ss << u8"            },\n";
                ss << u8"        },\n";
                ss << u8"        // Close Panel\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"ButtonWidget\", \"name\": \"CloseButton\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 1075, \"y\": 9 },\n";
                ss << u8"                \"filename\": \"PANEL\\\\closebtn_4x\",\n";
                ss << u8"                \"hoveredFrame\": 3,\n";
                ss << u8"                \"onClickMessage\": \"HirelingInventoryPanelMessage:Close\",\n";
                ss << u8"                \"tooltipString\": \"@strClose\",\n";
                ss << u8"                \"sound\": \"cursor_close_window_hd\",\n";
                ss << u8"            },\n";
                ss << u8"        },\n";
                ss << u8"        // Hire skills\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"HirelingSkillIconWidget\", \"name\": \"Skill0\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 675, \"y\": 942, \"scale\": 0.60 },\n";
                ss << u8"                \"skillIconFilename\": \"Spells/Hireables/HrSkillIcon\"\n";
                ss << u8"            }\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"HirelingSkillIconWidget\", \"name\": \"Skill1\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 782, \"y\": 942, \"scale\": 0.60 },\n";
                ss << u8"                \"skillIconFilename\": \"Spells/Hireables/HrSkillIcon\"\n";
                ss << u8"            }\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"HirelingSkillIconWidget\", \"name\": \"Skill2\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 889, \"y\": 942, \"scale\": 0.60 },\n";
                ss << u8"                \"skillIconFilename\": \"Spells/Hireables/HrSkillIcon\"\n";
                ss << u8"            }\n";
                ss << u8"        },\n";
                ss << u8"    ]\n";
                ss << u8"}\n";
                defaultTxt = ss.str();
            }
            return defaultTxt;
        }

        const std::string& GetHoradricCubeLayout()
        {
            static std::string defaultTxt;
            if (defaultTxt.empty())
            {
                std::stringstream ss;
                ss << u8"{\n";
                ss << u8"    \"type\": \"HoradricCubePanel\", \"name\": \"HoradricCubeLayout\",\n";
                ss << u8"    \"fields\": {\n";
                ss << u8"        \"priority\": 10,\n";
                ss << u8"        \"rect\": { \"x\": -320, \"y\": -240, \"width\": 320, \"height\": 432 },\n";
                ss << u8"        \"anchor\": \"$LeftPanelAnchor\",\n";
                ss << u8"    },\n";
                ss << u8"    \"children\": [\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"ClickCatcherWidget\", \"name\": \"click_catcher\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"width\": 320, \"height\": 432 }\n";
                ss << u8"            },\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"GridImageWidget\", \"name\": \"background\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"filename\": \"PANEL\\supertransmogrifier\",\n";
                ss << u8"                \"frames\": 4,\n";
                ss << u8"                \"rows\": 2,\n";
                ss << u8"            },\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"ButtonWidget\", \"name\": \"convert\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 144, \"y\": 260 },\n";
                ss << u8"                \"filename\": \"PANEL\\miniconvert\",\n";
                ss << u8"                \"tooltipString\": \"@strUiMenu2\",\n";
                ss << u8"                \"tooltipOffset\": { \"x\": 0, \"y\": -3 },\n";
                ss << u8"                \"onClickMessage\": \"HoradricCubePanelMessage:Convert\",\n";
                ss << u8"            },\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"ButtonWidget\", \"name\": \"close\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 275, \"y\": 383 },\n";
                ss << u8"                \"filename\": \"PANEL\\buysellbtn\",\n";
                ss << u8"                \"normalFrame\": 10,\n";
                ss << u8"                \"pressedFrame\": 11,\n";
                ss << u8"                \"tooltipString\": \"@strClose\",\n";
                ss << u8"                \"tooltipOffset\": { \"x\": 0, \"y\": -3 },\n";
                ss << u8"                \"onClickMessage\": \"HoradricCubePanelMessage:Close\",\n";
                ss << u8"            },\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"InventoryGridWidget\", \"name\": \"grid\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 118, \"y\": 139 },\n";
                ss << u8"                \"cellCount\": { \"x\": 3, \"y\": 4 },\n";
                ss << u8"                \"cellSize\": \"$ItemCellSize\",\n";
                ss << u8"                \"gemSocketFilename\": \"PANEL\\gemsocket\",\n";
                ss << u8"            },\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"AnimatedImageWidget\", \"name\": \"flourish\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 320, \"y\": 237 },\n";
                ss << u8"                \"filename\": \"MENU\\horadric\",\n";
                ss << u8"                \"blendMode\": \"black\",\n";
                ss << u8"                \"fps\": 14,\n";
                ss << u8"                \"playing\": false,\n";
                ss << u8"                \"loop\": false,\n";
                ss << u8"            },\n";
                ss << u8"        },\n";
                ss << u8"    ]\n";
                ss << u8"}\n";
                defaultTxt = ss.str();
            }
            return defaultTxt;
        }

        const std::string& GetPlayerInventoryExpansionLayout()
        {
            static std::string defaultTxt;
            if (defaultTxt.empty())
            {
                std::stringstream ss;
                ss << u8"{\n";
                ss << u8"    \"basedOn\": \"PlayerInventoryOriginalLayout.json\",\n";
                ss << u8"    \"type\": \"PlayerInventoryPanel\", \"name\": \"PlayerInventoryExpansionLayout\",\n";
                ss << u8"    \"children\": [\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"ClickCatcherWidget\", \"name\": \"click_catcher\",\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"GridImageWidget\", \"name\": \"background\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"filename\": \"PANEL\\invchar6\",\n";
                ss << u8"            },\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"ImageWidget\", \"name\": \"background_right_arm\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 15, \"y\": 22 },\n";
                ss << u8"                \"filename\": \"PANEL\\invchar6Tab\",\n";
                ss << u8"                \"frame\": 1,\n";
                ss << u8"            },\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"ImageWidget\", \"name\": \"background_left_arm\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 246, \"y\": 22 },\n";
                ss << u8"                \"filename\": \"PANEL\\invchar6Tab\",\n";
                ss << u8"                \"frame\": 0,\n";
                ss << u8"            },\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"FocusableWidget\", \"name\": \"weaponswap_right_arm\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 20, \"y\": 23, \"width\": 56, \"height\": 24 },\n";
                ss << u8"            },\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"FocusableWidget\", \"name\": \"weaponswap_left_arm\",\n";
                ss << u8"            \"fields\": {\n";
                ss << u8"                \"rect\": { \"x\": 251, \"y\": 23, \"width\": 56, \"height\": 24 },\n";
                ss << u8"            },\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"TextBoxWidget\", \"name\": \"gold_amount\",\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"ButtonWidget\", \"name\": \"gold_button\",\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"ButtonWidget\", \"name\": \"close\",\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"InventoryGridWidget\", \"name\": \"grid\",\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"InventorySlotWidget\", \"name\": \"slot_head\",\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"InventorySlotWidget\", \"name\": \"slot_neck\",\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"InventorySlotWidget\", \"name\": \"slot_torso\",\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"InventorySlotWidget\", \"name\": \"slot_right_arm\",\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"InventorySlotWidget\", \"name\": \"slot_left_arm\",\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"InventorySlotWidget\", \"name\": \"slot_right_hand\",\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"InventorySlotWidget\", \"name\": \"slot_left_hand\",\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"InventorySlotWidget\", \"name\": \"slot_belt\",\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"InventorySlotWidget\", \"name\": \"slot_feet\",\n";
                ss << u8"        },\n";
                ss << u8"        {\n";
                ss << u8"            \"type\": \"InventorySlotWidget\", \"name\": \"slot_gloves\",\n";
                ss << u8"        },\n";
                ss << u8"    ]\n";
                ss << u8"}\n";
                defaultTxt = ss.str();
            }
            return defaultTxt;
        }
    }
}