/*
    Diablo II Character Editor
    Copyright (C) 2021-2023 Walter Couto

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/
//---------------------------------------------------------------------------

#include "pch.h"
#include <sstream>

namespace d2ce
{
    namespace JsonReaderHelper
    {
        const std::string& GetNPCs()
        {
            static std::string defaultTxt;
            if (defaultTxt.empty())
            {
                std::stringstream ss;
                ss << u8"[\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 1008,\n";
                ss << u8"    \"Key\": \"asheara\",\n";
                ss << u8"    \"enUS\": \"Asheara\",\n";
                ss << u8"    \"zhTW\": \"艾席拉\",\n";
                ss << u8"    \"deDE\": \"Aschara\",\n";
                ss << u8"    \"esES\": \"Asheara\",\n";
                ss << u8"    \"frFR\": \"Asheara\",\n";
                ss << u8"    \"itIT\": \"Asheara\",\n";
                ss << u8"    \"koKR\": \"아시아라\",\n";
                ss << u8"    \"plPL\": \"Asheara\",\n";
                ss << u8"    \"esMX\": \"Asheara\",\n";
                ss << u8"    \"jaJP\": \"アシェアラ\",\n";
                ss << u8"    \"ptBR\": \"Ashara\",\n";
                ss << u8"    \"ruRU\": \"Ашира\",\n";
                ss << u8"    \"zhCN\": \"艾席拉\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 1009,\n";
                ss << u8"    \"Key\": \"hratli\",\n";
                ss << u8"    \"enUS\": \"Hratli\",\n";
                ss << u8"    \"zhTW\": \"赫拉鐵力\",\n";
                ss << u8"    \"deDE\": \"Hratli\",\n";
                ss << u8"    \"esES\": \"Hratli\",\n";
                ss << u8"    \"frFR\": \"Hratli\",\n";
                ss << u8"    \"itIT\": \"Hratli\",\n";
                ss << u8"    \"koKR\": \"흐라틀리\",\n";
                ss << u8"    \"plPL\": \"Hratli\",\n";
                ss << u8"    \"esMX\": \"Hratli\",\n";
                ss << u8"    \"jaJP\": \"フラトリ\",\n";
                ss << u8"    \"ptBR\": \"Ratli\",\n";
                ss << u8"    \"ruRU\": \"Хратли\",\n";
                ss << u8"    \"zhCN\": \"赫拉铁力\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 1010,\n";
                ss << u8"    \"Key\": \"alkor\",\n";
                ss << u8"    \"enUS\": \"Alkor\",\n";
                ss << u8"    \"zhTW\": \"艾柯\",\n";
                ss << u8"    \"deDE\": \"Alkor\",\n";
                ss << u8"    \"esES\": \"Alkor\",\n";
                ss << u8"    \"frFR\": \"Alkor\",\n";
                ss << u8"    \"itIT\": \"Alkor\",\n";
                ss << u8"    \"koKR\": \"알코어\",\n";
                ss << u8"    \"plPL\": \"Alkor\",\n";
                ss << u8"    \"esMX\": \"Alkor\",\n";
                ss << u8"    \"jaJP\": \"アルコル\",\n";
                ss << u8"    \"ptBR\": \"Alkor\",\n";
                ss << u8"    \"ruRU\": \"Алькор\",\n";
                ss << u8"    \"zhCN\": \"奥科\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 1011,\n";
                ss << u8"    \"Key\": \"ormus\",\n";
                ss << u8"    \"enUS\": \"Ormus\",\n";
                ss << u8"    \"zhTW\": \"奧瑪斯\",\n";
                ss << u8"    \"deDE\": \"Ormus\",\n";
                ss << u8"    \"esES\": \"Ormus\",\n";
                ss << u8"    \"frFR\": \"Ormus\",\n";
                ss << u8"    \"itIT\": \"Ormus\",\n";
                ss << u8"    \"koKR\": \"오르무스\",\n";
                ss << u8"    \"plPL\": \"Ormus\",\n";
                ss << u8"    \"esMX\": \"Ormus\",\n";
                ss << u8"    \"jaJP\": \"オーマス\",\n";
                ss << u8"    \"ptBR\": \"Órmus\",\n";
                ss << u8"    \"ruRU\": \"Ормус\",\n";
                ss << u8"    \"zhCN\": \"奥玛斯\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 1012,\n";
                ss << u8"    \"Key\": \"nikita\",\n";
                ss << u8"    \"enUS\": \"Natalya\",\n";
                ss << u8"    \"zhTW\": \"娜塔亞\",\n";
                ss << u8"    \"deDE\": \"Natalya\",\n";
                ss << u8"    \"esES\": \"Natalya\",\n";
                ss << u8"    \"frFR\": \"Natalya\",\n";
                ss << u8"    \"itIT\": \"Natalya\",\n";
                ss << u8"    \"koKR\": \"나탈랴\",\n";
                ss << u8"    \"plPL\": \"Natalia\",\n";
                ss << u8"    \"esMX\": \"Natalya\",\n";
                ss << u8"    \"jaJP\": \"ナターリャ\",\n";
                ss << u8"    \"ptBR\": \"Natalya\",\n";
                ss << u8"    \"ruRU\": \"Наталия\",\n";
                ss << u8"    \"zhCN\": \"娜塔亚\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 1013,\n";
                ss << u8"    \"Key\": \"tyrael\",\n";
                ss << u8"    \"enUS\": \"Tyrael\",\n";
                ss << u8"    \"zhTW\": \"泰瑞爾\",\n";
                ss << u8"    \"deDE\": \"Tyrael\",\n";
                ss << u8"    \"esES\": \"Tyrael\",\n";
                ss << u8"    \"frFR\": \"Tyraël\",\n";
                ss << u8"    \"itIT\": \"Tyrael\",\n";
                ss << u8"    \"koKR\": \"티리엘\",\n";
                ss << u8"    \"plPL\": \"Tyrael\",\n";
                ss << u8"    \"esMX\": \"Tyrael\",\n";
                ss << u8"    \"jaJP\": \"ティラエル\",\n";
                ss << u8"    \"ptBR\": \"Tyrael\",\n";
                ss << u8"    \"ruRU\": \"Тираэль\",\n";
                ss << u8"    \"zhCN\": \"泰瑞尔\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 1016,\n";
                ss << u8"    \"Key\": \"Jamella\",\n";
                ss << u8"    \"enUS\": \"Jamella\",\n";
                ss << u8"    \"zhTW\": \"賈梅拉\",\n";
                ss << u8"    \"deDE\": \"Jamella\",\n";
                ss << u8"    \"esES\": \"Jamella\",\n";
                ss << u8"    \"frFR\": \"Jamella\",\n";
                ss << u8"    \"itIT\": \"Jamella\",\n";
                ss << u8"    \"koKR\": \"자멜라\",\n";
                ss << u8"    \"plPL\": \"Jamella\",\n";
                ss << u8"    \"esMX\": \"Jamella\",\n";
                ss << u8"    \"jaJP\": \"ジャメラ\",\n";
                ss << u8"    \"ptBR\": \"Jamella\",\n";
                ss << u8"    \"ruRU\": \"Джамелла\",\n";
                ss << u8"    \"zhCN\": \"贾梅拉\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 1017,\n";
                ss << u8"    \"Key\": \"halbu\",\n";
                ss << u8"    \"enUS\": \"Halbu\",\n";
                ss << u8"    \"zhTW\": \"海爾布\",\n";
                ss << u8"    \"deDE\": \"Halbu\",\n";
                ss << u8"    \"esES\": \"Halbu\",\n";
                ss << u8"    \"frFR\": \"Halbu\",\n";
                ss << u8"    \"itIT\": \"Halbu\",\n";
                ss << u8"    \"koKR\": \"할부\",\n";
                ss << u8"    \"plPL\": \"Halbu\",\n";
                ss << u8"    \"esMX\": \"Halbu\",\n";
                ss << u8"    \"jaJP\": \"ハルブ\",\n";
                ss << u8"    \"ptBR\": \"Halbu\",\n";
                ss << u8"    \"ruRU\": \"Хальбу\",\n";
                ss << u8"    \"zhCN\": \"哈尔布\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 1018,\n";
                ss << u8"    \"Key\": \"Malachai\",\n";
                ss << u8"    \"enUS\": \"Hadriel\",\n";
                ss << u8"    \"zhTW\": \"哈德爾\",\n";
                ss << u8"    \"deDE\": \"Hadriel\",\n";
                ss << u8"    \"esES\": \"Hadriel\",\n";
                ss << u8"    \"frFR\": \"Hadriel\",\n";
                ss << u8"    \"itIT\": \"Hadriel\",\n";
                ss << u8"    \"koKR\": \"하드리엘\",\n";
                ss << u8"    \"plPL\": \"Hadriel\",\n";
                ss << u8"    \"esMX\": \"Hadriel\",\n";
                ss << u8"    \"jaJP\": \"ハドリエル\",\n";
                ss << u8"    \"ptBR\": \"Hadriel\",\n";
                ss << u8"    \"ruRU\": \"Гадриэль\",\n";
                ss << u8"    \"zhCN\": \"哈德瑞尔\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 2890,\n";
                ss << u8"    \"Key\": \"DeckardCain\",\n";
                ss << u8"    \"enUS\": \"Deckard Cain\",\n";
                ss << u8"    \"zhTW\": \"迪卡‧凱恩\",\n";
                ss << u8"    \"deDE\": \"Deckard Cain\",\n";
                ss << u8"    \"esES\": \"Deckard Caín\",\n";
                ss << u8"    \"frFR\": \"Deckard Cain\",\n";
                ss << u8"    \"itIT\": \"Deckard Cain\",\n";
                ss << u8"    \"koKR\": \"데커드 케인\",\n";
                ss << u8"    \"plPL\": \"Deckard Cain\",\n";
                ss << u8"    \"esMX\": \"Deckard Cain\",\n";
                ss << u8"    \"jaJP\": \"デッカード・ケイン\",\n";
                ss << u8"    \"ptBR\": \"Deckard Cain\",\n";
                ss << u8"    \"ruRU\": \"Декард Каин\",\n";
                ss << u8"    \"zhCN\": \"迪卡德·凯恩\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 2891,\n";
                ss << u8"    \"Key\": \"Gheed\",\n";
                ss << u8"    \"enUS\": \"Gheed\",\n";
                ss << u8"    \"zhTW\": \"基德\",\n";
                ss << u8"    \"deDE\": \"Gheed\",\n";
                ss << u8"    \"esES\": \"Gheed\",\n";
                ss << u8"    \"frFR\": \"Gheed\",\n";
                ss << u8"    \"itIT\": \"Gheed\",\n";
                ss << u8"    \"koKR\": \"기드\",\n";
                ss << u8"    \"plPL\": \"Gheed\",\n";
                ss << u8"    \"esMX\": \"Gheed\",\n";
                ss << u8"    \"jaJP\": \"ギード\",\n";
                ss << u8"    \"ptBR\": \"Gheed\",\n";
                ss << u8"    \"ruRU\": \"Гид\",\n";
                ss << u8"    \"zhCN\": \"基德\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 2892,\n";
                ss << u8"    \"Key\": \"Akara\",\n";
                ss << u8"    \"enUS\": \"Akara\",\n";
                ss << u8"    \"zhTW\": \"阿卡拉\",\n";
                ss << u8"    \"deDE\": \"Akara\",\n";
                ss << u8"    \"esES\": \"Akara\",\n";
                ss << u8"    \"frFR\": \"Akara\",\n";
                ss << u8"    \"itIT\": \"Akara\",\n";
                ss << u8"    \"koKR\": \"아카라\",\n";
                ss << u8"    \"plPL\": \"Akara\",\n";
                ss << u8"    \"esMX\": \"Akara\",\n";
                ss << u8"    \"jaJP\": \"アカラ\",\n";
                ss << u8"    \"ptBR\": \"Akara\",\n";
                ss << u8"    \"ruRU\": \"Акара\",\n";
                ss << u8"    \"zhCN\": \"阿卡拉\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 2893,\n";
                ss << u8"    \"Key\": \"Kashya\",\n";
                ss << u8"    \"enUS\": \"Kashya\",\n";
                ss << u8"    \"zhTW\": \"卡夏\",\n";
                ss << u8"    \"deDE\": \"Kaschya\",\n";
                ss << u8"    \"esES\": \"Kashya\",\n";
                ss << u8"    \"frFR\": \"Kashya\",\n";
                ss << u8"    \"itIT\": \"Kashya\",\n";
                ss << u8"    \"koKR\": \"카샤\",\n";
                ss << u8"    \"plPL\": \"Kashya\",\n";
                ss << u8"    \"esMX\": \"Kashya\",\n";
                ss << u8"    \"jaJP\": \"カーシャ\",\n";
                ss << u8"    \"ptBR\": \"Kashya\",\n";
                ss << u8"    \"ruRU\": \"Кашья\",\n";
                ss << u8"    \"zhCN\": \"卡夏\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 2894,\n";
                ss << u8"    \"Key\": \"Charsi\",\n";
                ss << u8"    \"enUS\": \"Charsi\",\n";
                ss << u8"    \"zhTW\": \"恰西\",\n";
                ss << u8"    \"deDE\": \"Charsi\",\n";
                ss << u8"    \"esES\": \"Charsi\",\n";
                ss << u8"    \"frFR\": \"Charsi\",\n";
                ss << u8"    \"itIT\": \"Charsi\",\n";
                ss << u8"    \"koKR\": \"찰시\",\n";
                ss << u8"    \"plPL\": \"Charsi\",\n";
                ss << u8"    \"esMX\": \"Charsi\",\n";
                ss << u8"    \"jaJP\": \"チャルシ\",\n";
                ss << u8"    \"ptBR\": \"Charsi\",\n";
                ss << u8"    \"ruRU\": \"Чарси\",\n";
                ss << u8"    \"zhCN\": \"恰西\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 2895,\n";
                ss << u8"    \"Key\": \"Wariv\",\n";
                ss << u8"    \"enUS\": \"Warriv\",\n";
                ss << u8"    \"zhTW\": \"瓦瑞夫\",\n";
                ss << u8"    \"deDE\": \"Warriv\",\n";
                ss << u8"    \"esES\": \"Warriv\",\n";
                ss << u8"    \"frFR\": \"Warriv\",\n";
                ss << u8"    \"itIT\": \"Warriv\",\n";
                ss << u8"    \"koKR\": \"와리브\",\n";
                ss << u8"    \"plPL\": \"Warriv\",\n";
                ss << u8"    \"esMX\": \"Warriv\",\n";
                ss << u8"    \"jaJP\": \"ワリヴ\",\n";
                ss << u8"    \"ptBR\": \"Warriv\",\n";
                ss << u8"    \"ruRU\": \"Варрив\",\n";
                ss << u8"    \"zhCN\": \"瓦瑞夫\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 2896,\n";
                ss << u8"    \"Key\": \"Warriv\",\n";
                ss << u8"    \"enUS\": \"Warriv\",\n";
                ss << u8"    \"zhTW\": \"瓦瑞夫\",\n";
                ss << u8"    \"deDE\": \"Warriv\",\n";
                ss << u8"    \"esES\": \"Warriv\",\n";
                ss << u8"    \"frFR\": \"Warriv\",\n";
                ss << u8"    \"itIT\": \"Warriv\",\n";
                ss << u8"    \"koKR\": \"와리브\",\n";
                ss << u8"    \"plPL\": \"Warriv\",\n";
                ss << u8"    \"esMX\": \"Warriv\",\n";
                ss << u8"    \"jaJP\": \"ワリヴ\",\n";
                ss << u8"    \"ptBR\": \"Warriv\",\n";
                ss << u8"    \"ruRU\": \"Варрив\",\n";
                ss << u8"    \"zhCN\": \"瓦瑞夫\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 3022,\n";
                ss << u8"    \"Key\": \"Natalya\",\n";
                ss << u8"    \"enUS\": \"Natalya\",\n";
                ss << u8"    \"zhTW\": \"娜塔亞\",\n";
                ss << u8"    \"deDE\": \"Natalya\",\n";
                ss << u8"    \"esES\": \"Natalya\",\n";
                ss << u8"    \"frFR\": \"Natalya\",\n";
                ss << u8"    \"itIT\": \"Natalya\",\n";
                ss << u8"    \"koKR\": \"나탈랴\",\n";
                ss << u8"    \"plPL\": \"Natalia\",\n";
                ss << u8"    \"esMX\": \"Natalya\",\n";
                ss << u8"    \"jaJP\": \"ナターリャ\",\n";
                ss << u8"    \"ptBR\": \"Natalya\",\n";
                ss << u8"    \"ruRU\": \"Наталия\",\n";
                ss << u8"    \"zhCN\": \"娜塔亚\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 3023,\n";
                ss << u8"    \"Key\": \"Drognan\",\n";
                ss << u8"    \"enUS\": \"Drognan\",\n";
                ss << u8"    \"zhTW\": \"卓格南\",\n";
                ss << u8"    \"deDE\": \"Drognan\",\n";
                ss << u8"    \"esES\": \"Drognan\",\n";
                ss << u8"    \"frFR\": \"Drognan\",\n";
                ss << u8"    \"itIT\": \"Drognan\",\n";
                ss << u8"    \"koKR\": \"드로그난\",\n";
                ss << u8"    \"plPL\": \"Drognan\",\n";
                ss << u8"    \"esMX\": \"Drognan\",\n";
                ss << u8"    \"jaJP\": \"ドログナン\",\n";
                ss << u8"    \"ptBR\": \"Drognan\",\n";
                ss << u8"    \"ruRU\": \"Дрогнан\",\n";
                ss << u8"    \"zhCN\": \"卓格楠\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 3024,\n";
                ss << u8"    \"Key\": \"Atma\",\n";
                ss << u8"    \"enUS\": \"Atma\",\n";
                ss << u8"    \"zhTW\": \"亞特瑪\",\n";
                ss << u8"    \"deDE\": \"Atma\",\n";
                ss << u8"    \"esES\": \"Atma\",\n";
                ss << u8"    \"frFR\": \"Atma\",\n";
                ss << u8"    \"itIT\": \"Atma\",\n";
                ss << u8"    \"koKR\": \"아트마\",\n";
                ss << u8"    \"plPL\": \"Atma\",\n";
                ss << u8"    \"esMX\": \"Atma\",\n";
                ss << u8"    \"jaJP\": \"アトマ\",\n";
                ss << u8"    \"ptBR\": \"Atma\",\n";
                ss << u8"    \"ruRU\": \"Атма\",\n";
                ss << u8"    \"zhCN\": \"阿特玛\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 3025,\n";
                ss << u8"    \"Key\": \"Fara\",\n";
                ss << u8"    \"enUS\": \"Fara\",\n";
                ss << u8"    \"zhTW\": \"法拉\",\n";
                ss << u8"    \"deDE\": \"Fara\",\n";
                ss << u8"    \"esES\": \"Fara\",\n";
                ss << u8"    \"frFR\": \"Fara\",\n";
                ss << u8"    \"itIT\": \"Fara\",\n";
                ss << u8"    \"koKR\": \"파라\",\n";
                ss << u8"    \"plPL\": \"Fara\",\n";
                ss << u8"    \"esMX\": \"Fara\",\n";
                ss << u8"    \"jaJP\": \"ファラ\",\n";
                ss << u8"    \"ptBR\": \"Fara\",\n";
                ss << u8"    \"ruRU\": \"Фара\",\n";
                ss << u8"    \"zhCN\": \"法拉\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 3026,\n";
                ss << u8"    \"Key\": \"Lysander\",\n";
                ss << u8"    \"enUS\": \"Lysander\",\n";
                ss << u8"    \"zhTW\": \"雷山德\",\n";
                ss << u8"    \"deDE\": \"Lysander\",\n";
                ss << u8"    \"esES\": \"Lysander\",\n";
                ss << u8"    \"frFR\": \"Lysander\",\n";
                ss << u8"    \"itIT\": \"Lysander\",\n";
                ss << u8"    \"koKR\": \"라이샌더\",\n";
                ss << u8"    \"plPL\": \"Lysander\",\n";
                ss << u8"    \"esMX\": \"Lysander\",\n";
                ss << u8"    \"jaJP\": \"ライサンダー\",\n";
                ss << u8"    \"ptBR\": \"Lysander\",\n";
                ss << u8"    \"ruRU\": \"Лисандер\",\n";
                ss << u8"    \"zhCN\": \"雷山德\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 3027,\n";
                ss << u8"    \"Key\": \"Jerhyn\",\n";
                ss << u8"    \"enUS\": \"Jerhyn\",\n";
                ss << u8"    \"zhTW\": \"傑恩\",\n";
                ss << u8"    \"deDE\": \"Jerhyn\",\n";
                ss << u8"    \"esES\": \"Jerhyn\",\n";
                ss << u8"    \"frFR\": \"Jerhyn\",\n";
                ss << u8"    \"itIT\": \"Jerhyn\",\n";
                ss << u8"    \"koKR\": \"제르힌\",\n";
                ss << u8"    \"plPL\": \"Jerhyn\",\n";
                ss << u8"    \"esMX\": \"Jerhyn\",\n";
                ss << u8"    \"jaJP\": \"ジェラン\",\n";
                ss << u8"    \"ptBR\": \"Jerrin\",\n";
                ss << u8"    \"ruRU\": \"Джерхин\",\n";
                ss << u8"    \"zhCN\": \"耶尔辛\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 3028,\n";
                ss << u8"    \"Key\": \"jerhyn\",\n";
                ss << u8"    \"enUS\": \"Jerhyn\",\n";
                ss << u8"    \"zhTW\": \"傑恩\",\n";
                ss << u8"    \"deDE\": \"Jerhyn\",\n";
                ss << u8"    \"esES\": \"Jerhyn\",\n";
                ss << u8"    \"frFR\": \"Jerhyn\",\n";
                ss << u8"    \"itIT\": \"Jerhyn\",\n";
                ss << u8"    \"koKR\": \"제르힌\",\n";
                ss << u8"    \"plPL\": \"Jerhyn\",\n";
                ss << u8"    \"esMX\": \"Jerhyn\",\n";
                ss << u8"    \"jaJP\": \"ジェラン\",\n";
                ss << u8"    \"ptBR\": \"Jerrin\",\n";
                ss << u8"    \"ruRU\": \"Джерхин\",\n";
                ss << u8"    \"zhCN\": \"耶尔辛\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 3029,\n";
                ss << u8"    \"Key\": \"Geglash\",\n";
                ss << u8"    \"enUS\": \"Geglash\",\n";
                ss << u8"    \"zhTW\": \"基格列斯\",\n";
                ss << u8"    \"deDE\": \"Geglasch\",\n";
                ss << u8"    \"esES\": \"Geglash\",\n";
                ss << u8"    \"frFR\": \"Geglash\",\n";
                ss << u8"    \"itIT\": \"Geglash\",\n";
                ss << u8"    \"koKR\": \"게글라시\",\n";
                ss << u8"    \"plPL\": \"Geglash\",\n";
                ss << u8"    \"esMX\": \"Geglash\",\n";
                ss << u8"    \"jaJP\": \"ゲグラシュ\",\n";
                ss << u8"    \"ptBR\": \"Geglash\",\n";
                ss << u8"    \"ruRU\": \"Геглаш\",\n";
                ss << u8"    \"zhCN\": \"基格列斯\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 3030,\n";
                ss << u8"    \"Key\": \"Elzix\",\n";
                ss << u8"    \"enUS\": \"Elzix\",\n";
                ss << u8"    \"zhTW\": \"艾吉斯\",\n";
                ss << u8"    \"deDE\": \"Elzix\",\n";
                ss << u8"    \"esES\": \"Elzix\",\n";
                ss << u8"    \"frFR\": \"Elzix\",\n";
                ss << u8"    \"itIT\": \"Elzix\",\n";
                ss << u8"    \"koKR\": \"엘직스\",\n";
                ss << u8"    \"plPL\": \"Elzix\",\n";
                ss << u8"    \"esMX\": \"Elzix\",\n";
                ss << u8"    \"jaJP\": \"エルジックス\",\n";
                ss << u8"    \"ptBR\": \"Elzix\",\n";
                ss << u8"    \"ruRU\": \"Эльзикс\",\n";
                ss << u8"    \"zhCN\": \"艾吉斯\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 3031,\n";
                ss << u8"    \"Key\": \"Greiz\",\n";
                ss << u8"    \"enUS\": \"Greiz\",\n";
                ss << u8"    \"zhTW\": \"格雷茲\",\n";
                ss << u8"    \"deDE\": \"Griez\",\n";
                ss << u8"    \"esES\": \"Greiz\",\n";
                ss << u8"    \"frFR\": \"Greiz\",\n";
                ss << u8"    \"itIT\": \"Greiz\",\n";
                ss << u8"    \"koKR\": \"그레이즈\",\n";
                ss << u8"    \"plPL\": \"Greiz\",\n";
                ss << u8"    \"esMX\": \"Greiz\",\n";
                ss << u8"    \"jaJP\": \"グレイズ\",\n";
                ss << u8"    \"ptBR\": \"Greiz\",\n";
                ss << u8"    \"ruRU\": \"Греиз\",\n";
                ss << u8"    \"zhCN\": \"格雷兹\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 3032,\n";
                ss << u8"    \"Key\": \"Meshif\",\n";
                ss << u8"    \"enUS\": \"Meshif\",\n";
                ss << u8"    \"zhTW\": \"馬席夫\",\n";
                ss << u8"    \"deDE\": \"Meschif\",\n";
                ss << u8"    \"esES\": \"Meshif\",\n";
                ss << u8"    \"frFR\": \"Meshif\",\n";
                ss << u8"    \"itIT\": \"Meshif\",\n";
                ss << u8"    \"koKR\": \"메시프\",\n";
                ss << u8"    \"plPL\": \"Meshif\",\n";
                ss << u8"    \"esMX\": \"Meshif\",\n";
                ss << u8"    \"jaJP\": \"メシーフ\",\n";
                ss << u8"    \"ptBR\": \"Meshif\",\n";
                ss << u8"    \"ruRU\": \"Месхиф\",\n";
                ss << u8"    \"zhCN\": \"梅席夫\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 3112,\n";
                ss << u8"    \"Key\": \"navi\",\n";
                ss << u8"    \"enUS\": \"Flavie\",\n";
                ss << u8"    \"zhTW\": \"弗拉維\",\n";
                ss << u8"    \"deDE\": \"Flavie\",\n";
                ss << u8"    \"esES\": \"Flavia\",\n";
                ss << u8"    \"frFR\": \"Flavie\",\n";
                ss << u8"    \"itIT\": \"Flavie\",\n";
                ss << u8"    \"koKR\": \"플라비\",\n";
                ss << u8"    \"plPL\": \"Flawia\",\n";
                ss << u8"    \"esMX\": \"Flavie\",\n";
                ss << u8"    \"jaJP\": \"フラヴィ\",\n";
                ss << u8"    \"ptBR\": \"Flavi\",\n";
                ss << u8"    \"ruRU\": \"Флави\",\n";
                ss << u8"    \"zhCN\": \"弗拉维\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 3113,\n";
                ss << u8"    \"Key\": \"Kaelan\",\n";
                ss << u8"    \"enUS\": \"Kaelan\",\n";
                ss << u8"    \"zhTW\": \"凱藍\",\n";
                ss << u8"    \"deDE\": \"Kaelan\",\n";
                ss << u8"    \"esES\": \"Kaelan\",\n";
                ss << u8"    \"frFR\": \"Kaelan\",\n";
                ss << u8"    \"itIT\": \"Kaelan\",\n";
                ss << u8"    \"koKR\": \"캘란\",\n";
                ss << u8"    \"plPL\": \"Kaelan\",\n";
                ss << u8"    \"esMX\": \"Kaelan\",\n";
                ss << u8"    \"jaJP\": \"カイラン\",\n";
                ss << u8"    \"ptBR\": \"Kaelan\",\n";
                ss << u8"    \"ruRU\": \"Кейлан\",\n";
                ss << u8"    \"zhCN\": \"凯伦\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 3114,\n";
                ss << u8"    \"Key\": \"meshif\",\n";
                ss << u8"    \"enUS\": \"Meshif\",\n";
                ss << u8"    \"zhTW\": \"馬席夫\",\n";
                ss << u8"    \"deDE\": \"Meschif\",\n";
                ss << u8"    \"esES\": \"Meshif\",\n";
                ss << u8"    \"frFR\": \"Meshif\",\n";
                ss << u8"    \"itIT\": \"Meshif\",\n";
                ss << u8"    \"koKR\": \"메시프\",\n";
                ss << u8"    \"plPL\": \"Meshif\",\n";
                ss << u8"    \"esMX\": \"Meshif\",\n";
                ss << u8"    \"jaJP\": \"メシーフ\",\n";
                ss << u8"    \"ptBR\": \"Meshif\",\n";
                ss << u8"    \"ruRU\": \"Месхиф\",\n";
                ss << u8"    \"zhCN\": \"梅席夫\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 22476,\n";
                ss << u8"    \"Key\": \"Larzuk\",\n";
                ss << u8"    \"enUS\": \"Larzuk\",\n";
                ss << u8"    \"zhTW\": \"拉蘇克\",\n";
                ss << u8"    \"deDE\": \"Larzuk\",\n";
                ss << u8"    \"esES\": \"Larzuk\",\n";
                ss << u8"    \"frFR\": \"Larzuk\",\n";
                ss << u8"    \"itIT\": \"Larzuk\",\n";
                ss << u8"    \"koKR\": \"라르주크\",\n";
                ss << u8"    \"plPL\": \"Larzuk\",\n";
                ss << u8"    \"esMX\": \"Larzuk\",\n";
                ss << u8"    \"jaJP\": \"ラルザック\",\n";
                ss << u8"    \"ptBR\": \"Larzuk\",\n";
                ss << u8"    \"ruRU\": \"Ларзук\",\n";
                ss << u8"    \"zhCN\": \"拉苏克\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 22477,\n";
                ss << u8"    \"Key\": \"Drehya\",\n";
                ss << u8"    \"enUS\": \"Anya\",\n";
                ss << u8"    \"zhTW\": \"安亞\",\n";
                ss << u8"    \"deDE\": \"Anya\",\n";
                ss << u8"    \"esES\": \"Anya\",\n";
                ss << u8"    \"frFR\": \"Anya\",\n";
                ss << u8"    \"itIT\": \"Anya\",\n";
                ss << u8"    \"koKR\": \"안야\",\n";
                ss << u8"    \"plPL\": \"Anya\",\n";
                ss << u8"    \"esMX\": \"Anya\",\n";
                ss << u8"    \"jaJP\": \"アニャ\",\n";
                ss << u8"    \"ptBR\": \"Anya\",\n";
                ss << u8"    \"ruRU\": \"Аня\",\n";
                ss << u8"    \"zhCN\": \"安雅\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 22478,\n";
                ss << u8"    \"Key\": \"Malah\",\n";
                ss << u8"    \"enUS\": \"Malah\",\n";
                ss << u8"    \"zhTW\": \"瑪拉\",\n";
                ss << u8"    \"deDE\": \"Malah\",\n";
                ss << u8"    \"esES\": \"Malah\",\n";
                ss << u8"    \"frFR\": \"Malah\",\n";
                ss << u8"    \"itIT\": \"Malah\",\n";
                ss << u8"    \"koKR\": \"말라\",\n";
                ss << u8"    \"plPL\": \"Malah\",\n";
                ss << u8"    \"esMX\": \"Malah\",\n";
                ss << u8"    \"jaJP\": \"マラー\",\n";
                ss << u8"    \"ptBR\": \"Malah\",\n";
                ss << u8"    \"ruRU\": \"Малла\",\n";
                ss << u8"    \"zhCN\": \"马拉\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 22479,\n";
                ss << u8"    \"Key\": \"Nihlathak Town\",\n";
                ss << u8"    \"enUS\": \"Nihlathak\",\n";
                ss << u8"    \"zhTW\": \"尼拉塞克\",\n";
                ss << u8"    \"deDE\": \"Nihlathak\",\n";
                ss << u8"    \"esES\": \"Nihlathak\",\n";
                ss << u8"    \"frFR\": \"Nihlathak\",\n";
                ss << u8"    \"itIT\": \"Nihlathak\",\n";
                ss << u8"    \"koKR\": \"니흘라탁\",\n";
                ss << u8"    \"plPL\": \"Nihlathak\",\n";
                ss << u8"    \"esMX\": \"Nihlathak\",\n";
                ss << u8"    \"jaJP\": \"ニーラサック\",\n";
                ss << u8"    \"ptBR\": \"Nilatak\",\n";
                ss << u8"    \"ruRU\": \"Нильятак\",\n";
                ss << u8"    \"zhCN\": \"尼拉塞克\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 22480,\n";
                ss << u8"    \"Key\": \"Qual-Kehk\",\n";
                ss << u8"    \"enUS\": \"Qual-Kehk\",\n";
                ss << u8"    \"zhTW\": \"夸爾凱克\",\n";
                ss << u8"    \"deDE\": \"Qua-Kehk\",\n";
                ss << u8"    \"esES\": \"Qual-Kehk\",\n";
                ss << u8"    \"frFR\": \"Qual-Kehk\",\n";
                ss << u8"    \"itIT\": \"Qual-Kehk\",\n";
                ss << u8"    \"koKR\": \"콸케크\",\n";
                ss << u8"    \"plPL\": \"Qual-Kehk\",\n";
                ss << u8"    \"esMX\": \"Qual-Kehk\",\n";
                ss << u8"    \"jaJP\": \"クァル=ケック\",\n";
                ss << u8"    \"ptBR\": \"Qual-kehk\",\n";
                ss << u8"    \"ruRU\": \"Куаль-Кек\",\n";
                ss << u8"    \"zhCN\": \"夸尔凯克\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 22481,\n";
                ss << u8"    \"Key\": \"Act 5 Townguard\",\n";
                ss << u8"    \"enUS\": \"Guard\",\n";
                ss << u8"    \"zhTW\": \"守衛\",\n";
                ss << u8"    \"deDE\": \"Wächter\",\n";
                ss << u8"    \"esES\": \"Guardia\",\n";
                ss << u8"    \"frFR\": \"Garde\",\n";
                ss << u8"    \"itIT\": \"Guardia\",\n";
                ss << u8"    \"koKR\": \"경비병\",\n";
                ss << u8"    \"plPL\": \"Strażnik\",\n";
                ss << u8"    \"esMX\": \"Guardia\",\n";
                ss << u8"    \"jaJP\": \"衛兵\",\n";
                ss << u8"    \"ptBR\": \"Guarda\",\n";
                ss << u8"    \"ruRU\": \"Стражник\",\n";
                ss << u8"    \"zhCN\": \"卫兵\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 22482,\n";
                ss << u8"    \"Key\": \"Act 5 Combatant\",\n";
                ss << u8"    \"enUS\": \"Combatant\",\n";
                ss << u8"    \"zhTW\": \"參戰者\",\n";
                ss << u8"    \"deDE\": \"Kämpfer\",\n";
                ss << u8"    \"esES\": \"Combatiente\",\n";
                ss << u8"    \"frFR\": \"Combattant\",\n";
                ss << u8"    \"itIT\": \"Combattente\",\n";
                ss << u8"    \"koKR\": \"전투원\",\n";
                ss << u8"    \"plPL\": \"Bojownik\",\n";
                ss << u8"    \"esMX\": \"Combatiente\",\n";
                ss << u8"    \"jaJP\": \"兵士\",\n";
                ss << u8"    \"ptBR\": \"Combatente\",\n";
                ss << u8"    \"ruRU\": \"Боец\",\n";
                ss << u8"    \"zhCN\": \"争斗者\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 22483,\n";
                ss << u8"    \"Key\": \"Nihlathak\",\n";
                ss << u8"    \"enUS\": \"Nihlathak\",\n";
                ss << u8"    \"zhTW\": \"尼拉塞克\",\n";
                ss << u8"    \"deDE\": \"Nihlathak\",\n";
                ss << u8"    \"esES\": \"Nihlathak\",\n";
                ss << u8"    \"frFR\": \"Nihlathak\",\n";
                ss << u8"    \"itIT\": \"Nihlathak\",\n";
                ss << u8"    \"koKR\": \"니흘라탁\",\n";
                ss << u8"    \"plPL\": \"Nihlathak\",\n";
                ss << u8"    \"esMX\": \"Nihlathak\",\n";
                ss << u8"    \"jaJP\": \"ニーラサック\",\n";
                ss << u8"    \"ptBR\": \"Nilatak\",\n";
                ss << u8"    \"ruRU\": \"Нильятак\",\n";
                ss << u8"    \"zhCN\": \"尼拉塞克\"\n";
                ss << u8"  },\n";
                ss << u8"  {\n";
                ss << u8"    \"id\": 27075,\n";
                ss << u8"    \"Key\": \"Soldier\",\n";
                ss << u8"    \"enUS\": \"Soldier\",\n";
                ss << u8"    \"zhTW\": \"士兵\",\n";
                ss << u8"    \"deDE\": \"Soldat\",\n";
                ss << u8"    \"esES\": \"Soldado\",\n";
                ss << u8"    \"frFR\": \"Soldat\",\n";
                ss << u8"    \"itIT\": \"Soldato\",\n";
                ss << u8"    \"koKR\": \"병사\",\n";
                ss << u8"    \"plPL\": \"Żołnierz\",\n";
                ss << u8"    \"esMX\": \"Soldado\",\n";
                ss << u8"    \"jaJP\": \"兵士\",\n";
                ss << u8"    \"ptBR\": \"Soldado\",\n";
                ss << u8"    \"ruRU\": \"Солдат\",\n";
                ss << u8"    \"zhCN\": \"士兵\"\n";
                ss << u8"  }\n";
                ss << u8"]\n";
                defaultTxt = ss.str();
            }
            return defaultTxt;
        }
    }
}