/*
    Diablo II Character Editor
    Copyright (C) 2021-2023 Walter Couto

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/
//---------------------------------------------------------------------------

#include "pch.h"
#include <sstream>

namespace d2ce
{
    namespace TxtReaderHelper
    {
        const std::string& GetSetItems()
        {
            static std::string defaultTxt;
            if (defaultTxt.empty())
            {
                std::stringstream ss;
                ss << u8"index\t*ID\tset\titem\t*ItemName\trarity\tlvl\tlvl req\tchrtransform\tinvtransform\tinvfile\tflippyfile\tdropsound\tdropsfxframe\tusesound\tcost mult\tcost add\tadd func\tprop1\tpar1\tmin1\tmax1\tprop2\tpar2\tmin2\tmax2\tprop3\tpar3\tmin3\tmax3\tprop4\tpar4\tmin4\tmax4\tprop5\tpar5\tmin5\tmax5\tprop6\tpar6\tmin6\tmax6\tprop7\tpar7\tmin7\tmax7\tprop8\tpar8\tmin8\tmax8\tprop9\tpar9\tmin9\tmax9\taprop1a\tapar1a\tamin1a\tamax1a\taprop1b\tapar1b\tamin1b\tamax1b\taprop2a\tapar2a\tamin2a\tamax2a\taprop2b\tapar2b\tamin2b\tamax2b\taprop3a\tapar3a\tamin3a\tamax3a\taprop3b\tapar3b\tamin3b\tamax3b\taprop4a\tapar4a\tamin4a\tamax4a\taprop4b\tapar4b\tamin4b\tamax4b\taprop5a\tapar5a\tamin5a\tamax5a\taprop5b\tapar5b\tamin5b\tamax5b\tdiablocloneweight\t*eol\n";
                ss << u8"Civerb's Ward\t0\tCiverb's Vestments\tlrg\tLarge Shield\t7\t13\t9\tlyel\tlyel\t\t\t\t\t\t5\t2500\t1\tac\t\t15\t15\tblock\t\t15\t15\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tmana\t\t21\t22\t\t\t\t\tres-pois\t\t25\t26\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Civerb's Icon\t1\tCiverb's Vestments\tamu\tAmulet\t7\t13\t9\tlyel\tlyel\t\t\t\t\t\t5\t2500\t2\tregen-mana\t\t40\t40\tregen\t\t4\t4\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tres-cold\t\t25\t25\t\t\t\t\tac\t\t25\t25\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Civerb's Cudgel\t2\tCiverb's Vestments\tgsc\tGrand Scepter\t7\t13\t9\tlyel\tlyel\t\t\t\t\t\t5\t2500\t\tatt\t\t75\t75\tdmg-max\t\t17\t23\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdmg/lvl\t8\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Hsarus' Iron Heel\t3\tHsarus' Defense\tmbt\tChain Boots\t7\t4\t3\tdred\tdred\t\t\t\t\t\t5\t2500\t2\tres-fire\t\t25\t25\tmove2\t\t20\t20\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tatt/lvl\t20\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Hsarus' Iron Fist\t4\tHsarus' Defense\tbuc\tBuckler\t7\t4\t3\tdred\tdred\t\t\t\t\t\t5\t2500\t2\tred-dmg\t\t2\t2\tstr\t\t10\t10\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tac/lvl\t20\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Hsarus' Iron Stay\t5\tHsarus' Defense\tmbl\tBelt\t7\t4\t3\tdred\tdred\t\t\t\t\t\t5\t2500\t2\tres-cold\t\t20\t20\thp\t\t20\t20\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tac/lvl\t20\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Cleglaw's Tooth\t6\tCleglaw's Brace\tlsd\tLong Sword\t7\t6\t4\tlred\tlred\t\t\t\t\t\t5\t2500\t2\tatt%\t\t30\t30\tdeadly\t\t50\t50\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdmg/lvl\t10\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Cleglaw's Claw\t7\tCleglaw's Brace\tsml\tSmall Shield\t7\t6\t4\tlred\tlred\t\t\t\t\t\t5\t2500\t2\tac\t\t17\t17\tres-pois-len\t\t75\t75\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tres-all\t\t15\t15\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Cleglaw's Pincers\t8\tCleglaw's Brace\tmgl\tChain Gloves\t7\t6\t4\tlred\tlred\t\t\t\t\t\t5\t2500\t2\tknock\t\t1\t1\tslow\t\t25\t25\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tatt/lvl\t20\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Iratha's Collar\t9\tIratha's Finery\tamu\tAmulet\t7\t21\t15\tlgry\tlgry\t\t\t\t\t\t5\t2500\t2\tres-pois\t\t30\t30\tres-pois-len\t\t75\t75\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tres-all\t\t15\t15\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Iratha's Cuff\t10\tIratha's Finery\ttgl\tLight Gauntlets\t7\t21\t15\tlgry\tlgry\t\t\t\t\t\t5\t2500\t2\tres-cold\t\t30\t30\thalf-freeze\t\t1\t1\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tswing2\t\t20\t20\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Iratha's Coil\t11\tIratha's Finery\tcrn\tCrown\t7\t21\t15\tlgry\tlgry\t\t\t\t\t\t5\t2500\t2\tres-fire\t\t30\t30\tres-ltng\t\t30\t30\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tac/lvl\t16\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Iratha's Cord\t12\tIratha's Finery\ttbl\tHeavy Belt\t7\t21\t15\tlgry\tlgry\t\t\t\t\t\t5\t2500\t2\tac\t\t25\t25\tdmg-min\t\t5\t5\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdex\t\t10\t10\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Isenhart's Lightbrand\t13\tIsenhart's Armory\tbsd\tBroad Sword\t7\t11\t8\tlgld\tlgld\t\t\t\t\t\t5\t2500\t2\tdmg-min\t\t10\t10\tswing2\t\t20\t20\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tatt/lvl\t10\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Isenhart's Parry\t14\tIsenhart's Armory\tgts\tGothic Shield\t7\t11\t8\tlgld\tlgld\t\t\t\t\t\t5\t2500\t2\tac\t\t40\t40\tlight-thorns\t\t4\t4\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tres-all\t\t8\t8\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Isenhart's Case\t15\tIsenhart's Armory\tbrs\tBreast Plate\t7\t11\t8\tlgld\tlgld\t\t\t\t\t\t5\t2500\t2\tac\t\t40\t40\tred-mag\t\t2\t2\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tac/lvl\t16\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Isenhart's Horns\t16\tIsenhart's Armory\tfhl\tFull Helm\t7\t11\t8\tlgld\tlgld\t\t\t\t\t\t5\t2500\t2\tdex\t\t6\t6\tred-dmg\t\t2\t2\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tres-all\t\t8\t8\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Vidala's Barb\t17\tVidala's Rig\tlbb\tLong Battle Bow\t7\t19\t14\tblac\tblac\t\t\t\t\t\t5\t2500\t2\tltng-min\t\t1\t1\tltng-max\t\t20\t20\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tatt/lvl\t16\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Vidala's Fetlock\t18\tVidala's Rig\ttbt\tLight Plated Boots\t7\t19\t14\tblac\tblac\t\t\t\t\t\t5\t2500\t2\tstam\t\t150\t150\tmove3\t\t30\t30\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tres-all\t\t8\t8\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Vidala's Ambush\t19\tVidala's Rig\tlea\tLeather Armor\t7\t19\t14\tblac\tblac\t\t\t\t\t\t5\t2500\t2\tac\t\t50\t50\tdex\t\t11\t11\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tres-fire\t\t24\t24\t\t\t\t\tac/lvl\t20\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Vidala's Snare\t20\tVidala's Rig\tamu\tAmulet\t7\t19\t14\tblac\tblac\t\t\t\t\t\t5\t2500\t2\thp\t\t15\t15\tres-cold\t\t20\t20\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tmag%\t\t50\t50\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Milabrega's Orb\t21\tMilabrega's Regalia\tkit\tKite Shield\t7\t23\t17\tdblu\tdblu\t\t\t\t\t\t5\t2500\t2\tmag%\t\t20\t20\tac\t\t25\t25\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\thp\t\t50\t50\t\t\t\t\tac%\t\t50\t50\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Milabrega's Rod\t22\tMilabrega's Regalia\twsp\tWar Scepter\t7\t23\t17\tdblu\tdblu\t\t\t\t\t\t5\t2500\t\tpal\t\t1\t1\tdmg%\t\t50\t50\tlight\t\t2\t2\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Milabrega's Diadem\t23\tMilabrega's Regalia\tcrn\tCrown\t7\t23\t17\tdblu\tdblu\t\t\t\t\t\t5\t2500\t2\thp\t\t15\t15\tmana\t\t15\t15\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tres-cold\t\t40\t40\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Milabrega's Robe\t24\tMilabrega's Regalia\taar\tAncient Armor\t7\t23\t17\tdblu\tdblu\t\t\t\t\t\t5\t2500\t2\tthorns\t\t3\t3\tred-dmg\t\t2\t2\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tac%\t\t100\t100\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Cathan's Rule\t25\tCathan's Traps\tbst\tBattle Staff\t7\t15\t11\tdgrn\tdgrn\t\t\t\t\t\t5\t2500\t2\tfireskill\t\t1\t1\tfire-max\t\t10\t10\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tmana\t\t50\t50\t\t\t\t\tres-all\t\t10\t10\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Cathan's Mesh\t26\tCathan's Traps\tchn\tChain Mail\t7\t15\t11\tdgrn\tdgrn\t\t\t\t\t\t5\t2500\t2\tac\t\t15\t15\tease\t\t-50\t-50\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tthorns\t\t5\t5\t\t\t\t\tres-fire\t\t30\t30\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Cathan's Visage\t27\tCathan's Traps\tmsk\tMask\t7\t15\t11\tdgrn\tdgrn\t\t\t\t\t\t5\t2500\t2\tmana\t\t20\t20\tres-cold\t\t25\t25\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tac/lvl\t16\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Cathan's Sigil\t28\tCathan's Traps\tamu\tAmulet\t7\t15\t11\tdgrn\tdgrn\t\t\t\t\t\t5\t2500\t2\tbalance1\t\t10\t10\tlight-thorns\t\t5\t5\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tatt\t\t50\t50\t\t\t\t\tmag%\t\t25\t25\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Cathan's Seal\t29\tCathan's Traps\trin\tRing\t7\t15\t11\tdgrn\tdgrn\t\t\t\t\t\t5\t2500\t2\tlifesteal\t\t6\t6\tred-dmg\t\t2\t2\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tstr\t\t10\t10\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Tancred's Crowbill\t30\tTancred's Battlegear\tmpi\tMilitary Pick\t7\t27\t20\tdgld\tdgld\t\t\t\t\t\t5\t2500\t2\tatt\t\t75\t75\tdmg%\t\t80\t80\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tmana\t\t20\t20\t\t\t\t\tswing2\t\t20\t20\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Tancred's Spine\t31\tTancred's Battlegear\tful\tFull Plate Mail\t7\t27\t20\tdgld\tdgld\t\t\t\t\t\t5\t2500\t2\thp\t\t40\t40\tstr\t\t15\t15\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tac/lvl\t16\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Tancred's Hobnails\t32\tTancred's Battlegear\tlbt\tBoots\t7\t27\t20\tdgld\tdgld\t\t\t\t\t\t5\t2500\t2\tregen-stam\t\t25\t25\tdex\t\t10\t10\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tmove3\t\t30\t30\t\t\t\t\tstr\t\t10\t10\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Tancred's Weird\t33\tTancred's Battlegear\tamu\tAmulet\t7\t27\t20\tdgld\tdgld\t\t\t\t\t\t5\t2500\t2\tred-dmg\t\t2\t2\tred-mag\t\t1\t1\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tmag%\t\t78\t78\t\t\t\t\tatt\t\t60\t60\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Tancred's Skull\t34\tTancred's Battlegear\tbhm\tBone Helm\t7\t27\t20\tdgld\tdgld\t\t\t\t\t\t5\t2500\t2\tdmg%\t\t10\t10\tatt\t\t40\t40\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tres-all\t\t10\t10\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Sigon's Gage\t35\tSigon's Complete Steel\thgl\tGauntlets\t7\t9\t6\twhit\twhit\t\t\t\t\t\t5\t2500\t2\tstr\t\t10\t10\tatt\t\t20\t20\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tswing3\t\t30\t30\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Sigon's Visor\t36\tSigon's Complete Steel\tghm\tGreat Helm\t7\t9\t6\twhit\twhit\t\t\t\t\t\t5\t2500\t2\tmana\t\t30\t30\tac\t\t25\t25\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tatt/lvl\t16\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Sigon's Shelter\t37\tSigon's Complete Steel\tgth\tGothic Plate\t7\t9\t6\twhit\twhit\t\t\t\t\t\t5\t2500\t2\tac%\t\t25\t25\tres-ltng\t\t30\t30\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tthorns\t\t20\t20\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Sigon's Sabot\t38\tSigon's Complete Steel\thbt\tGreaves\t7\t9\t6\twhit\twhit\t\t\t\t\t\t5\t2500\t2\tmove2\t\t20\t20\tres-cold\t\t40\t40\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tatt\t\t50\t50\t\t\t\t\tmag%\t\t50\t50\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Sigon's Wrap\t39\tSigon's Complete Steel\thbl\tPlated Belt\t7\t9\t6\twhit\twhit\t\t\t\t\t\t5\t2500\t2\tres-fire\t\t20\t20\thp\t\t20\t20\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tac/lvl\t16\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Sigon's Guard\t40\tSigon's Complete Steel\ttow\tTower Shield\t7\t9\t6\twhit\twhit\t\t\t\t\t\t5\t2500\t2\tallskills\t\t1\t1\tblock\t\t20\t20\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Infernal Cranium\t41\tInfernal Tools\tcap\tCap\t7\t7\t5\tlyel\tlyel\t\t\t\t\t\t5\t2500\t2\tres-all\t\t10\t10\tdmg-to-mana\t\t20\t20\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tac/lvl\t16\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Infernal Torch\t42\tInfernal Tools\tgwn\tGrim Wand\t7\t7\t5\tlyel\tlyel\t\t\t\t\t\t5\t2500\t2\tdmg-min\t\t8\t8\tnec\t\t1\t1\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tatt/lvl\t20\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Infernal Sign\t43\tInfernal Tools\ttbl\tHeavy Belt\t7\t7\t5\tlyel\tlyel\t\t\t\t\t\t5\t2500\t2\tac\t\t25\t25\thp\t\t20\t20\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tres-pois\t\t25\t25\t\t\t\t\thalf-freeze\t\t1\t1\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Berserker's Headgear\t44\tBerserker's Garb\thlm\tHelm\t7\t5\t3\tdred\tdred\t\t\t\t\t\t5\t2500\t2\tac\t\t15\t15\tres-fire\t\t25\t25\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tatt/lvl\t16\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Berserker's Hauberk\t45\tBerserker's Garb\tspl\tSplint Mail\t7\t5\t3\tdred\tdred\t\t\t\t\t\t5\t2500\t2\tred-mag\t\t2\t2\tbar\t\t1\t1\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tac/lvl\t24\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Berserker's Hatchet\t46\tBerserker's Garb\t2ax\tDouble Axe\t7\t5\t3\tdred\tdred\t\t\t\t\t\t5\t2500\t2\tatt%\t\t30\t30\tmanasteal\t\t5\t5\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdmg%\t\t50\t50\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Death's Hand\t47\tDeath's Disguise\tlgl\tLeather Gloves\t7\t8\t6\tlred\tlred\t\t\t\t\t\t5\t2500\t2\tres-pois\t\t50\t50\tres-pois-len\t\t75\t75\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tswing3\t\t30\t30\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Death's Guard\t48\tDeath's Disguise\tlbl\tSash\t7\t8\t6\tlred\tlred\t\t\t\t\t\t5\t2500\t2\tac\t\t20\t20\tnofreeze\t\t1\t1\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tres-all\t\t15\t15\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Death's Touch\t49\tDeath's Disguise\twsd\tWar Sword\t7\t8\t6\tlred\tlred\t\t\t\t\t\t5\t2500\t2\tdmg%\t\t25\t25\tlifesteal\t\t4\t4\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdmg-cold\t75\t25\t75\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Angelic Sickle\t50\tAngelical Raiment\tsbr\tSabre\t7\t17\t12\tlgry\tlgry\t\t\t\t\t\t5\t2500\t2\tatt\t\t75\t75\tdmg-undead\t\t250\t250\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdmg%\t\t75\t75\t\t\t\t\tswing3\t\t30\t30\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Angelic Mantle\t51\tAngelical Raiment\trng\tRing Mail\t7\t17\t12\tlgry\tlgry\t\t\t\t\t\t5\t2500\t2\tred-dmg\t\t3\t3\tac%\t\t40\t40\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tac\t\t150\t150\t\t\t\t\tres-fire\t\t50\t50\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Angelic Halo\t52\tAngelical Raiment\trin\tRing\t3\t17\t12\tlgry\tlgry\t\t\t\t\t\t5\t2500\t2\tregen\t\t6\t6\thp\t\t20\t20\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tatt/lvl\t24\t\t\t\t\t\t\tmag%\t\t50\t50\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Angelic Wings\t53\tAngelical Raiment\tamu\tAmulet\t7\t17\t12\tlgry\tlgry\t\t\t\t\t\t5\t2500\t2\tlight\t\t3\t3\tdmg-to-mana\t\t20\t20\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\thp\t\t75\t75\t\t\t\t\tallskills\t\t1\t1\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Arctic Horn\t54\tArctic Gear\tswb\tShort War Bow\t7\t3\t2\tlgld\tlgld\t\t\t\t\t\t5\t2500\t2\tatt%\t\t20\t20\tdmg%\t\t50\t50\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tatt/lvl\t16\t\t\t\t\t\t\tdmg-cold\t75\t20\t30\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Arctic Furs\t55\tArctic Gear\tqui\tQuilted Armor\t7\t3\t2\tlgld\tlgld\t\t\t\t\t\t5\t2500\t2\tac%\t\t275\t325\tres-all\t\t10\t10\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tac/lvl\t24\t\t\t\t\t\t\tres-cold\t\t15\t15\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Arctic Binding\t56\tArctic Gear\tvbl\tLight Belt\t7\t3\t2\tlgld\tlgld\t\t\t\t\t\t5\t2500\t2\tres-cold\t\t40\t40\tac\t\t30\t30\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tmag%\t\t40\t40\t\t\t\t\tres-cold\t\t10\t10\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Arctic Mitts\t57\tArctic Gear\ttgl\tLight Gauntlets\t7\t3\t2\tlgld\tlgld\t\t\t\t\t\t5\t2500\t2\thp\t\t20\t20\tswing1\t\t10\t10\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tatt\t\t50\t50\t\t\t\t\tdex\t\t10\t10\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Arcanna's Sign\t58\tArcanna's Tricks\tamu\tAmulet\t1\t20\t15\tblac\tblac\t\t\t\t\t\t5\t2500\t2\tmana\t\t15\t15\tregen-mana\t\t20\t20\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tmag%\t\t50\t50\t\t\t\t\tres-fire\t\t20\t20\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Arcanna's Deathwand\t59\tArcanna's Tricks\twst\tWar Staff\t7\t20\t15\tblac\tblac\t\t\t\t\t\t5\t2500\t2\tsor\t\t1\t1\tdeadly\t\t25\t25\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tmana\t\t50\t50\t\t\t\t\tregen-mana\t\t5\t5\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Arcanna's Head\t60\tArcanna's Tricks\tskp\tSkull Cap\t7\t20\t15\tblac\tblac\t\t\t\t\t\t5\t2500\t2\tregen\t\t4\t4\tthorns\t\t2\t2\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tac/lvl\t24\t\t\t\t\t\t\tres-ltng\t\t15\t15\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Arcanna's Flesh\t61\tArcanna's Tricks\tltp\tLight Plate\t7\t20\t15\tblac\tblac\t\t\t\t\t\t5\t2500\t2\tlight\t\t2\t2\tred-dmg\t\t3\t3\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tac\t\t100\t100\t\t\t\t\tenr\t\t10\t10\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Expansion\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
                ss << u8"Natalya's Totem\t62\tNatalya's Odium\txh9\tGrim Helm\t7\t22\t59\tdgry\tdgry\t\t\t\t\t\t5\t5000\t\tac\t\t135\t175\tdex\t\t20\t30\tstr\t\t10\t20\tres-all\t\t10\t20\tred-mag\t\t3\t3\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Natalya's Mark\t63\tNatalya's Odium\t7qr\tScissors Suwayyah\t7\t22\t79\tdgry\tdgry\t\t\t\t\t\t5\t5000\t\tswing3\t\t40\t40\tdmg%\t\t200\t200\tignore-ac\t\t1\t1\tdmg-cold\t100\t50\t50\tdmg-fire\t\t12\t17\tdmg-undead\t\t200\t200\tdmg-demon\t\t200\t200\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Natalya's Shadow\t64\tNatalya's Odium\tucl\tLoricated Mail\t7\t22\t73\tdgry\tdgry\t\t\t\t\t\t5\t5000\t\tac\t\t150\t225\thp/lvl\t8\t\t\tskilltab\t19\t2\t2\tres-pois-len\t\t75\t75\tres-pois\t\t25\t25\tsock\t\t1\t3\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Natalya's Soul\t65\tNatalya's Odium\txmb\tMesh Boots\t7\t22\t25\tdgry\tdgry\t\t\t\t\t\t5\t5000\t\tac\t\t75\t125\tmove3\t\t40\t40\tregen-stam/lvl\t2\t\t\tdur\t\t50\t50\tres-cold\t\t15\t25\tres-ltng\t\t15\t25\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Aldur's Stony Gaze\t66\tAldur's Watchtower\tdr8\tHunter's Guise\t7\t29\t36\toran\toran\t\t\t\t\t\t5\t5000\t2\tac\t\t90\t90\tregen-mana\t\t17\t17\tlight\t\t5\t5\tbalance3\t\t25\t25\tres-cold\t\t40\t50\tsock\t\t2\t2\t\t\t\t\t\t\t\t\t\t\t\t\tenr\t\t15\t15\t\t\t\t\tenr\t\t15\t15\t\t\t\t\tenr\t\t15\t15\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Aldur's Deception\t67\tAldur's Watchtower\tuul\tShadow Plate\t7\t29\t76\toran\toran\t\t\t\t\t\t5\t5000\t2\tac\t\t300\t300\tskilltab\t16\t1\t1\tstr\t\t20\t20\tdex\t\t15\t15\tres-ltng\t\t40\t50\tease\t\t-50\t-50\tskilltab\t17\t1\t1\t\t\t\t\t\t\t\t\tvit\t\t15\t15\t\t\t\t\tvit\t\t15\t15\t\t\t\t\tvit\t\t15\t15\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Aldur's Gauntlet\t68\tAldur's Watchtower\t9mt\tJagged Star\t7\t29\t42\toran\toran\t\t\t\t\t\t5\t5000\t2\tdmg-norm\t\t40\t62\tdmg-ltng\t\t50\t75\tlifesteal\t\t10\t10\tswing3\t\t30\t30\tdmg-demon\t\t200\t200\tmanasteal\t\t5\t5\tsock\t\t2\t5\t\t\t\t\t\t\t\t\tstr\t\t15\t15\t\t\t\t\tstr\t\t15\t15\t\t\t\t\tstr\t\t15\t15\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Aldur's Advance\t69\tAldur's Watchtower\txtb\tBattle Boots\t7\t29\t45\toran\toran\t\t\t\t\t\t5\t5000\t2\tindestruct\t\t1\t1\tregen-stam\t\t32\t32\thp\t\t50\t50\tdmg-to-mana\t\t10\t10\tmove3\t\t40\t40\tstam\t\t180\t180\tres-fire\t\t40\t50\t\t\t\t\t\t\t\t\tdex\t\t15\t15\t\t\t\t\tdex\t\t15\t15\t\t\t\t\tdex\t\t15\t15\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Immortal King's Will\t70\tImmortal King\tba5\tAvenger Guard\t7\t37\t47\tlgry\tlgry\t\t\t\t\t\t5\t5000\t\tac\t\t125\t125\tgold%\t\t37\t37\tskilltab\t14\t2\t2\tlight\t\t4\t4\tmag%\t\t25\t40\tsock\t\t2\t2\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Immortal King's Soul Cage\t71\tImmortal King\tuar\tSacred Armor\t7\t37\t76\tlgry\tlgry\t\t\t\t\t\t5\t5000\t2\tac\t\t400\t400\tgethit-skill\t52\t5\t5\tskilltab\t12\t2\t2\tres-pois\t\t50\t50\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tbalance2\t\t25\t25\t\t\t\t\tres-cold\t\t40\t40\t\t\t\t\tres-fire\t\t40\t40\t\t\t\t\tres-ltng\t\t40\t40\t\t\t\t\tac%\t\t50\t50\t\t\t\t\t\t0\n";
                ss << u8"Immortal King's Detail\t72\tImmortal King\tzhb\tWar Belt\t7\t37\t29\tlgry\tlgry\t\t\t\t\t\t5\t5000\t2\tac\t\t36\t36\tres-fire\t\t28\t28\tres-ltng\t\t31\t31\tstr\t\t25\t25\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tac\t\t105\t105\t\t\t\t\tbalance2\t\t25\t25\t\t\t\t\tac%\t\t100\t100\t\t\t\t\tred-dmg%\t\t20\t20\t\t\t\t\tskilltab\t13\t2\t2\t\t\t\t\t\t0\n";
                ss << u8"Immortal King's Forge\t73\tImmortal King\txhg\tWar Gauntlets\t7\t37\t30\tlgry\tlgry\t\t\t\t\t\t5\t5000\t2\tac\t\t65\t65\tstr\t\t20\t20\tdex\t\t20\t20\tgethit-skill\t38\t12\t4\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tswing2\t\t25\t25\t\t\t\t\tac\t\t120\t120\t\t\t\t\tlifesteal\t\t10\t10\t\t\t\t\tmanasteal\t\t10\t10\t\t\t\t\tfreeze\t\t2\t2\t\t\t\t\t\t0\n";
                ss << u8"Immortal King's Pillar\t74\tImmortal King\txhb\tWar Boots\t7\t37\t31\tlgry\tlgry\t\t\t\t\t\t5\t5000\t2\tac\t\t75\t75\tmove3\t\t40\t40\tatt\t\t110\t110\thp\t\t44\t44\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tmag%\t\t25\t25\t\t\t\t\tskilltab\t12\t2\t2\t\t\t\t\tac\t\t160\t160\t\t\t\t\thalf-freeze\t\t1\t1\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Immortal King's Stone Crusher\t75\tImmortal King\t7m7\tOgre Maul\t7\t37\t76\tlgry\tlgry\t\t\t\t\t\t5\t5000\t2\tindestruct\t\t1\t1\tswing3\t\t40\t40\tdmg-demon\t\t200\t200\tdmg-undead\t\t200\t200\tcrush\t\t35\t40\tdmg%\t\t200\t200\tsock\t\t2\t2\t\t\t\t\t\t\t\t\tdmg-fire\t\t211\t397\t\t\t\t\tdmg-ltng\t\t7\t477\t\t\t\t\tdmg-cold\t150\t127\t364\t\t\t\t\tdmg-pois\t150\t349\t349\t\t\t\t\tdmg-mag\t\t250\t361\t\t\t\t\t\t0\n";
                ss << u8"Tal Rasha's Fire-Spun Cloth\t76\tTal Rasha's Wrappings\tzmb\tMesh Belt\t7\t26\t53\tdpur\tdpur\t\t\t\t\t\t5\t5000\t2\tease\t\t-20\t-20\tmana\t\t30\t30\tdex\t\t20\t20\tdmg-to-mana\t\t37\t37\tmag%\t\t10\t15\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tac\t\t60\t60\t\t\t\t\tcast2\t\t10\t10\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Tal Rasha's Adjudication\t77\tTal Rasha's Wrappings\tamu\tAmulet\t1\t26\t67\tdpur\tdpur\t\t\t\t\t\t5\t5000\t2\tres-ltng\t\t33\t33\tsor\t\t2\t2\thp\t\t50\t50\tdmg-ltng\t\t3\t32\tmana\t\t42\t42\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tcast2\t\t10\t10\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Tal Rasha's Lidless Eye\t78\tTal Rasha's Wrappings\toba\tSwirling Crystal\t7\t26\t65\tdpur\tdpur\t\t\t\t\t\t5\t5000\t2\thp\t\t57\t57\tmana\t\t77\t77\tenr\t\t10\t10\tcast3\t\t20\t20\tskill\tFire Mastery\t1\t2\tskill\tLightning Mastery\t1\t2\tskill\tCold Mastery\t1\t2\t\t\t\t\t\t\t\t\tsor\t\t1\t1\t\t\t\t\tpierce-fire\t\t15\t15\t\t\t\t\tpierce-ltng\t\t15\t15\t\t\t\t\textra-cold\t\t15\t15\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Tal Rasha's Howling Wind\t79\tTal Rasha's Wrappings\tuth\tLacquered Plate\t7\t26\t71\tdpur\tdpur\t\t\t\t\t\t5\t5000\t2\tease\t\t-60\t-60\tred-mag\t\t15\t15\tmag%\t\t88\t88\tres-cold\t\t40\t40\tres-fire\t\t40\t40\tres-ltng\t\t40\t40\tac\t\t400\t400\t\t\t\t\t\t\t\t\tcast2\t\t10\t10\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Tal Rasha's Horadric Crest\t80\tTal Rasha's Wrappings\txsk\tDeath Mask\t7\t26\t66\tdpur\tdpur\t\t\t\t\t\t5\t5000\t\tmana\t\t30\t30\thp\t\t60\t60\tac\t\t45\t45\tres-all\t\t15\t15\tlifesteal\t\t10\t10\tmanasteal\t\t10\t10\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Griswold's Valor\t81\tGriswold's Legacy\turn\tCorona\t7\t44\t69\tdgld\tdgld\t\t\t\t\t\t5\t5000\t2\tac%\t\t50\t75\tabs-cold/lvl\t\t2\t2\tsock\t\t2\t2\tease\t\t-40\t-40\tmag%\t\t20\t30\tres-all\t\t5\t5\t\t\t\t\t\t\t\t\t\t\t\t\tskilltab\t10\t2\t2\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Griswold's Heart\t82\tGriswold's Legacy\txar\tOrnate Plate\t7\t44\t45\tdgld\tdgld\t\t\t\t\t\t5\t5000\t\tac\t\t500\t500\tskilltab\t11\t2\t2\tsock\t\t3\t3\tstr\t\t20\t20\tease\t\t-40\t-40\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Griswolds's Redemption\t83\tGriswold's Legacy\t7ws\tCaduceus\t7\t44\t53\tdgld\tdgld\t\t\t\t\t\t5\t5000\t2\tdmg%\t\t200\t240\tswing2\t\t40\t40\tdmg-undead\t\t200\t200\tease\t\t-20\t-20\tsock\t\t3\t4\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tskilltab\t9\t2\t2\t\t\t\t\tdmg-norm\t\t10\t20\t\t\t\t\tdmg-norm\t\t10\t20\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Griswold's Honor\t84\tGriswold's Legacy\tpaf\tVortex Shield\t7\t44\t68\tdgld\tdgld\t\t\t\t\t\t5\t5000\t\tac\t\t108\t108\tsock\t3\t\t\tblock2\t\t65\t65\tblock\t\t20\t20\tres-all\t\t45\t45\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Trang-Oul's Guise\t85\tTrang-Oul's Avatar\tuh9\tBone Visage\t7\t32\t65\tdgld\tdgld\t\t\t\t\t\t5\t5000\t\tac\t\t80\t100\tbalance2\t\t25\t25\tthorns\t\t20\t20\tmana\t\t150\t150\tregen\t\t5\t5\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Trang-Oul's Scales\t86\tTrang-Oul's Avatar\txul\tChaos Armor\t7\t32\t49\tdyel\tdyel\t\t\t\t\t\t5\t5000\t2\tease\t\t-40\t-40\tac-miss\t\t100\t100\tres-pois\t\t40\t40\tskilltab\t8\t2\t2\tmove3\t\t40\t40\tac%\t\t150\t150\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tres-ltng\t\t50\t50\t\t\t\t\t\t\t\t\t\t\t\t\tred-dmg%\t\t25\t25\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Trang-Oul's Wing\t87\tTrang-Oul's Avatar\tne9\tCantor Trophy\t7\t32\t54\tdyel\tdyel\t\t\t\t\t\t5\t5000\t2\tac\t\t125\t125\tstr\t\t25\t25\tdex\t\t15\t15\tres-fire\t\t38\t45\tblock\t\t30\t30\tres-pois\t\t40\t40\tskilltab\t7\t2\t2\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tpierce-pois\t\t25\t25\t\t\t\t\tregen\t\t15\t15\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Trang-Oul's Claws\t88\tTrang-Oul's Avatar\txmg\tHeavy Bracers\t7\t32\t45\tdyel\tdyel\t\t\t\t\t\t5\t5000\t\tac\t\t30\t30\tcast3\t\t20\t20\tres-cold\t\t30\t30\tskilltab\t6\t2\t2\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\textra-pois\t\t25\t25\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Trang-Oul's Girth\t89\tTrang-Oul's Avatar\tutc\tTroll Belt\t7\t32\t47\tdyel\tdyel\t\t\t\t\t\t5\t5000\t2\tac\t\t75\t100\tstam\t\t30\t30\tregen\t\t5\t5\thp\t\t66\t66\tnofreeze\t\t1\t1\tease\t\t-40\t-40\tmana\t\t25\t50\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tres-cold\t\t40\t40\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"M'avina's True Sight\t90\tM'avina's Battle Hymn\tci3\tDiadem\t7\t21\t59\twhit\twhit\t\t\t\t\t\t5\t5000\t2\tac\t\t150\t150\tregen\t\t10\t10\tswing2\t\t30\t30\tmana\t\t25\t25\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tallskills\t\t1\t1\t\t\t\t\tatt%\t\t50\t50\t\t\t\t\tres-all\t\t25\t25\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"M'avina's Embrace\t91\tM'avina's Battle Hymn\tuld\tKraken Shell\t7\t21\t70\twhit\twhit\t\t\t\t\t\t5\t5000\t2\tgethit-skill\t55\t10\t3\tease\t\t-30\t-30\tred-mag\t\t5\t12\tskilltab\t1\t2\t2\tac/lvl\t32\t\t\tac\t\t350\t350\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tbalance2\t\t30\t30\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"M'avina's Icy Clutch\t92\tM'avina's Battle Hymn\txtg\tBattle Gauntlets\t7\t21\t32\twhit\twhit\t\t\t\t\t\t5\t5000\t2\tac\t\t45\t50\tdmg-cold\t150\t6\t18\thalf-freeze\t\t1\t1\tgold%\t\t56\t56\tstr\t\t10\t10\tdex\t\t15\t15\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdmg-cold\t100\t131\t252\t\t\t\t\textra-cold\t\t20\t20\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"M'avina's Tenet\t93\tM'avina's Battle Hymn\tzvb\tSharkskin Belt\t7\t21\t45\twhit\twhit\t\t\t\t\t\t5\t5000\t2\tac\t\t50\t50\tmove2\t\t20\t20\tmanasteal\t\t5\t5\tlight\t\t5\t5\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tres-all\t\t25\t25\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"M'avina's Caster\t94\tM'avina's Battle Hymn\tamc\tGrand Matron Bow\t7\t21\t70\twhit\twhit\t\t\t\t\t\t5\t5000\t2\tdmg%\t\t188\t188\tswing3\t\t40\t40\tmagicarrow\t\t1\t1\tatt\t\t50\t50\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdmg-mag\t\t114\t377\t\t\t\t\thit-skill\tNova\t10\t15\t\t\t\t\tskilltab\t0\t2\t2\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Telling of Beads\t95\tThe Disciple\tamu\tAmulet\t1\t39\t30\tlblu\tlblu\t\t\t\t\t\t5\t5000\t\tres-pois\t\t35\t50\tallskills\t\t1\t1\tres-cold\t\t18\t18\tthorns\t\t8\t10\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Laying of Hands\t96\tThe Disciple\tulg\tBramble Mitts\t7\t39\t63\tlblu\tlblu\t\t\t\t\t\t5\t5000\t\tac\t\t25\t25\tswing2\t\t20\t20\tres-fire\t\t50\t50\tdmg-demon\t\t350\t350\thit-skill\t101\t10\t3\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Rite of Passage\t97\tThe Disciple\txlb\tDemonhide Boots\t7\t39\t29\tlblu\tlblu\t\t\t\t\t\t5\t5000\t\tac\t\t25\t25\tmove3\t\t30\t30\thalf-freeze\t\t1\t1\tstam\t\t15\t25\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Spiritual Custodian\t98\tThe Disciple\tuui\tDusk Shroud\t7\t39\t43\tlblu\tlblu\t\t\t\t\t\t5\t5000\t\tac\t\t305\t415\tres-fire\t\t24\t24\tgethit-skill\t48\t25\t3\tdmg-pois\t50\t125\t175\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Credendum\t99\tThe Disciple\tumc\tMithril Coil\t7\t39\t65\tlblu\tlblu\t\t\t\t\t\t5\t5000\t\tac\t\t50\t50\tstr\t\t10\t10\tdex\t\t10\t10\tres-all\t\t15\t15\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Dangoon's Teaching\t100\tHeaven's Brethren\t7ma\tReinforced Mace\t7\t55\t68\t\t\t\t\t\t\t\t5\t5000\t\tdmg/lvl\t12\t\t\tswing3\t\t40\t40\thit-skill\t44\t10\t3\tdmg-fire\t\t20\t30\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Heaven's Taebaek\t101\tHeaven's Brethren\tuts\tWard\t7\t55\t81\t\t\t\t\t\t\t\t5\t5000\t\tac\t\t50\t50\tmana\t\t100\t100\tres-ltng\t\t30\t30\tthorns\t\t30\t30\tindestruct\t\t1\t1\tblock\t\t25\t25\tblock3\t\t30\t30\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Haemosu's Adament\t102\tHeaven's Brethren\txrs\tCuirass\t7\t55\t44\t\t\t\t\t\t\t\t5\t5000\t\tac\t\t500\t500\tac-miss\t\t35\t35\thp\t\t75\t75\tac-hth\t\t40\t40\tease\t\t-20\t-20\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Ondal's Almighty\t103\tHeaven's Brethren\tuhm\tSpired Helm\t7\t55\t69\t\t\t\t\t\t\t\t5\t5000\t\tac\t\t50\t50\tease\t\t-40\t-40\thit-skill\t72\t10\t3\tstr\t\t10\t10\tdex\t\t15\t15\tbalance3\t\t24\t24\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Guillaume's Face\t104\tOrphan's Call\txhm\tWinged Helm\t7\t41\t34\tlgry\tlgry\t\t\t\t\t\t5\t5000\t\tac%\t\t120\t120\tbalance3\t\t30\t30\tcrush\t\t35\t35\tdeadly\t\t15\t15\tstr\t\t15\t15\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Wilhelm's Pride\t105\tOrphan's Call\tztb\tBattle Belt\t7\t41\t42\tlgry\tlgry\t\t\t\t\t\t5\t5000\t\tac%\t\t75\t75\tmanasteal\t\t5\t5\tres-cold\t\t10\t10\tlifesteal\t\t5\t5\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Magnus' Skin\t106\tOrphan's Call\txvg\tSharkskin Gloves\t7\t41\t37\tlgry\tlgry\t\t\t\t\t\t5\t5000\t\tac%\t\t50\t50\tres-fire\t\t15\t15\tswing2\t\t20\t20\tlight\t\t3\t3\tatt\t\t100\t100\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Wihtstan's Guard\t107\tOrphan's Call\txml\tRound Shield\t7\t41\t29\tlgry\tlgry\t\t\t\t\t\t5\t5000\t\tac%\t\t175\t175\tblock3\t\t40\t40\tblock\t\t55\t55\thalf-freeze\t\t1\t1\tlight\t\t5\t5\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Hwanin's Splendor\t108\tHwanin's Majesty\txrn\tGrand Crown\t7\t28\t45\t\t\t\t\t\t\t\t5\t5000\t\tregen\t\t20\t20\tred-mag\t\t10\t10\tres-cold\t\t37\t37\tac%\t\t100\t100\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Hwanin's Refuge\t109\tHwanin's Majesty\txcl\tTigulated Mail\t7\t28\t30\t\t\t\t\t\t\t\t5\t5000\t\tac\t\t200\t200\tres-pois\t\t27\t27\thp\t\t100\t100\tgethit-skill\t42\t10\t3\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Hwanin's Seal\t110\tHwanin's Majesty\tmbl\tBelt\t7\t28\t35\t\t\t\t\t\t\t\t5\t5000\t\tdmg-ltng\t\t3\t33\tnoheal\t\t1\t1\tac/lvl\t12\t\t\tdmg-to-mana\t\t12\t12\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Hwanin's Justice\t111\tHwanin's Majesty\t9vo\tBill\t7\t28\t28\t\t\t\t\t\t\t\t5\t5000\t\tatt\t\t330\t330\tindestruct\t\t1\t1\thit-skill\t45\t10\t3\tswing3\t\t40\t40\tdmg%\t\t200\t200\tdmg-ltng\t\t5\t25\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Sazabi's Cobalt Redeemer\t112\tSazabi's Grand Tribute\t7ls\tCryptic Sword\t7\t34\t73\tdblu\tdblu\t\t\t\t\t\t5\t5000\t\tdmg%\t\t150\t150\tdmg-cold\t50\t25\t35\tswing3\t\t40\t40\tdmg-demon\t\t318\t318\tindestruct\t\t1\t1\tdex\t\t15\t15\tstr\t\t5\t5\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Sazabi's Ghost Liberator\t113\tSazabi's Grand Tribute\tupl\tBalrog Skin\t7\t34\t67\tdblu\tdblu\t\t\t\t\t\t5\t5000\t\tac\t\t400\t400\tbalance3\t\t30\t30\tstr\t\t25\t25\tatt-demon\t\t300\t300\thp\t\t50\t75\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Sazabi's Mental Sheath\t114\tSazabi's Grand Tribute\txhl\tBasinet\t7\t34\t43\tdblu\tdblu\t\t\t\t\t\t5\t5000\t\tac\t\t100\t100\tallskills\t\t1\t1\tres-fire\t\t15\t20\tres-ltng\t\t15\t20\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Bul-Kathos' Sacred Charge\t115\tBul-Kathos' Children\t7gd\tColossus Blade\t7\t50\t61\tdgrn\tdgrn\t\t\t\t\t\t5\t5000\t\tcrush\t\t35\t35\tres-all\t\t20\t20\tswing2\t\t20\t20\tdmg%\t\t200\t200\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Bul-Kathos' Tribal Guardian\t116\tBul-Kathos' Children\t7wd\tMythical Sword\t7\t50\t54\tdgrn\tdgrn\t\t\t\t\t\t5\t5000\t\tres-fire\t\t50\t50\tdmg-pois\t50\t255\t255\tswing2\t\t20\t20\tstr\t\t20\t20\tdmg%\t\t200\t200\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Cow King's Horns\t117\tCow King's Leathers\txap\tWar Hat\t7\t20\t25\t\t\t\t\t\t\t\t5\t5000\t\tac\t\t75\t75\thalf-freeze\t\t1\t1\tdmg-to-mana\t\t35\t35\tthorns\t\t10\t10\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Cow King's Hide\t118\tCow King's Leathers\tstu\tStudded Leather\t7\t20\t18\t\t\t\t\t\t\t\t5\t5000\t\tres-all\t\t18\t18\tac%\t\t60\t60\thp\t\t30\t30\tgethit-skill\t53\t18\t5\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Cow King's Hoofs\t119\tCow King's Leathers\tvbt\tHeavy Boots\t7\t20\t13\t\t\t\t\t\t\t\t5\t5000\t\tac\t\t25\t35\tmove3\t\t30\t30\tmag%\t\t25\t25\tdex\t\t20\t20\tdmg-fire\t\t25\t35\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Naj's Puzzler\t120\tNaj's Ancient Set\t6cs\tElder Staff\t7\t43\t78\t\t\t\t\t\t\t\t5\t5000\t\tenr\t\t35\t35\tdmg%\t\t150\t150\tcharged\t54\t69\t11\tcast3\t\t30\t30\tdmg-ltng\t\t6\t45\tmana\t\t70\t70\tallskills\t\t1\t1\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Naj's Light Plate\t121\tNaj's Ancient Set\tult\tHellforge Plate\t7\t43\t71\t\t\t\t\t\t\t\t5\t5000\t\tease\t\t-60\t-60\thp\t\t65\t65\tres-all\t\t25\t25\tdmg-to-mana\t\t45\t45\tallskills\t\t1\t1\tac\t\t300\t300\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"Naj's Circlet\t122\tNaj's Ancient Set\tci0\tCirclet\t7\t43\t28\t\t\t\t\t\t\t\t5\t5000\t\tac\t\t75\t75\tdmg-fire\t\t25\t35\tlight\t\t5\t5\tstr\t\t15\t15\tgethit-skill\t53\t12\t5\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"McAuley's Paragon\t123\tMcAuley's Folly\tcap\tCap\t3\t20\t25\tlpur\tlpur\t\t\t\t\t\t5\t5000\t\tmag%\t\t35\t35\tthorns\t\t8\t8\tac/lvl\t8\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"McAuley's Riprap\t124\tMcAuley's Folly\tvbt\tHeavy Boots\t7\t20\t20\tlpur\tlpur\t\t\t\t\t\t5\t5000\t\tmove3\t\t40\t40\tatt\t\t100\t100\tstr\t\t5\t5\tdex\t\t10\t10\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"McAuley's Taboo\t125\tMcAuley's Folly\tvgl\tHeavy Gloves\t7\t20\t28\tlpur\tlpur\t\t\t\t\t\t5\t5000\t\tac\t\t20\t25\tswing2\t\t20\t20\thp\t\t40\t40\tdmg-pois\t75\t30\t36\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                ss << u8"McAuley's Superstition\t126\tMcAuley's Folly\tbwn\tBone Wand\t7\t20\t25\tlpur\tlpur\t\t\t\t\t\t5\t5000\t\tdmg%\t2\t75\t75\tmana\t\t25\t25\tmanasteal\t\t8\t8\tcast3\t\t20\t20\tdmg-cold\t50\t25\t75\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0\n";
                defaultTxt = ss.str();
            }
            return defaultTxt;
        }
    }
}