//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by D2Editor.rc
//
#define IDOK2                           3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_D2EDITOR_DIALOG             102
#define IDS_OLD_APP_TITLE               102
#define IDR_MAINFRAME                   128
#define IDB_CHAR_BITMAP                 131
#define IDB_QUEST_BITMAP                133
#define IDB_SKILL_BITMAP                134
#define IDB_EXIT_BITMAP                 135
#define IDB_WAYPOINT_BITMAP             137
#define IDB_STATS_BITMAP                138
#define IDD_D2LEVELINFO_DIALOG          140
#define IDD_WAYPOINTS_DIALOG            142
#define IDD_QUESTS_DIALOG               143
#define IDD_AMAZON_SKILLS_DIALOG        144
#define IDD_SKILLS_DIALOG               144
#define IDD_GPS_CONVERTER_DIALOG        147
#define IDB_STATS_LEFT_BITMAP           152
#define IDD_MERC_DIALOG                 153
#define IDR_RESOURCE_HEADER             154
#define IDD_ITEMS_DIALOG                155
#define IDD_ADD_GPS_DIALOG              156
#define IDB_INVQLT                      157
#define IDD_SHARED_STASH_DIALOG         157
#define IDB_INVLEA                      158
#define IDD_RUNEWORD_DIALOG             158
#define IDB_INVHLA                      159
#define IDB_INVSTU                      160
#define IDB_INVRNG                      161
#define IDB_INVSCL                      162
#define IDB_INVCHN                      163
#define IDB_INVBRS                      164
#define IDB_INVSPL                      165
#define IDB_INVPLT                      166
#define IDB_INVFLD                      167
#define IDB_INVGTH                      168
#define IDB_INVFUL                      169
#define IDB_INVAAR                      170
#define IDB_INVLTP                      171
#define IDB_INVLBT                      172
#define IDB_INVVBT                      173
#define IDB_INVMBT                      174
#define IDB_INVTBT                      175
#define IDB_INVHBT                      176
#define IDB_INVLGL                      178
#define IDB_INVVGL                      179
#define IDB_INVMGL                      180
#define IDB_INVTGL                      181
#define IDB_INVHGL                      182
#define IDB_INVCAP                      183
#define IDB_INVSKP                      184
#define IDB_INVHLM                      185
#define IDB_INVFHL                      186
#define IDB_INVGHM                      187
#define IDB_INVCRN                      188
#define IDB_INVMSK                      189
#define IDB_INVBHM                      190
#define IDB_INVBA1                      191
#define IDB_INVBA2                      192
#define IDB_INVBA3                      193
#define IDB_INVBA4                      194
#define IDB_INVBA5                      195
#define IDB_INVCI0                      196
#define IDB_INVCI1                      197
#define IDB_INVCI2                      198
#define IDB_INVCI3                      199
#define IDB_INVDR1                      200
#define IDB_INVDR2                      201
#define IDB_INVDR3                      202
#define IDB_INVDR5                      203
#define IDB_INVDR4                      204
#define IDB_INVLBL                      205
#define IDB_INVVBL                      206
#define IDB_INVMBL                      207
#define IDB_INVTBL                      208
#define IDB_INVHBL                      209
#define IDB_INVBUC                      210
#define IDB_INVSML                      211
#define IDB_INVLRG                      212
#define IDB_INVKIT                      213
#define IDB_INVTOW                      214
#define IDB_INVGTS                      215
#define IDB_INVBSH                      216
#define IDB_INVSPK                      217
#define IDB_INVNE1                      218
#define IDB_INVNE2                      219
#define IDB_INVNE3                      220
#define IDB_INVNE4                      221
#define IDB_INVNE5                      222
#define IDB_INVPA1                      223
#define IDB_INVPA2                      224
#define IDB_INVPA3                      225
#define IDB_INVPA4                      226
#define IDB_INVPA5                      227
#define IDB_INVHAX                      228
#define IDB_INVAXE                      229
#define IDB_INV2AX                      230
#define IDB_INVMPI                      231
#define IDB_INVWAX                      232
#define IDB_INVLAX                      233
#define IDB_INVBRX                      234
#define IDB_INVBTX                      235
#define IDB_INVGAX                      236
#define IDB_INVGIX                      237
#define IDB_INVWND                      238
#define IDB_INVYWN                      239
#define IDB_INVBWN                      240
#define IDB_INVGWN                      241
#define IDB_INVCLB                      242
#define IDB_INVSPC                      243
#define IDB_INVMAC                      244
#define IDB_INVMST                      245
#define IDB_INVFLA                      246
#define IDB_INVWHM                      247
#define IDB_INVMAU                      248
#define IDB_INVGMA                      249
#define IDB_INVSCP                      250
#define IDB_INVGSC                      251
#define IDB_INVWSP                      252
#define IDB_INVSSD                      253
#define IDB_INVSCM                      254
#define IDB_INVSBR                      255
#define IDB_INVFLC                      256
#define IDB_INVCRS                      257
#define IDB_INVBSD                      258
#define IDB_INVLSD                      259
#define IDB_INVWSD                      260
#define IDB_INV2HS                      261
#define IDB_INVCLM                      262
#define IDB_INVGIS                      263
#define IDB_INVBSW                      264
#define IDB_INVFLB                      265
#define IDB_INVGSD                      266
#define IDB_INVDGR                      267
#define IDB_INVDIR                      268
#define IDB_INVKRS                      269
#define IDB_INVBLD                      270
#define IDB_INVTKN                      271
#define IDB_INVTAX                      272
#define IDB_INVBKF                      273
#define IDB_INVBAL                      274
#define IDB_INVJAV                      275
#define IDB_INVPIL                      276
#define IDB_INVSSP                      277
#define IDB_INVGLV                      278
#define IDB_INVTSP                      279
#define IDB_INVSPR                      280
#define IDB_INVTRI                      281
#define IDB_INVBRN                      282
#define IDB_INVSPT                      283
#define IDB_INVPIK                      284
#define IDB_INVBAR                      285
#define IDB_INVVOU                      286
#define IDB_INVSCY                      287
#define IDB_INVPAX                      288
#define IDB_INVHAL                      289
#define IDB_INVWSC                      290
#define IDB_INVSST                      291
#define IDB_INVLST                      292
#define IDB_INVCST                      293
#define IDB_INVBST                      294
#define IDB_INVWST                      295
#define IDB_INVSBW                      296
#define IDB_INVHBW                      297
#define IDB_INVLBW                      298
#define IDB_INVCBW                      299
#define IDB_INVSBB                      300
#define IDB_INVLBB                      301
#define IDB_INVSWB                      302
#define IDB_INVLWB                      303
#define IDB_INVLXB                      304
#define IDB_INVMXB                      305
#define IDB_INVHXB                      306
#define IDB_INVRXB                      307
#define IDB_INVGPL                      308
#define IDB_INVOPL                      309
#define IDB_INVGPM                      310
#define IDB_INVOPM                      311
#define IDB_INVGPS                      312
#define IDB_INVOPS                      313
#define IDB_INVD33                      314
#define IDB_INVG33                      315
#define IDB_INVLEG                      316
#define IDB_INVHMR                      317
#define IDB_INVHFH                      318
#define IDB_INVHST                      319
#define IDB_INVMSF                      320
#define IDB_INVQF1                      321
#define IDB_INVQF2                      322
#define IDB_INVKTR                      323
#define IDB_INVAXF                      324
#define IDB_INVCLW                      325
#define IDB_INVSKR                      326
#define IDB_INVOB1                      328
#define IDB_INVOB2                      329
#define IDB_INVOB3                      330
#define IDB_INVOB4                      331
#define IDB_INVOB5                      332
#define IDB_INVAM1                      333
#define IDB_INVAM2                      334
#define IDB_INVAM3                      335
#define IDB_INVAM4                      336
#define IDB_INVAM5                      337
#define IDB_INVJBI                      339
#define IDB_INVGSVC                     340
#define IDB_INVRAMN                     341
#define IDB_INVAMU                      342
#define IDB_INVNPS                      343
#define IDB_INVQVR                      344
#define IDB_INVRBER                     345
#define IDB_INVCQV                      346
#define IDB_INVSBK                      347
#define IDB_INVRCHAM                    350
#define IDB_INVGSVA                     351
#define IDB_INVGSWA                     352
#define IDB_INVGSGA                     353
#define IDB_INVGSRA                     354
#define IDB_INVGSBA                     355
#define IDB_INVSKC                      356
#define IDB_INVGSYA                     357
#define IDB_INVGSWC                     358
#define IDB_INVRDOL                     359
#define IDB_INVREL                      360
#define IDB_INVRELD                     361
#define IDB_INVPOT                      362
#define IDB_INVGSGC                     363
#define IDB_INVRETH                     364
#define IDB_INVRFAL                     365
#define IDB_INVGSVB                     366
#define IDB_INVGSWB                     367
#define IDB_INVGSGB                     368
#define IDB_INVGSBB                     369
#define IDB_INVSKF                      370
#define IDB_INVGSYB                     371
#define IDB_INVGSRB                     372
#define IDB_INVGSVD                     373
#define IDB_INVGSWD                     374
#define IDB_INVGSGD                     375
#define IDB_INVGSRD                     376
#define IDB_INVGSBD                     377
#define IDB_INVSKL                      378
#define IDB_INVGSYD                     379
#define IDB_INVVPL                      380
#define IDB_INVGLD                      381
#define IDB_INVCHM3                     382
#define IDB_INVHP4                      383
#define IDB_INVMP4                      384
#define IDB_INVRGUL                     385
#define IDB_INVHP3                      386
#define IDB_INVRPS                      386
#define IDB_INVRHEL                     387
#define IDB_INVHRB                      388
#define IDB_INVBOX                      389
#define IDB_INVHSCR                     390
#define IDB_INVRIO                      393
#define IDB_INVRIST                     394
#define IDB_INVRITH                     395
#define IDB_INVRJO                      396
#define IDB_INVJEW                      397
#define IDB_INVJEW_1                    398
#define IDB_INVKEY                      399
#define IDB_INVBRNZ                     400
#define IDB_INVEAR                      401
#define IDB_INVEYE                      402
#define IDB_INVHRT                      403
#define IDB_INVRKO                      404
#define IDB_INVBBB                      405
#define IDB_INVCHM2                     406
#define IDB_INVRLEM                     407
#define IDB_INVHP2                      408
#define IDB_INVMP2                      409
#define IDB_INVRLO                      410
#define IDB_INVRLUM                     411
#define IDB_INVRMAL                     412
#define IDB_INVJEW_2                    413
#define IDB_INVMP3                      414
#define IDB_INVBPS                      414
#define IDB_INVMSS                      415
#define IDB_INVHP1                      416
#define IDB_INVMP1                      417
#define IDB_INVBPL                      418
#define IDB_INVJEW_3                    419
#define IDB_INVRNEF                     420
#define IDB_INVROHM                     421
#define IDB_INVRORT                     422
#define IDB_INVGSVE                     423
#define IDB_INVGSWE                     424
#define IDB_INVGSGE                     425
#define IDB_INVGSRE                     426
#define IDB_INVGSBE                     427
#define IDB_INVSKZ                      428
#define IDB_INVGSYE                     429
#define IDB_INVXYZ                      430
#define IDB_INVRPUL                     431
#define IDB_INVRRAL                     432
#define IDB_INVVPS                      433
#define IDB_INVRIN                      434
#define IDB_INVRPL                      435
#define IDB_INVJEW_4                    436
#define IDB_INVGSRC                     437
#define IDB_INVGSBC                     438
#define IDB_INVRSC                      439
#define IDB_INVSCB                      440
#define IDB_INVJEW_5                    441
#define IDB_INVBSC                      443
#define IDB_INVRSHAE                    444
#define IDB_INVFANG                     447
#define IDB_INVFLAG                     448
#define IDB_INVSKU                      457
#define IDB_INVCHM1                     458
#define IDB_INVRSOL                     459
#define IDB_INVWPS                      460
#define IDB_INVHP5                      461
#define IDB_INVMP5                      462
#define IDB_INVRSUR                     463
#define IDB_INVRTAL                     464
#define IDB_INVYPS                      465
#define IDB_INVMPH                      466
#define IDB_INVGBI                      467
#define IDB_INVRTHUL                    468
#define IDB_INVRTIR                     469
#define IDB_INVTOA                      470
#define IDB_INVRBK                      471
#define IDB_INVBBK                      472
#define IDB_INVVIP                      473
#define IDB_INVGSYC                     474
#define IDB_INVTRCH                     475
#define IDB_INVFED                      476
#define IDB_INVCEH                      477
#define IDB_INVTES                      478
#define IDB_INVBET                      479
#define IDB_INVRUM                      480
#define IDB_INVRVEX                     481
#define IDB_INVRZOD                     482
#define IDB_INVEMPTY                    483
#define IDB_INV_ARMOR                   484
#define IDB_INV_BELT                    485
#define IDB_INV_FEET                    486
#define IDB_INV_HELM_GLOVES_0_0         487
#define IDB_INV_HELM_GLOVES_0_1         488
#define IDB_INV_RING_AMULET_0_0         489
#define IDB_INV_RING_AMULET_0_1         490
#define IDB_INV_WEAPONS                 491
#define IDR_ITEM_MENU                   492
#define IDB_INV_EMPTY_SOCKET            493
#define IDB_INVRIN_1                    494
#define IDB_INVRIN_2                    495
#define IDB_INVRIN_3                    496
#define IDB_INVRIN_4                    497
#define IDB_INVAMU_1                    498
#define IDB_INVAMU_2                    499
#define IDB_INVHORN                     500
#define IDB_INVJAW                      501
#define IDB_INVTAIL                     502
#define IDB_INVQUIL                     503
#define IDB_INVSOL                      504
#define IDB_INVSPLE                     505
#define IDB_INVCHM1_1                   506
#define IDB_INVCHM1_2                   507
#define IDB_INVCHM2_1                   508
#define IDB_INVCHM2_2                   509
#define IDB_INVCHM3_1                   510
#define IDB_INVCHM3_2                   511
#define IDB_SKILL_AMA00                 512
#define IDB_SKILL_AMA02                 513
#define IDB_SKILL_AMA04                 514
#define IDB_SKILL_AMA06                 515
#define IDB_SKILL_AMA08                 516
#define IDB_SKILL_AMA10                 517
#define IDB_SKILL_AMA12                 518
#define IDB_SKILL_AMA14                 519
#define IDB_SKILL_AMA16                 520
#define IDB_SKILL_AMA18                 521
#define IDB_SKILL_AMA20                 522
#define IDB_SKILL_AMA22                 523
#define IDB_SKILL_AMA24                 524
#define IDB_SKILL_AMA26                 525
#define IDB_SKILL_AMA28                 526
#define IDB_SKILL_AMA30                 527
#define IDB_SKILL_AMA32                 528
#define IDB_SKILL_AMA34                 529
#define IDB_SKILL_AMA36                 530
#define IDB_SKILL_AMA38                 531
#define IDB_SKILL_AMA40                 532
#define IDB_SKILL_AMA42                 533
#define IDB_SKILL_AMA44                 534
#define IDB_SKILL_AMA46                 535
#define IDB_SKILL_AMA48                 536
#define IDB_SKILL_AMA50                 537
#define IDB_SKILL_AMA52                 538
#define IDB_SKILL_AMA54                 539
#define IDB_SKILL_AMA56                 540
#define IDB_SKILL_AMA58                 541
#define IDB_SKILL_ASS00                 542
#define IDB_SKILL_ASS02                 543
#define IDB_SKILL_ASS04                 544
#define IDB_SKILL_ASS06                 545
#define IDB_SKILL_ASS08                 546
#define IDB_SKILL_ASS10                 547
#define IDB_SKILL_ASS12                 548
#define IDB_SKILL_ASS14                 549
#define IDB_SKILL_ASS16                 550
#define IDB_SKILL_ASS18                 551
#define IDB_SKILL_ASS20                 552
#define IDB_SKILL_ASS22                 553
#define IDB_SKILL_ASS24                 554
#define IDB_SKILL_ASS26                 555
#define IDB_SKILL_ASS28                 556
#define IDB_SKILL_ASS30                 557
#define IDB_SKILL_ASS32                 558
#define IDB_SKILL_ASS34                 559
#define IDB_SKILL_ASS36                 560
#define IDB_SKILL_ASS38                 561
#define IDB_SKILL_ASS40                 562
#define IDB_SKILL_ASS42                 563
#define IDB_SKILL_ASS44                 564
#define IDB_SKILL_ASS46                 565
#define IDB_SKILL_ASS48                 566
#define IDB_SKILL_ASS50                 567
#define IDB_SKILL_ASS52                 568
#define IDB_SKILL_ASS54                 569
#define IDB_SKILL_ASS56                 570
#define IDB_SKILL_ASS58                 571
#define IDB_SKILL_BAR00                 572
#define IDB_SKILL_BAR02                 573
#define IDB_SKILL_BAR04                 574
#define IDB_SKILL_BAR06                 575
#define IDB_SKILL_BAR08                 576
#define IDB_SKILL_BAR10                 577
#define IDB_SKILL_BAR12                 578
#define IDB_SKILL_BAR14                 579
#define IDB_SKILL_BAR16                 580
#define IDB_SKILL_BAR18                 581
#define IDB_SKILL_BAR20                 582
#define IDB_SKILL_BAR22                 583
#define IDB_SKILL_BAR24                 584
#define IDB_SKILL_BAR26                 585
#define IDB_SKILL_BAR28                 586
#define IDB_SKILL_BAR30                 587
#define IDB_SKILL_BAR32                 588
#define IDB_SKILL_BAR34                 589
#define IDB_SKILL_BAR36                 590
#define IDB_SKILL_BAR38                 591
#define IDB_SKILL_BAR40                 592
#define IDB_SKILL_BAR42                 593
#define IDB_SKILL_BAR44                 594
#define IDB_SKILL_BAR46                 595
#define IDB_SKILL_BAR48                 596
#define IDB_SKILL_BAR50                 597
#define IDB_SKILL_BAR52                 598
#define IDB_SKILL_BAR54                 599
#define IDB_SKILL_BAR56                 600
#define IDB_SKILL_BAR58                 601
#define IDB_SKILL_DRU00                 602
#define IDB_SKILL_DRU02                 603
#define IDB_SKILL_DRU04                 604
#define IDB_SKILL_DRU06                 605
#define IDB_SKILL_DRU08                 606
#define IDB_SKILL_DRU10                 607
#define IDB_SKILL_DRU12                 608
#define IDB_SKILL_DRU14                 609
#define IDB_SKILL_DRU16                 610
#define IDB_SKILL_DRU18                 611
#define IDB_SKILL_DRU20                 612
#define IDB_SKILL_DRU22                 613
#define IDB_SKILL_DRU24                 614
#define IDB_SKILL_DRU26                 615
#define IDB_SKILL_DRU28                 616
#define IDB_SKILL_DRU30                 617
#define IDB_SKILL_DRU32                 618
#define IDB_SKILL_DRU34                 619
#define IDB_SKILL_DRU36                 620
#define IDB_SKILL_DRU38                 621
#define IDB_SKILL_DRU40                 622
#define IDB_SKILL_DRU42                 623
#define IDB_SKILL_DRU44                 624
#define IDB_SKILL_DRU46                 625
#define IDB_SKILL_DRU48                 626
#define IDB_SKILL_DRU50                 627
#define IDB_SKILL_DRU52                 628
#define IDB_SKILL_DRU54                 629
#define IDB_SKILL_DRU56                 630
#define IDB_SKILL_DRU58                 631
#define IDB_SKILL_NEC00                 632
#define IDB_SKILL_NEC02                 633
#define IDB_SKILL_NEC04                 634
#define IDB_SKILL_NEC06                 635
#define IDB_SKILL_NEC08                 636
#define IDB_SKILL_NEC10                 637
#define IDB_SKILL_NEC12                 638
#define IDB_SKILL_NEC14                 639
#define IDB_SKILL_NEC16                 640
#define IDB_SKILL_NEC18                 641
#define IDB_SKILL_NEC20                 642
#define IDB_SKILL_NEC22                 643
#define IDB_SKILL_NEC24                 644
#define IDB_SKILL_NEC26                 645
#define IDB_SKILL_NEC28                 646
#define IDB_SKILL_NEC30                 647
#define IDB_SKILL_NEC32                 648
#define IDB_SKILL_NEC34                 649
#define IDB_SKILL_NEC36                 650
#define IDB_SKILL_NEC38                 651
#define IDB_SKILL_NEC40                 652
#define IDB_SKILL_NEC42                 653
#define IDB_SKILL_NEC44                 654
#define IDB_SKILL_NEC46                 655
#define IDB_SKILL_NEC48                 656
#define IDB_SKILL_NEC50                 657
#define IDB_SKILL_NEC52                 658
#define IDB_SKILL_NEC54                 659
#define IDB_SKILL_NEC56                 660
#define IDB_SKILL_NEC58                 661
#define IDB_SKILL_PAL00                 662
#define IDB_SKILL_PAL02                 663
#define IDB_SKILL_PAL04                 664
#define IDB_SKILL_PAL06                 665
#define IDB_SKILL_PAL08                 666
#define IDB_SKILL_PAL10                 667
#define IDB_SKILL_PAL12                 668
#define IDB_SKILL_PAL14                 669
#define IDB_SKILL_PAL16                 670
#define IDB_SKILL_PAL18                 671
#define IDB_SKILL_PAL20                 672
#define IDB_SKILL_PAL22                 673
#define IDB_SKILL_PAL24                 674
#define IDB_SKILL_PAL26                 675
#define IDB_SKILL_PAL28                 676
#define IDB_SKILL_PAL30                 677
#define IDB_SKILL_PAL32                 678
#define IDB_SKILL_PAL34                 679
#define IDB_SKILL_PAL36                 680
#define IDB_SKILL_PAL38                 681
#define IDB_SKILL_PAL40                 682
#define IDB_SKILL_PAL42                 683
#define IDB_SKILL_PAL44                 684
#define IDB_SKILL_PAL46                 685
#define IDB_SKILL_PAL48                 686
#define IDB_SKILL_PAL50                 687
#define IDB_SKILL_PAL52                 688
#define IDB_SKILL_PAL54                 689
#define IDB_SKILL_PAL56                 690
#define IDB_SKILL_PAL58                 691
#define IDB_SKILL_SOR00                 692
#define IDB_SKILL_SOR02                 693
#define IDB_SKILL_SOR04                 694
#define IDB_SKILL_SOR06                 695
#define IDB_SKILL_SOR08                 696
#define IDB_SKILL_SOR10                 697
#define IDB_SKILL_SOR12                 698
#define IDB_SKILL_SOR14                 699
#define IDB_SKILL_SOR16                 700
#define IDB_SKILL_SOR18                 701
#define IDB_SKILL_SOR20                 702
#define IDB_SKILL_SOR22                 703
#define IDB_SKILL_SOR24                 704
#define IDB_SKILL_SOR26                 705
#define IDB_SKILL_SOR28                 706
#define IDB_SKILL_SOR30                 707
#define IDB_SKILL_SOR32                 708
#define IDB_SKILL_SOR34                 709
#define IDB_SKILL_SOR36                 710
#define IDB_SKILL_SOR38                 711
#define IDB_SKILL_SOR40                 712
#define IDB_SKILL_SOR42                 713
#define IDB_SKILL_SOR44                 714
#define IDB_SKILL_SOR46                 715
#define IDB_SKILL_SOR48                 716
#define IDB_SKILL_SOR50                 717
#define IDB_SKILL_SOR52                 718
#define IDB_SKILL_SOR54                 719
#define IDB_SKILL_SOR56                 720
#define IDB_SKILL_SOR58                 721
#define IDB_SKILL_UNK                   722
#define IDR_HIRELING_TXT                723
#define IDC_TRASH_CURSOR                724
#define IDD_NEW_ITEM_DIALOG             725
#define IDD_MAGICAL_AFFIXES_DIALOG      727
#define IDD_RARE_AFFIXES_DIALOG         728
#define IDD_EAR_DIALOG                  729
#define IDD_RARE_AFFIXES_V100_DIALOG    730
#define IDC_DIFFICULTY                  1000
#define IDC_CHAR_NAME                   1001
#define IDC_CHAR_LEVEL                  1002
#define IDC_CHAR_STRENGTH               1003
#define IDC_CHAR_ENERGY                 1004
#define IDC_CHAR_DEXTERITY              1005
#define IDC_CHAR_VITALITY               1006
#define IDC_CUR_LIFE                    1007
#define IDC_MAX_LIFE                    1008
#define IDC_CUR_MANA                    1009
#define IDC_MAX_MANA                    1010
#define IDC_CUR_STAMINA                 1011
#define IDC_MAX_STAMINA                 1012
#define IDC_CHAR_EXPERIENCE             1013
#define IDC_WAYPOINTS_BTN               1015
#define IDC_EDIT_SKILLS_BTN             1016
#define IDC_QUESTS_BTN                  1017
#define IDC_CHAR_CLASS_CMB              1018
#define IDC_CHAR_NEXT_EXPERIENCE        1019
#define IDC_STARTING_ACT_CMB            1020
#define IDC_CHAR_TITLE_CMB              1021
#define IDC_MAX_ALL_BTN                 1022
#define IDC_GOLD_IN_BELT                1023
#define IDC_GOLD_IN_STASH               1024
#define IDC_STATS_LEFT                  1025
#define IDC_HARDCORE_CHECK              1027
#define IDC_RESURRECTED_CHECK           1028
#define IDC_EXPANSION_CHECK             1029
#define IDC_LADDER_CHECK                1030
#define IDC_ATTRIBUTE                   1031
#define IDC_RUNEWORD_LIST               1031
#define IDC_ITEM_TREE                   1031
#define IDC_PREFIX1_COMBO               1031
#define IDC_QUIT_BTN                    1032
#define IDC_SUFFIX1_COMBO               1032
#define IDC_ETHEREAL_CHECK              1032
#define IDC_ABOUT_VERSION               1033
#define IDC_CHAR_DEFENSE                1033
#define IDC_QUALITY_COMBO               1033
#define IDC_PREFIX1_STATIC              1033
#define IDC_RUNEWORD_STATIC             1033
#define IDC_APP_COPYRIGHT               1034
#define IDC_CHAR_DAMAGE                 1034
#define IDC_QUALITY_STATIC              1034
#define IDC_SUFFIX1_STATIC              1034
#define IDC_TO_STATIC                   1034
#define IDC_LEVELINFO_GRID              1035
#define IDC_EDIT_SET_ALL_SKILLS         1035
#define IDC_CHAR_RESIST_FIRE            1035
#define IDC_PREFIX2_COMBO               1035
#define IDC_SOCKETS_EDIT                1035
#define IDC_RADIO_DIFFICULTY_NORMAL     1036
#define IDC_STATIC_TREE_1               1036
#define IDC_CHAR_RESIST_COLD            1036
#define IDC_SUFFIX2_COMBO               1036
#define IDC_SOCKETS_SPIN                1036
#define IDC_RADIO_DIFFICULTY_NIGHTMARE  1037
#define IDC_STATIC_TREE_2               1037
#define IDC_CHAR_RESIST_LIGHTNING       1037
#define IDC_PREFIX2_STATIC              1037
#define IDC_SOCKETS_STATIC              1037
#define IDC_RADIO_DIFFICULTY_HELL       1038
#define IDC_STATIC_TREE_3               1038
#define IDC_CHAR_RESIST_POISON          1038
#define IDC_SUFFIX2_STATIC              1038
#define IDC_MONSTERS_STATIC             1038
#define IDC_ACTIVATE_ALL                1039
#define IDC_COMPLETE_ALL                1039
#define IDC_SET_ALL_SKILLS              1039
#define IDC_PREFIX3_COMBO               1039
#define IDC_MONSTERS_COMBO              1039
#define IDC_CHECK_ACTI_1                1040
#define IDC_CHECK_ACTI_QUEST_1          1040
#define IDC_EDIT_TREE_1_ROW_1_COL_1     1040
#define IDC_STATIC_CHAR_NAME            1040
#define IDC_SUFFIX3_COMBO               1040
#define IDC_CHECK_ACTI_2                1041
#define IDC_CHECK_ACTI_QUEST_2          1041
#define IDC_EDIT_TREE_1_ROW_1_COL_2     1041
#define IDC_STATIC_CHAR_CLASS           1041
#define IDC_PREFIX3_STATIC              1041
#define IDC_CHECK_ACTI_3                1042
#define IDC_CHECK_ACTI_QUEST_3          1042
#define IDC_EDIT_TREE_1_ROW_1_COL_3     1042
#define IDC_STATIC_CHAR_LEVEL           1042
#define IDC_SUFFIX3_STATIC              1042
#define IDC_CHECK_ACTI_4                1043
#define IDC_CHECK_ACTI_QUEST_4          1043
#define IDC_EDIT_TREE_1_ROW_2_COL_1     1043
#define IDC_STATIC_CHAR_EXPERIENCE      1043
#define IDC_RARE_PREFIX_COMBO           1043
#define IDC_CHECK_ACTI_5                1044
#define IDC_CHECK_ACTI_QUEST_5          1044
#define IDC_EDIT_TREE_1_ROW_2_COL_2     1044
#define IDC_STATIC_CUR_LIFE             1044
#define IDC_RARE_SUFFIX_COMBO           1044
#define IDC_CHECK_ACTI_6                1045
#define IDC_CHECK_ACTI_QUEST_6          1045
#define IDC_EDIT_TREE_1_ROW_2_COL_3     1045
#define IDC_STATIC_CHAR_STRENGTH        1045
#define IDC_RARE_PREFIX_STATIC          1045
#define IDC_CHECK_ACTI_7                1046
#define IDC_CHECK_ACTII_QUEST_1         1046
#define IDC_EDIT_TREE_1_ROW_3_COL_1     1046
#define IDC_STATIC_CHAR_DEXTERITY       1046
#define IDC_RARE_SUFFIX_STATIC          1046
#define IDC_CHECK_ACTI_8                1047
#define IDC_CHECK_ACTII_QUEST_2         1047
#define IDC_EDIT_TREE_1_ROW_3_COL_2     1047
#define IDC_STATIC_CHAR_DAMAGE          1047
#define IDC_CHECK_ACTI_9                1048
#define IDC_CHECK_ACTII_QUEST_3         1048
#define IDC_EDIT_TREE_1_ROW_3_COL_3     1048
#define IDC_STATIC_CHAR_DEFENSE         1048
#define IDC_CHECK_ACTII_1               1049
#define IDC_CHECK_ACTII_QUEST_4         1049
#define IDC_EDIT_TREE_1_ROW_4_COL_1     1049
#define IDC_STATIC_CHAR_RESIST_FIRE     1049
#define IDC_CHECK_ACTII_2               1050
#define IDC_CHECK_ACTII_QUEST_5         1050
#define IDC_EDIT_TREE_1_ROW_4_COL_2     1050
#define IDC_STATIC_CHAR_RESIST_COLD     1050
#define IDC_CHECK_ACTII_3               1051
#define IDC_CHECK_ACTII_QUEST_6         1051
#define IDC_EDIT_TREE_1_ROW_4_COL_3     1051
#define IDC_STATIC_CHAR_RESIST_LIGHTNING 1051
#define IDC_TOOLTIP_RECT                1051
#define IDC_CHECK_ACTII_4               1052
#define IDC_CHECK_ACTIII_QUEST_1        1052
#define IDC_EDIT_TREE_1_ROW_5_COL_1     1052
#define IDC_STATIC_CHAR_RESIST_POISON   1052
#define IDC_GAMBLE_BUTTON               1052
#define IDC_CHECK_ACTII_5               1053
#define IDC_CHECK_ACTIII_QUEST_2        1053
#define IDC_EDIT_TREE_1_ROW_5_COL_2     1053
#define IDC_CHECK_ACTII_6               1054
#define IDC_CHECK_ACTIII_QUEST_3        1054
#define IDC_EDIT_TREE_1_ROW_5_COL_3     1054
#define IDC_CHECK_ACTII_7               1055
#define IDC_CHECK_ACTIII_QUEST_4        1055
#define IDC_EDIT_TREE_1_ROW_6_COL_1     1055
#define IDC_CHECK_ACTII_8               1056
#define IDC_CHECK_ACTIII_QUEST_5        1056
#define IDC_EDIT_TREE_1_ROW_6_COL_2     1056
#define IDC_CHECK_ACTII_9               1057
#define IDC_CHECK_ACTIII_QUEST_6        1057
#define IDC_EDIT_TREE_1_ROW_6_COL_3     1057
#define IDC_CHECK_ACTIII_1              1058
#define IDC_CHECK_ACTIV_QUEST_1         1058
#define IDC_EDIT_TREE_2_ROW_1_COL_1     1058
#define IDC_CHECK_ACTIII_2              1059
#define IDC_CHECK_ACTIV_QUEST_2         1059
#define IDC_EDIT_TREE_2_ROW_1_COL_2     1059
#define IDC_CHECK_ACTIII_3              1060
#define IDC_CHECK_ACTIV_QUEST_3         1060
#define IDC_EDIT_TREE_2_ROW_1_COL_3     1060
#define IDC_CHECK_ACTIII_4              1061
#define IDC_CHECK_ACTV_QUEST_1          1061
#define IDC_EDIT_TREE_2_ROW_2_COL_1     1061
#define IDC_CHECK_ACTIII_5              1062
#define IDC_CHECK_ACTV_QUEST_2          1062
#define IDC_EDIT_TREE_2_ROW_2_COL_2     1062
#define IDC_CHECK_ACTIII_6              1063
#define IDC_CHECK_ACTV_QUEST_3          1063
#define IDC_EDIT_TREE_2_ROW_2_COL_3     1063
#define IDC_CHECK_ACTIII_7              1064
#define IDC_CHECK_ACTV_QUEST_4          1064
#define IDC_EDIT_TREE_2_ROW_3_COL_1     1064
#define IDC_CHECK_ACTIII_8              1065
#define IDC_CHECK_ACTV_QUEST_5          1065
#define IDC_EDIT_TREE_2_ROW_3_COL_2     1065
#define IDC_CHECK_ACTIII_9              1066
#define IDC_CHECK_ACTV_QUEST_6          1066
#define IDC_EDIT_TREE_2_ROW_3_COL_3     1066
#define IDC_CHECK_ACTIV_1               1067
#define IDC_CHECK_QUEST_FARM            1067
#define IDC_EDIT_TREE_2_ROW_4_COL_1     1067
#define IDC_CHECK_ACTIV_2               1068
#define IDC_CHECK_ACTI_RESET_STATS      1068
#define IDC_EDIT_TREE_2_ROW_4_COL_2     1068
#define IDC_CHECK_ACTIV_3               1069
#define IDC_EDIT_TREE_2_ROW_4_COL_3     1069
#define IDC_CHECK_ACTV_1                1070
#define IDC_EDIT_TREE_2_ROW_5_COL_1     1070
#define IDC_CHECK_ACTV_2                1071
#define IDC_EDIT_TREE_2_ROW_5_COL_2     1071
#define IDC_CHECK_ACTV_3                1072
#define IDC_EDIT_TREE_2_ROW_5_COL_3     1072
#define IDC_CHECK_ACTV_4                1073
#define IDC_EDIT_TREE_2_ROW_6_COL_1     1073
#define IDC_CHECK_ACTV_5                1074
#define IDC_EDIT_TREE_2_ROW_6_COL_2     1074
#define IDC_CHECK_ACTV_6                1075
#define IDC_EDIT_TREE_2_ROW_6_COL_3     1075
#define IDC_CHECK_ACTV_7                1076
#define IDC_EDIT_TREE_3_ROW_1_COL_1     1076
#define IDC_CHECK_ACTV_8                1077
#define IDC_EDIT_TREE_3_ROW_1_COL_2     1077
#define IDC_CHECK_ACTV_9                1078
#define IDC_EDIT_TREE_3_ROW_1_COL_3     1078
#define IDC_EDIT_TREE_3_ROW_2_COL_1     1079
#define IDC_STATIC_ACTI                 1080
#define IDC_EDIT_TREE_3_ROW_2_COL_2     1080
#define IDC_STATIC_ACTII                1081
#define IDC_EDIT_TREE_3_ROW_2_COL_3     1081
#define IDC_STATIC_ACTIII               1082
#define IDC_EDIT_TREE_3_ROW_3_COL_1     1082
#define IDC_STATIC_ACTIV                1083
#define IDC_EDIT_TREE_3_ROW_3_COL_2     1083
#define IDC_STATIC_ACTV                 1084
#define IDC_EDIT_TREE_3_ROW_3_COL_3     1084
#define IDC_EDIT_TREE_3_ROW_4_COL_1     1085
#define IDC_EDIT_TREE_3_ROW_4_COL_2     1086
#define IDC_EDIT_TREE_3_ROW_4_COL_3     1087
#define IDC_EDIT_TREE_3_ROW_5_COL_1     1088
#define IDC_EDIT_TREE_3_ROW_5_COL_2     1089
#define IDC_EDIT_TREE_3_ROW_5_COL_3     1090
#define IDC_EDIT_TREE_3_ROW_6_COL_1     1091
#define IDC_EDIT_TREE_3_ROW_6_COL_2     1092
#define IDC_EDIT_TREE_3_ROW_6_COL_3     1093
#define IDC_BUTTON_TREE_1_ROW_1_COL_1   1094
#define IDC_BUTTON_TREE_1_ROW_1_COL_2   1095
#define IDC_BUTTON_TREE_1_ROW_1_COL_3   1096
#define IDC_BUTTON_TREE_1_ROW_2_COL_1   1097
#define IDC_BUTTON_TREE_1_ROW_2_COL_2   1098
#define IDC_BUTTON_TREE_1_ROW_2_COL_3   1099
#define IDC_FROM_COMBO                  1100
#define IDC_BUTTON_TREE_1_ROW_3_COL_1   1100
#define IDC_TO_COMBO                    1101
#define IDC_BUTTON_TREE_1_ROW_3_COL_2   1101
#define IDC_LOCATION_COMBO              1102
#define IDC_MFCLINK1                    1102
#define IDC_BUTTON_TREE_1_ROW_3_COL_3   1102
#define IDC_LOCATION_STATIC             1103
#define IDC_ENERGY_PLUS_BTN             1103
#define IDC_BUTTON_TREE_1_ROW_4_COL_1   1103
#define IDC_LOCATION_COMBO2             1103
#define IDC_VITALITY_PLUS_BTN           1104
#define IDC_BUTTON_TREE_1_ROW_4_COL_2   1104
#define IDC_STRENGTH_PLUS_BTN           1105
#define IDC_BUTTON_TREE_1_ROW_4_COL_3   1105
#define IDC_DEXTERITY_PLUS_BTN          1106
#define IDC_BUTTON_TREE_1_ROW_5_COL_1   1106
#define IDC_STATS_LEFT_IMAGE            1107
#define IDC_BUTTON_TREE_1_ROW_5_COL_2   1107
#define IDC_BACKGROUND_BOX              1108
#define IDC_BUTTON_TREE_1_ROW_5_COL_3   1108
#define IDC_MERC_HIRED                  1109
#define IDC_BUTTON_TREE_1_ROW_6_COL_1   1109
#define IDC_TYPE_DASH_2                 1110
#define IDC_BUTTON_TREE_1_ROW_6_COL_2   1110
#define IDC_INV_HEAD                    1111
#define IDC_BUTTON_TREE_1_ROW_6_COL_3   1111
#define IDC_INV_CORPSE_HEAD             1112
#define IDC_BUTTON_TREE_2_ROW_1_COL_1   1112
#define IDC_INV_MERC_HEAD               1113
#define IDC_BUTTON_TREE_2_ROW_1_COL_2   1113
#define IDC_INV_CORPSE_LEFT_ARM         1114
#define IDC_BUTTON_TREE_2_ROW_1_COL_3   1114
#define IDC_INV_LEFT_ARM                1115
#define IDC_BUTTON_TREE_2_ROW_2_COL_1   1115
#define IDC_INV_MERC_LEFT_ARM           1116
#define IDC_BUTTON_TREE_2_ROW_2_COL_2   1116
#define IDC_INV_TORSO                   1117
#define IDC_BUTTON_TREE_2_ROW_2_COL_3   1117
#define IDC_INV_CORPSE_TORSO            1118
#define IDC_BUTTON_TREE_2_ROW_3_COL_1   1118
#define IDC_INV_MERC_TORSO              1119
#define IDC_BUTTON_TREE_2_ROW_3_COL_2   1119
#define IDC_INV_RIGHT_ARM               1120
#define IDC_BUTTON_TREE_2_ROW_3_COL_3   1120
#define IDC_INV_CORPSE_RIGHT_ARM        1121
#define IDC_BUTTON_TREE_2_ROW_4_COL_1   1121
#define IDC_INV_MERC_RIGHT_ARM          1122
#define IDC_BUTTON_TREE_2_ROW_4_COL_2   1122
#define IDC_INV_NECK                    1123
#define IDC_BUTTON_TREE_2_ROW_4_COL_3   1123
#define IDC_INV_CORPSE_NECK             1124
#define IDC_BUTTON_TREE_2_ROW_5_COL_1   1124
#define IDC_INV_BELT                    1125
#define IDC_BUTTON_TREE_2_ROW_5_COL_2   1125
#define IDC_INV_CORPSE_BELT             1126
#define IDC_BUTTON_TREE_2_ROW_5_COL_3   1126
#define IDC_INV_FEET                    1127
#define IDC_BUTTON_TREE_2_ROW_6_COL_1   1127
#define IDC_INV_CORPSE_FEET             1128
#define IDC_BUTTON_TREE_2_ROW_6_COL_2   1128
#define IDC_INV_RIGHT_RING              1129
#define IDC_BUTTON_TREE_2_ROW_6_COL_3   1129
#define IDC_INV_CORPSE_RIGHT_RING       1130
#define IDC_BUTTON_TREE_3_ROW_1_COL_1   1130
#define IDC_INV_LEFT_RING               1131
#define IDC_BUTTON_TREE_3_ROW_1_COL_2   1131
#define IDC_INV_CORPSE_LEFT_RING        1132
#define IDC_BUTTON_TREE_3_ROW_1_COL_3   1132
#define IDC_INV_GLOVES                  1133
#define IDC_BUTTON_TREE_3_ROW_2_COL_1   1133
#define IDC_INV_CORPSE_GLOVES           1134
#define IDC_BUTTON_TREE_3_ROW_2_COL_2   1134
#define IDC_INV_GOLEM                   1135
#define IDC_BUTTON_TREE_3_ROW_2_COL_3   1135
#define IDC_INV_GRID                    1136
#define IDC_BUTTON_TREE_3_ROW_3_COL_1   1136
#define IDC_INV_STASH_GRID              1137
#define IDC_BUTTON_TREE_3_ROW_3_COL_2   1137
#define IDC_INV_CUBE_GRID               1138
#define IDC_BUTTON_TREE_3_ROW_3_COL_3   1138
#define IDC_INV_BELT_GRID               1139
#define IDC_BUTTON_TREE_3_ROW_4_COL_1   1139
#define IDC_CORPSE_GROUP                1140
#define IDC_BUTTON_TREE_3_ROW_4_COL_2   1140
#define IDC_PREV_BUTTON                 1140
#define IDC_MERC_GROUP                  1141
#define IDC_BUTTON_TREE_3_ROW_4_COL_3   1141
#define IDC_NEXT_BUTTON                 1141
#define IDC_GOLEM_GROUP                 1142
#define IDC_BUTTON_TREE_3_ROW_5_COL_1   1142
#define IDC_INV_WEAPON_I                1143
#define IDC_BUTTON_TREE_3_ROW_5_COL_2   1143
#define IDC_INV_WEAPON_II               1144
#define IDC_BUTTON_TREE_3_ROW_5_COL_3   1144
#define IDC_INV_CUBE_GROUP              1145
#define IDC_BUTTON_TREE_3_ROW_6_COL_1   1145
#define IDC_INV_BELT_GROUP              1146
#define IDC_BUTTON_TREE_3_ROW_6_COL_2   1146
#define IDC_FILL_BUTTON                 1147
#define IDC_BUTTON_TREE_3_ROW_6_COL_3   1147
#define IDC_FILL_BUTTON2                1148
#define IDC_PAGE_COMBO                  1150
#define IDC_SHARED_STASH_BUTTON         1151
#define ID_VIEW_REFRESH                 32772
#define ID_VIEW_LEVEL_REQ               32773
#define ID_OPTIONS_BACKUP_CHAR          32774
#define ID_OPTIONS_RESTORE_CHAR         32775
#define ID_OPTIONS_CHECK_CHAR           32776
#define ID_OPTIONS_INDESTRUCTIBLEFORALLITEMS 32777
#define ID_OPTIONS_MAX_EVERYTHING       32778
#define ID_ITEM_CONTEXT_INDESTRUCTIBLE  32779
#define ID_OPTIONS_UPGRADE_GEMS         32780
#define ID_VIEW_WAYPOINTS               32781
#define ID_VIEW_QUESTS                  32782
#define ID_VIEW_SKILL_TREE              32783
#define ID_OPTIONS_UPGRADE_POTIONS      32784
#define ID_OPTIONS_UPGRADE_REJUVENATIONS 32785
#define ID_OPTIONS_GOLD                 32786
#define ID_OPTIONS_GPS_CONVERTOR        32787
#define ID_OPTIONS_MAXFILLSTACKABLES    32788
#define ID_OPTIONS_MAXDURABILITYFORALLITEMS 32789
#define ID_OPTIONS_RESET_STATS          32790
#define ID_FILE_EXPORT_AS_JSON          32791
#define ID_FILE_SAVE_AS_VERSION         32792
#define ID_VIEW_MERCENARY               32793
#define ID_OPTIONS_FIXALLITEMS          32794
#define ID_ITEM_CONTEXT_REMOVE_PERSONALIZATION 32795
#define ID_ITEM_CONTEXT_LOAD            32796
#define ID_ITEM_CONTEXT_FIX             32797
#define ID_ITEM_CONTEXT_MAXDURABILITY   32798
#define ID_VIEW_ITEMS                   32799
#define ID_ITEM_CONTEXT_UPGRADE_GEM     32800
#define ID_ITEM_CONTEXT_UPGRADE_POTION  32801
#define ID_ITEM_CONTEXT_UPGRADE_REJUVENATION 32802
#define ID_ITEM_CONTEXT_GPS_CONVERTOR   32803
#define ID_OPTIONS_MAXSOCKETSFORALLITEMS 32804
#define ID_ITEM_CONTEXT_MAXSOCKETS      32805
#define ID_ITEM_CONTEXT_ADDSOCKET       32806
#define ID_ITEM_CONTEXT_PERSONALIZE     32807
#define ID_OPTIONS_GPS_CREATOR          32808
#define ID_ITEM_CONTEXT_GPS_CREATOR     32809
#define ID_ITEM_CONTEXT_UPGRADE_GEMS    32810
#define ID_ITEM_CONTEXT_UPGRADE_POTIONS 32811
#define ID_ITEM_CONTEXT_UPGRADE_REJUVENATIONS 32812
#define ID_ITEM_CONTEXT_MAXFILLSTACKABLES 32813
#define ID_ITEM_CONTEXT_FIXALLITEMS     32814
#define ID_ITEM_CONTEXT_MAXDURABILITYFORALLITEMS 32815
#define ID_ITEM_CONTEXT_INDESTRUCTIBLEFORALLITEMS 32816
#define ID_ITEM_CONTEXT_MAXSOCKETSFORALLITEMS 32817
#define ID_VIEW_SHAREDSTASH             32818
#define ID_ITEM_CONTEXT_UNSOCKET        32819
#define ID_ITEM_CONTEXT_APPLY_RUNEWORD  32820
#define ID_ITEM_CONTEXT_IMPORT_ITEM     32821
#define ID_ITEM_CONTEXT_EXPORT_ITEM     32822
#define ID_ITEM_CONTEXT_REMOVE_ITEM     32823
#define ID_ITEM_CONTEXT_UPGRADE_SUPERIORQUALITYALLITEMS 32824
#define ID_OPTIONS_ALLITEMSSUPERIORQUALITY 32825
#define ID_ITEM_CONTEXT_MAKESUPERIORQUALITY 32826
#define ID_ITEM_CONTEXT_UPGRADEITEMTIER 32827
#define ID_ITEM_CONTEXT_UPGRADE_ALLITEMSMAXTIER 32828
#define ID_OPTIONS_ALLITEMSHIGHERTIER   32829
#define ID_ITEM_CONTEXT_MAKEETHEREAL    32830
#define ID_ITEM_CONTEXT_REMOVEETHEREAL  32831
#define ID_ITEM_CONTEXT_CREATE_ITEM     32832

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        731
#define _APS_NEXT_COMMAND_VALUE         32831
#define _APS_NEXT_CONTROL_VALUE         1152
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
