//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by D2Editor.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_D2EDITOR_DIALOG             102
#define IDS_OLD_APP_TITLE               102
#define IDR_MAINFRAME                   128
#define IDB_CHAR_BITMAP                 131
#define IDB_QUEST_BITMAP                133
#define IDB_SKILL_BITMAP                134
#define IDB_EXIT_BITMAP                 135
#define IDB_WAYPOINT_BITMAP             137
#define IDB_STATS_BITMAP                138
#define IDD_D2LEVELINFO_DIALOG          140
#define IDD_WAYPOINTS_DIALOG            142
#define IDD_QUESTS_DIALOG               143
#define IDD_AMAZON_SKILLS_DIALOG        144
#define IDD_SKILLS_DIALOG               144
#define IDD_GPS_CONVERTER_DIALOG        147
#define IDB_STATS_LEFT_BITMAP           152
#define IDD_MERC_DIALOG                 153
#define IDR_RESOURCE_HEADER             154
#define IDD_ITEMS_DIALOG                155
#define IDB_INVQLT                      157
#define IDB_INVLEA                      158
#define IDB_INVHLA                      159
#define IDB_INVSTU                      160
#define IDB_INVRNG                      161
#define IDB_INVSCL                      162
#define IDB_INVCHN                      163
#define IDB_INVBRS                      164
#define IDB_INVSPL                      165
#define IDB_INVPLT                      166
#define IDB_INVFLD                      167
#define IDB_INVGTH                      168
#define IDB_INVFUL                      169
#define IDB_INVAAR                      170
#define IDB_INVLTP                      171
#define IDB_INVLBT                      172
#define IDB_INVVBT                      173
#define IDB_INVMBT                      174
#define IDB_INVTBT                      175
#define IDB_INVHBT                      176
#define IDB_INVLGL                      178
#define IDB_INVVGL                      179
#define IDB_INVMGL                      180
#define IDB_INVTGL                      181
#define IDB_INVHGL                      182
#define IDB_INVCAP                      183
#define IDB_INVSKP                      184
#define IDB_INVHLM                      185
#define IDB_INVFHL                      186
#define IDB_INVGHM                      187
#define IDB_INVCRN                      188
#define IDB_INVMSK                      189
#define IDB_INVBHM                      190
#define IDB_INVBA1                      191
#define IDB_INVBA2                      192
#define IDB_INVBA3                      193
#define IDB_INVBA4                      194
#define IDB_INVBA5                      195
#define IDB_INVCI0                      196
#define IDB_INVCI1                      197
#define IDB_INVCI2                      198
#define IDB_INVCI3                      199
#define IDB_INVDR1                      200
#define IDB_INVDR2                      201
#define IDB_INVDR3                      202
#define IDB_INVDR5                      203
#define IDB_INVDR4                      204
#define IDB_INVLBL                      205
#define IDB_INVVBL                      206
#define IDB_INVMBL                      207
#define IDB_INVTBL                      208
#define IDB_INVHBL                      209
#define IDB_INVBUC                      210
#define IDB_INVSML                      211
#define IDB_INVLRG                      212
#define IDB_INVKIT                      213
#define IDB_INVTOW                      214
#define IDB_INVGTS                      215
#define IDB_INVBSH                      216
#define IDB_INVSPK                      217
#define IDB_INVNE1                      218
#define IDB_INVNE2                      219
#define IDB_INVNE3                      220
#define IDB_INVNE4                      221
#define IDB_INVNE5                      222
#define IDB_INVPA1                      223
#define IDB_INVPA2                      224
#define IDB_INVPA3                      225
#define IDB_INVPA4                      226
#define IDB_INVPA5                      227
#define IDB_INVHAX                      228
#define IDB_INVAXE                      229
#define IDB_INV2AX                      230
#define IDB_INVMPI                      231
#define IDB_INVWAX                      232
#define IDB_INVLAX                      233
#define IDB_INVBRX                      234
#define IDB_INVBTX                      235
#define IDB_INVGAX                      236
#define IDB_INVGIX                      237
#define IDB_INVWND                      238
#define IDB_INVYWN                      239
#define IDB_INVBWN                      240
#define IDB_INVGWN                      241
#define IDB_INVCLB                      242
#define IDB_INVSPC                      243
#define IDB_INVMAC                      244
#define IDB_INVMST                      245
#define IDB_INVFLA                      246
#define IDB_INVWHM                      247
#define IDB_INVMAU                      248
#define IDB_INVGMA                      249
#define IDB_INVSCP                      250
#define IDB_INVGSC                      251
#define IDB_INVWSP                      252
#define IDB_INVSSD                      253
#define IDB_INVSCM                      254
#define IDB_INVSBR                      255
#define IDB_INVFLC                      256
#define IDB_INVCRS                      257
#define IDB_INVBSD                      258
#define IDB_INVLSD                      259
#define IDB_INVWSD                      260
#define IDB_INV2HS                      261
#define IDB_INVCLM                      262
#define IDB_INVGIS                      263
#define IDB_INVBSW                      264
#define IDB_INVFLB                      265
#define IDB_INVGSD                      266
#define IDB_INVDGR                      267
#define IDB_INVDIR                      268
#define IDB_INVKRS                      269
#define IDB_INVBLD                      270
#define IDB_INVTKN                      271
#define IDB_INVTAX                      272
#define IDB_INVBKF                      273
#define IDB_INVBAL                      274
#define IDB_INVJAV                      275
#define IDB_INVPIL                      276
#define IDB_INVSSP                      277
#define IDB_INVGLV                      278
#define IDB_INVTSP                      279
#define IDB_INVSPR                      280
#define IDB_INVTRI                      281
#define IDB_INVBRN                      282
#define IDB_INVSPT                      283
#define IDB_INVPIK                      284
#define IDB_INVBAR                      285
#define IDB_INVVOU                      286
#define IDB_INVSCY                      287
#define IDB_INVPAX                      288
#define IDB_INVHAL                      289
#define IDB_INVWSC                      290
#define IDB_INVSST                      291
#define IDB_INVLST                      292
#define IDB_INVCST                      293
#define IDB_INVBST                      294
#define IDB_INVWST                      295
#define IDB_INVSBW                      296
#define IDB_INVHBW                      297
#define IDB_INVLBW                      298
#define IDB_INVCBW                      299
#define IDB_INVSBB                      300
#define IDB_INVLBB                      301
#define IDB_INVSWB                      302
#define IDB_INVLWB                      303
#define IDB_INVLXB                      304
#define IDB_INVMXB                      305
#define IDB_INVHXB                      306
#define IDB_INVRXB                      307
#define IDB_INVGPL                      308
#define IDB_INVOPL                      309
#define IDB_INVGPM                      310
#define IDB_INVOPM                      311
#define IDB_INVGPS                      312
#define IDB_INVOPS                      313
#define IDB_INVD33                      314
#define IDB_INVG33                      315
#define IDB_INVLEG                      316
#define IDB_INVHMR                      317
#define IDB_INVHFH                      318
#define IDB_INVHST                      319
#define IDB_INVMSF                      320
#define IDB_INVQF1                      321
#define IDB_INVQF2                      322
#define IDB_INVKTR                      323
#define IDB_INVAXF                      324
#define IDB_INVCLW                      325
#define IDB_INVSKR                      326
#define IDB_INVOB1                      328
#define IDB_INVOB2                      329
#define IDB_INVOB3                      330
#define IDB_INVOB4                      331
#define IDB_INVOB5                      332
#define IDB_INVAM1                      333
#define IDB_INVAM2                      334
#define IDB_INVAM3                      335
#define IDB_INVAM4                      336
#define IDB_INVAM5                      337
#define IDB_INVJBI                      339
#define IDB_INVGSVC                     340
#define IDB_INVRAMN                     341
#define IDB_INVAMU                      342
#define IDB_INVNPS                      343
#define IDB_INVQVR                      344
#define IDB_INVRBER                     345
#define IDB_INVCQV                      346
#define IDB_INVSBK                      347
#define IDB_INVRCHAM                    350
#define IDB_INVGSVA                     351
#define IDB_INVGSWA                     352
#define IDB_INVGSGA                     353
#define IDB_INVGSRA                     354
#define IDB_INVGSBA                     355
#define IDB_INVSKC                      356
#define IDB_INVGSYA                     357
#define IDB_INVGSWC                     358
#define IDB_INVRDOL                     359
#define IDB_INVREL                      360
#define IDB_INVRELD                     361
#define IDB_INVPOT                      362
#define IDB_INVGSGC                     363
#define IDB_INVRETH                     364
#define IDB_INVRFAL                     365
#define IDB_INVGSVB                     366
#define IDB_INVGSWB                     367
#define IDB_INVGSGB                     368
#define IDB_INVGSBB                     369
#define IDB_INVSKF                      370
#define IDB_INVGSYB                     371
#define IDB_INVGSRB                     372
#define IDB_INVGSVD                     373
#define IDB_INVGSWD                     374
#define IDB_INVGSGD                     375
#define IDB_INVGSRD                     376
#define IDB_INVGSBD                     377
#define IDB_INVSKL                      378
#define IDB_INVGSYD                     379
#define IDB_INVVPL                      380
#define IDB_INVGLD                      381
#define IDB_INVCHM3                     382
#define IDB_INVHP4                      383
#define IDB_INVMP4                      384
#define IDB_INVRGUL                     385
#define IDB_INVRPS                      386
#define IDB_INVRHEL                     387
#define IDB_INVHRB                      388
#define IDB_INVBOX                      389
#define IDB_INVHSCR                     390
#define IDB_INVRIO                      393
#define IDB_INVRIST                     394
#define IDB_INVRITH                     395
#define IDB_INVRJO                      396
#define IDB_INVJEW                      397
#define IDB_INVKEY                      399
#define IDB_INVBRNZ                     400
#define IDB_INVEAR                      401
#define IDB_INVEYE                      402
#define IDB_INVHRT                      403
#define IDB_INVRKO                      404
#define IDB_INVBBB                      405
#define IDB_INVCHM2                     406
#define IDB_INVRLEM                     407
#define IDB_INVHP2                      408
#define IDB_INVMP2                      409
#define IDB_INVRLO                      410
#define IDB_INVRLUM                     411
#define IDB_INVRMAL                     412
#define IDB_INVBPS                      414
#define IDB_INVMSS                      415
#define IDB_INVHP1                      416
#define IDB_INVMP1                      417
#define IDB_INVBPL                      418
#define IDB_INVRNEF                     420
#define IDB_INVROHM                     421
#define IDB_INVRORT                     422
#define IDB_INVGSVE                     423
#define IDB_INVGSWE                     424
#define IDB_INVGSGE                     425
#define IDB_INVGSRE                     426
#define IDB_INVGSBE                     427
#define IDB_INVSKZ                      428
#define IDB_INVGSYE                     429
#define IDB_INVXYZ                      430
#define IDB_INVRPUL                     431
#define IDB_INVRRAL                     432
#define IDB_INVVPS                      433
#define IDB_INVRIN                      434
#define IDB_INVRPL                      435
#define IDB_INVGSRC                     437
#define IDB_INVGSBC                     438
#define IDB_INVRSC                      439
#define IDB_INVSCB                      440
#define IDB_INVBSC                      443
#define IDB_INVRSHAE                    444
#define IDB_INVFANG                     447
#define IDB_INVFLAG                     448
#define IDB_INVSKU                      457
#define IDB_INVCHM1                     458
#define IDB_INVRSOL                     459
#define IDB_INVWPS                      460
#define IDB_INVHP5                      461
#define IDB_INVMP5                      462
#define IDB_INVRSUR                     463
#define IDB_INVRTAL                     464
#define IDB_INVYPS                      465
#define IDB_INVMPH                      466
#define IDB_INVGBI                      467
#define IDB_INVRTHUL                    468
#define IDB_INVRTIR                     469
#define IDB_INVTOA                      470
#define IDB_INVRBK                      471
#define IDB_INVBBK                      472
#define IDB_INVVIP                      473
#define IDB_INVGSYC                     474
#define IDB_INVTRCH                     475
#define IDB_INVFED                      476
#define IDB_INVCEH                      477
#define IDB_INVTES                      478
#define IDB_INVBET                      479
#define IDB_INVRUM                      480
#define IDB_INVRVEX                     481
#define IDB_INVRZOD                     482
#define IDB_INVEMPTY                    483
#define IDB_INV_ARMOR                   484
#define IDB_INV_BELT                    485
#define IDB_INV_BOOTS                   486
#define IDB_INV_HELM_GLOVE_0_0          487
#define IDB_INV_HELM_GLOVE_0_1          488
#define IDB_INV_RING_AMULET_0_0         489
#define IDB_INV_RING_AMULET_0_1         490
#define IDB_INV_WEAPONS                 491
#define IDR_ITEM_MENU                   492
#define IDB_INV_EMPTY_SOCKET            493
#define IDC_DIFFICULTY                  1000
#define IDC_CHAR_NAME                   1001
#define IDC_CHAR_LEVEL                  1002
#define IDC_CHAR_STRENGTH               1003
#define IDC_CHAR_ENERGY                 1004
#define IDC_CHAR_DEXTERITY              1005
#define IDC_CHAR_VITALITY               1006
#define IDC_CUR_LIFE                    1007
#define IDC_MAX_LIFE                    1008
#define IDC_CUR_MANA                    1009
#define IDC_MAX_MANA                    1010
#define IDC_CUR_STAMINA                 1011
#define IDC_MAX_STAMINA                 1012
#define IDC_CHAR_EXPERIENCE             1013
#define IDC_WAYPOINTS_BTN               1015
#define IDC_EDIT_SKILLS_BTN             1016
#define IDC_QUESTS_BTN                  1017
#define IDC_CHAR_CLASS_CMB              1018
#define IDC_CHAR_NEXT_EXPERIENCE        1019
#define IDC_STARTING_ACT_CMB            1020
#define IDC_CHAR_TITLE_CMB              1021
#define IDC_MAX_ALL_BTN                 1022
#define IDC_GOLD_IN_BELT                1023
#define IDC_GOLD_IN_STASH               1024
#define IDC_STATS_LEFT                  1025
#define IDC_HARDCORE_CHECK              1027
#define IDC_RESURRECTED_CHECK           1028
#define IDC_EXPANSION_CHECK             1029
#define IDC_LADDER_CHECK                1030
#define IDC_ATTRIBUTE                   1031
#define IDC_QUIT_BTN                    1032
#define IDC_ABOUT_VERSION               1033
#define IDC_CHAR_DEFENSE                1033
#define IDC_APP_COPYRIGHT               1034
#define IDC_CHAR_DAMAGE                 1034
#define IDC_LEVELINFO_GRID              1035
#define IDC_EDIT_SET_ALL_SKILLS         1035
#define IDC_APP_COPYRIGHT2              1035
#define IDC_CHAR_RESIST_FIRE            1035
#define IDC_RADIO_DIFFICULTY_NORMAL     1036
#define IDC_STATIC_TREE_1               1036
#define IDC_CHAR_RESIST_COLD            1036
#define IDC_RADIO_DIFFICULTY_NIGHTMARE  1037
#define IDC_STATIC_TREE_2               1037
#define IDC_CHAR_RESIST_LIGHTNING       1037
#define IDC_RADIO_DIFFICULTY_HELL       1038
#define IDC_STATIC_TREE_3               1038
#define IDC_CHAR_RESIST_POISON          1038
#define IDC_ACTIVATE_ALL                1039
#define IDC_COMPLETE_ALL                1039
#define IDC_SET_ALL_SKILLS              1039
#define IDC_CHECK_ACTI_1                1040
#define IDC_CHECK_ACTI_QUEST_1          1040
#define IDC_EDIT_TREE_1_SKILL_1         1040
#define IDC_CHECK_ACTI_2                1041
#define IDC_CHECK_ACTI_QUEST_2          1041
#define IDC_EDIT_TREE_1_SKILL_2         1041
#define IDC_CHECK_ACTI_3                1042
#define IDC_CHECK_ACTI_QUEST_3          1042
#define IDC_EDIT_TREE_1_SKILL_3         1042
#define IDC_CHECK_ACTI_4                1043
#define IDC_CHECK_ACTI_QUEST_4          1043
#define IDC_EDIT_TREE_1_SKILL_4         1043
#define IDC_CHECK_ACTI_5                1044
#define IDC_CHECK_ACTI_QUEST_5          1044
#define IDC_EDIT_TREE_1_SKILL_5         1044
#define IDC_CHECK_ACTI_6                1045
#define IDC_CHECK_ACTI_QUEST_6          1045
#define IDC_EDIT_TREE_1_SKILL_6         1045
#define IDC_CHECK_ACTI_7                1046
#define IDC_CHECK_ACTII_QUEST_1         1046
#define IDC_EDIT_TREE_1_SKILL_7         1046
#define IDC_CHECK_ACTI_8                1047
#define IDC_CHECK_ACTII_QUEST_2         1047
#define IDC_EDIT_TREE_1_SKILL_8         1047
#define IDC_CHECK_ACTI_9                1048
#define IDC_CHECK_ACTII_QUEST_3         1048
#define IDC_EDIT_TREE_1_SKILL_9         1048
#define IDC_CHECK_ACTII_1               1049
#define IDC_CHECK_ACTII_QUEST_4         1049
#define IDC_EDIT_TREE_1_SKILL_10        1049
#define IDC_CHECK_ACTII_2               1050
#define IDC_CHECK_ACTII_QUEST_5         1050
#define IDC_EDIT_TREE_2_SKILL_1         1050
#define IDC_CHECK_ACTII_3               1051
#define IDC_CHECK_ACTII_QUEST_6         1051
#define IDC_EDIT_TREE_2_SKILL_2         1051
#define IDC_CHECK_ACTII_4               1052
#define IDC_CHECK_ACTIII_QUEST_1        1052
#define IDC_EDIT_TREE_2_SKILL_3         1052
#define IDC_CHECK_ACTII_5               1053
#define IDC_CHECK_ACTIII_QUEST_2        1053
#define IDC_EDIT_TREE_2_SKILL_4         1053
#define IDC_CHECK_ACTII_6               1054
#define IDC_CHECK_ACTIII_QUEST_3        1054
#define IDC_EDIT_TREE_2_SKILL_5         1054
#define IDC_CHECK_ACTII_7               1055
#define IDC_CHECK_ACTIII_QUEST_4        1055
#define IDC_EDIT_TREE_2_SKILL_6         1055
#define IDC_CHECK_ACTII_8               1056
#define IDC_CHECK_ACTIII_QUEST_5        1056
#define IDC_EDIT_TREE_2_SKILL_7         1056
#define IDC_CHECK_ACTII_9               1057
#define IDC_CHECK_ACTIII_QUEST_6        1057
#define IDC_EDIT_TREE_2_SKILL_8         1057
#define IDC_CHECK_ACTIII_1              1058
#define IDC_CHECK_ACTIV_QUEST_1         1058
#define IDC_EDIT_TREE_2_SKILL_9         1058
#define IDC_CHECK_ACTIII_2              1059
#define IDC_CHECK_ACTIV_QUEST_2         1059
#define IDC_EDIT_TREE_2_SKILL_10        1059
#define IDC_CHECK_ACTIII_3              1060
#define IDC_CHECK_ACTIV_QUEST_3         1060
#define IDC_EDIT_TREE_3_SKILL_1         1060
#define IDC_CHECK_ACTIII_4              1061
#define IDC_CHECK_ACTV_QUEST_1          1061
#define IDC_EDIT_TREE_3_SKILL_2         1061
#define IDC_CHECK_ACTIII_5              1062
#define IDC_CHECK_ACTV_QUEST_2          1062
#define IDC_EDIT_TREE_3_SKILL_3         1062
#define IDC_CHECK_ACTIII_6              1063
#define IDC_CHECK_ACTV_QUEST_3          1063
#define IDC_EDIT_TREE_3_SKILL_4         1063
#define IDC_CHECK_ACTIII_7              1064
#define IDC_CHECK_ACTV_QUEST_4          1064
#define IDC_EDIT_TREE_3_SKILL_5         1064
#define IDC_CHECK_ACTIII_8              1065
#define IDC_CHECK_ACTV_QUEST_5          1065
#define IDC_EDIT_TREE_3_SKILL_6         1065
#define IDC_CHECK_ACTIII_9              1066
#define IDC_CHECK_ACTV_QUEST_6          1066
#define IDC_EDIT_TREE_3_SKILL_7         1066
#define IDC_CHECK_ACTIV_1               1067
#define IDC_CHECK_QUEST_FARM            1067
#define IDC_EDIT_TREE_3_SKILL_8         1067
#define IDC_CHECK_ACTIV_2               1068
#define IDC_CHECK_ACTI_RESET_STATS      1068
#define IDC_EDIT_TREE_3_SKILL_9         1068
#define IDC_CHECK_ACTIV_3               1069
#define IDC_EDIT_TREE_3_SKILL_10        1069
#define IDC_CHECK_ACTV_1                1070
#define IDC_STATIC_TREE_1_SKILL_1       1070
#define IDC_CHECK_ACTV_2                1071
#define IDC_STATIC_TREE_1_SKILL_2       1071
#define IDC_CHECK_ACTV_3                1072
#define IDC_STATIC_TREE_1_SKILL_3       1072
#define IDC_CHECK_ACTV_4                1073
#define IDC_STATIC_TREE_1_SKILL_4       1073
#define IDC_CHECK_ACTV_5                1074
#define IDC_STATIC_TREE_1_SKILL_5       1074
#define IDC_CHECK_ACTV_6                1075
#define IDC_STATIC_TREE_1_SKILL_6       1075
#define IDC_CHECK_ACTV_7                1076
#define IDC_STATIC_TREE_1_SKILL_7       1076
#define IDC_CHECK_ACTV_8                1077
#define IDC_STATIC_TREE_1_SKILL_8       1077
#define IDC_CHECK_ACTV_9                1078
#define IDC_STATIC_TREE_1_SKILL_9       1078
#define IDC_STATIC_TREE_1_SKILL_10      1079
#define IDC_STATIC_ACTV                 1080
#define IDC_STATIC_TREE_2_SKILL_1       1080
#define IDC_STATIC_TREE_2_SKILL_2       1081
#define IDC_STATIC_TREE_2_SKILL_3       1082
#define IDC_STATIC_TREE_2_SKILL_4       1083
#define IDC_STATIC_TREE_2_SKILL_5       1084
#define IDC_STATIC_TREE_2_SKILL_6       1085
#define IDC_STATIC_TREE_2_SKILL_7       1086
#define IDC_STATIC_TREE_2_SKILL_8       1087
#define IDC_STATIC_TREE_2_SKILL_9       1088
#define IDC_STATIC_TREE_2_SKILL_10      1089
#define IDC_STATIC_TREE_3_SKILL_1       1090
#define IDC_STATIC_TREE_3_SKILL_2       1091
#define IDC_STATIC_TREE_3_SKILL_3       1092
#define IDC_STATIC_TREE_3_SKILL_4       1093
#define IDC_STATIC_TREE_3_SKILL_5       1094
#define IDC_STATIC_TREE_3_SKILL_6       1095
#define IDC_STATIC_TREE_3_SKILL_7       1096
#define IDC_STATIC_TREE_3_SKILL_8       1097
#define IDC_STATIC_TREE_3_SKILL_9       1098
#define IDC_STATIC_TREE_3_SKILL_10      1099
#define IDC_FROM_COMBO                  1100
#define IDC_TO_COMBO                    1101
#define IDC_MFCLINK1                    1102
#define IDC_ENERGY_PLUS_BTN             1103
#define IDC_VITALITY_PLUS_BTN           1104
#define IDC_STRENGTH_PLUS_BTN           1105
#define IDC_DEXTERITY_PLUS_BTN          1106
#define IDC_STATS_LEFT_IMAGE            1107
#define IDC_BACKGROUND_BOX              1108
#define IDC_MERC_HIRED                  1109
#define IDC_TYPE_DASH_2                 1110
#define IDC_INV_HEAD                    1111
#define IDC_INV_CORPSE_HEAD             1112
#define IDC_INV_MERC_HEAD               1113
#define IDC_INV_CORPSE_HAND_LEFT        1114
#define IDC_INV_HAND_LEFT               1115
#define IDC_INV_MERC_HAND_LEFT          1116
#define IDC_INV_TORSO                   1117
#define IDC_INV_CORPSE_TORSO            1118
#define IDC_INV_MERC_TORSO              1119
#define IDC_INV_HAND_RIGHT              1120
#define IDC_INV_CORPSE_HAND_RIGHT       1121
#define IDC_INV_MERC_HAND_RIGHT         1122
#define IDC_INV_NECK                    1123
#define IDC_INV_CORPSE_NECK             1124
#define IDC_INV_BELT                    1125
#define IDC_INV_CORPSE_BELT             1126
#define IDC_INV_BOOTS                   1127
#define IDC_INV_CORPSE_BOOTS            1128
#define IDC_INV_RING_RIGHT              1129
#define IDC_INV_CORPSE_RING_RIGHT       1130
#define IDC_INV_RING_LEFT               1131
#define IDC_INV_CORPSE_RING_LEFT        1132
#define IDC_INV_GLOVE                   1133
#define IDC_INV_CORPSE_GLOVE            1134
#define IDC_INV_GOLEM                   1135
#define IDC_INV_GRID                    1136
#define IDC_INV_STASH_GRID              1137
#define IDC_INV_CUBE_GRID               1138
#define IDC_INV_BELT_GRID               1139
#define IDC_CORPSE_GROUP                1140
#define IDC_MERC_GROUP                  1141
#define IDC_GOLEM_GROUP                 1142
#define IDC_INV_WEAPON_I                1143
#define IDC_INV_WEAPON_II               1144
#define IDC_INV_CUBE_GROUP              1145
#define IDC_INV_BELT_GROUP              1146
#define ID_VIEW_REFRESH                 32772
#define ID_VIEW_LEVEL_REQ               32773
#define ID_OPTIONS_BACKUP_CHAR          32774
#define ID_OPTIONS_RESTORE_CHAR         32775
#define ID_OPTIONS_CHECK_CHAR           32776
#define ID_OPTIONS_CHECK_CHARACTER      32777
#define ID_OPTIONS_MAX_EVERYTHING       32778
#define ID_OPTIONS_REMOVE               32779
#define ID_OPTIONS_UPGRADE_GEMS         32780
#define ID_VIEW_WAYPOINTS               32781
#define ID_VIEW_QUESTS                  32782
#define ID_VIEW_SKILL_TREE              32783
#define ID_OPTIONS_UPGRADE_POTIONS      32784
#define ID_OPTIONS_UPGRADE_REJUVENATION 32785
#define ID_OPTIONS_GOLD                 32786
#define ID_OPTIONS_GPS_CONVERTOR        32787
#define ID_OPTIONS_MAXFILLSTACKABLES    32788
#define ID_OPTIONS_MAXDURABILITYFORALLITEMS 32789
#define ID_OPTIONS_RESET_STATS          32790
#define ID_FILE_EXPORT_AS_JSON          32791
#define ID_FILE_EXPORT_AS_JSON_SERIALIZED 32792
#define ID_VIEW_MERCENARY               32793
#define ID_OPTIONS_FIXALLITEMS          32794
#define ID_OPTIONS_REFILLALLSTACKABLES  32795
#define ID_ITEM_CONTEXT_LOAD            32796
#define ID_ITEM_CONTEXT_FIX             32797
#define ID_ITEM_CONTEXT_MAXDURABILITY   32798
#define ID_VIEW_ITEMS                   32799
#define ID_ITEM_CONTEXT_UPGRADE_GEM     32800
#define ID_ITEM_CONTEXT_UPGRADE_POTION  32801
#define ID_ITEM_CONTEXT_UPGRADE_REJUVENATION 32802
#define ID_ITEM_CONTEXT_GPS_CONVERTOR   32803
#define ID_OPTIONS_MAXSOCKETSFORALLITEMS 32804
#define ID_ITEM_CONTEXT_MAXSOCKETS      32805
#define ID_ITEM_CONTEXT_ADDSOCKET       32806

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        494
#define _APS_NEXT_COMMAND_VALUE         32807
#define _APS_NEXT_CONTROL_VALUE         1147
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
